### ISSUE TITLE
[Linux] Secrets Provider unavailable in Flatpak

### ISSUE THREAD

**Issue by dragynbane222** [goatcorp/FFXIVQuickLauncher#1019]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to FFXIV updating and plugins not working correctly.

### What did you do?

I set my password to be saved, and found out that kwallet (the secrets provider for KDE) is unavailable in Flatpak, I'm going to attempt manually compiling and installing without flatpak here shortly, I anticipate that will be able to detect kwallet, I'll update if that's the case.

I'm guessing the flatpak version has to be compiled in a certain way so as flatpak can pass support for kwallet or gnome-keyring.

### Platform

Linux (native)

### Wine/Proton runner version

wine-xiv-staging-fsync-git-7.7.r14.gd7507fbe

### Relevant log output

```shell
Take care! No secrets provider is installed or configured. Passwords can't be saved.
```

**Comment by tommadness** [comment]
KWallet does not provide `freedesktop.secrets`, which XIVLauncher is specifically looking for.

**Comment by dragynbane222** [comment]
> KWallet does not provide `freedesktop.secrets`, which XIVLauncher is specifically looking for.

Ah, good to know, I'll close this since installing gnome-keyring and setting it to autostart seems to work. It's not an elegant workaround for KDE, but it works.
