### ISSUE TITLE
Game not launching

### ISSUE THREAD

**Issue by FemtoHawk** [goatcorp/FFXIVQuickLauncher#1021]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to FFXIV updating and plugins not working correctly.

### What did you do?

Use Steam Service account checked, XIVAlexander starts running but Dalamud Injector hangs at 12.8MB used, Final Fantasy XIV process never starts. No information from log. Problem is reoccurring, not fixed by restarts but fixes itself sometimes (possibly when Dalamud updates?)

### Platform

Windows

**Comment by FemtoHawk** [comment]
Final Fantasy XIV process starts after closing Dalmud Injector and Quicklauncher but game still doesn't start up (nothing on taskbar) and the process for FFXIV hangs at 11.6 MB memory used.

**Comment by Zi-SH** [comment]
What happens if you attempt to launch the FFXIV process with XIVLauncher and without XIVAlexander?

**Comment by FemtoHawk** [comment]
> What happens if you attempt to launch the FFXIV process with XIVLauncher and without XIVAlexander?

Works, seems to be an XIVAlexander issue, reinstalling XIVAlexander fixed it, thanks.
