### ISSUE TITLE
Dalamud showing loaded plugins in welcome message, but it's unchecked

### ISSUE THREAD

**Issue by Rynn21** [goatcorp/FFXIVQuickLauncher#1037]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to FFXIV updating and plugins not working correctly.

### What did you do?

I unchecked the "display loaded plugins in the welcome message", yet it still loads in chat when I start the game.
![Screenshot 2022-06-10 122947](https://user-images.githubusercontent.com/102271454/174448037-d2494a4c-4b1a-45c6-a87c-aecae638b1c3.png)

### Platform

Windows

**Comment by HQuest** [comment]
Not exactly a bug,. The option "display loaded plugins in the welcome message" only suppresses the list of plug-ins, but the message Dalamud was loaded and the plug-in count is still part of the XL initialization.

If you want a "quiet" option to not show you have Dalamud displayed and/or the count of plug-ins loaded, this is an improvement request.

**Comment by NotNite** [comment]
Going through our old issues (sorry!) - this is the wrong repo to report this on. If you want the behavior described above, leave it on [the right repository](https://github.com/goatcorp/Dalamud).
