### ISSUE TITLE
XIVLauncher crashing game after login

### ISSUE THREAD

**Issue by TwentyGaugeHigh** [goatcorp/FFXIVQuickLauncher#1042]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to FFXIV updating and plugins not working correctly.

### What did you do?

Launch XIVLauncher, game loads normally
Login to game
After about 5-10 minutes, game crashes to desktop with no error message
XIVLauncher will not open afterwards or attempt to launch the game
Restart computer with no resolution
Need to reinstall XIVLauncher to resolve

### Platform

Windows

**Comment by TwentyGaugeHigh** [comment]
The .exe seems to be deleteing itself when crashing. Exceptions for XIVLauncher and FFXIV are in place in my AV (Avast). This latest crash was just shy of 5 minutes after launching.

**Comment by reiichi001** [comment]
Hello! Please ensure you've made exceptions for both files and folders for your antivirus, and have restarted your computer afterward. <https://goatcorp.github.io/faq/xl_troubleshooting#q-how-do-i-whitelist-xivlauncher-and-dalamud-so-my-antivirus-leaves-them-alone>

If you've copied and pasted the paths, you will need to remove those and use the full path, as most programs outside of native built-in Windows utilities (or file explorer windows) won't resolve a shortcut path.

`%appdata%` is a shortcut to `C:\Users\<your username>\AppData\Roaming`
`%localappdata%` is a shortcut to `C:\Users\<your username>\AppData\Local`

You will need to ensure that you've whitelisted the XIVLauncher bootstrapper and versioned out release, and do the same for Dalamud if you want to use plugins.

Post-reboot, I'd also recommend forcing a clean download of Dalamud by manually removing its files. XIVLauncher will then redownload them when you next open the application.

General "how to delete dalamud" steps:
1. Close the game and XIVLauncher
2. Go to `%AppData%\XIVLauncher`
3. Remove the `Addon` and `dalamudAssets` folders
4. Start the game now
5. Let us know if the issue persists

If you use other addons/tools that modify your FFXIV installation (or the program while running), it may help to turn those off and see if the issue persists. Generally though, if an exe goes missing, it is almost assuredly your antivirus. (Unless your disk is failing, but you'd probably have larger issues if that was happening)

**Comment by TwentyGaugeHigh** [comment]
I was indeed using the shortcut paths to appdata, thank you for the heads up! I've re-added the exceptions with the absolute paths along with the others suggested in the FAQ. Cleared everything out and did a clean re-install as suggested and I believe this fixed the issue! 

Thank you for the assist! :)
