### ISSUE TITLE
[Linux][Steam Deck] Can't enter credentials

### ISSUE THREAD

**Issue by d4haxor** [goatcorp/FFXIVQuickLauncher#1045]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to FFXIV updating and plugins not working correctly.

### What did you do?

Using the version on discover store, clicking on either the username or password box immediately greys them out and prevents them from being further interacted with. If I mash the keyboard right as I click one of the boxes, 2 or 3 characters will go in before it becomes greyed out. 

### Platform

Linux (native)

**Comment by NotNite** [comment]
Enter your username/password in Gaming Mode. This is a Steam API limitation, sorry!
