### ISSUE TITLE
Launcher not launching game error

### ISSUE THREAD

**Issue by mortiaqt** [goatcorp/FFXIVQuickLauncher#1050]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to FFXIV updating and plugins not working correctly.

### What did you do?

When launching XIVLauncher, an error box would pop up stating 
"Failed to inject the XIVLauncher in-game addon. Please try restarting your game and your PC. If this keeps happening please report this error."
![image](https://user-images.githubusercontent.com/108592608/177015144-e724d29e-0d9c-47f1-93c9-aa22ca565fa6.png)

If I kept attempting to re-launch, the game would eventually open throug the launcher in addition to the error popping up. I have restarted my PC several times throughout this and the game launches fine through the official launcher. Redownloading XIVLauncher did not fix this either.

### Platform

Windows

**Comment by NotNite** [comment]
Hey! Do you use an antivirus? If so, have you [whitelisted XIVLauncher & Dalamud](https://goatcorp.github.io/faq/xl_troubleshooting#q-how-do-i-whitelist-xivlauncher-and-dalamud-so-my-antivirus-leaves-them-alone)?

**Comment by mortiaqt** [comment]
Hey, I just have the default windows defender, I added it to the whitelist per the faq and it seems to launch every time now, sometimes with the error sometimes without (game always launches though which is new). So it seems to have helped but not entirely negated the issue
