### ISSUE TITLE
[Linux][Steam Deck] Unable to launch XIVlauncher through Game Mode

### ISSUE THREAD

**Issue by biolyeon** [goatcorp/FFXIVQuickLauncher#1051]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to FFXIV updating and plugins not working correctly.

### What did you do?

I am a non-steam client player who was able to use the launcher when it first dropped on Flatpak. On current release, with the inability to type in credentials in desktop mode, I have tried opening the launcher through Steam in desktop mode, as well as through game mode. Neither option opens the launcher, resulting in just going back to the steam menu. I have also tried this with and without the launch command used for XIVlauncher in the instructions. Any idea as to whether this requires a fresh install of the launcher, or if this is something being worked on.

As a note, when the launcher first came out on flatpak, opening the launcher shortcut in game mode only had the launcher open, and the game was black screened, so I previously played by running the launcher through steam desktop mode for controller inputs. 

For this issue, is there anything I need to log that can help with this as well?

### Platform

Linux (native)

**Comment by NotNite** [comment]
Hi! My first guess is that you forgot to set some arguments in Steam, or set it to run with Proton. Check our [Steam Deck install guide](https://goatcorp.github.io/faq/steamdeck) for instructions.

**Comment by biolyeon** [comment]
Wow, it was very minor but it was the compatibility mode. I think previously I had it on proton experimental a month ago, but I just removed compatibility mode and it's running now.

**Comment by NotNite** [comment]
Nice! Glad it's working for you.
