### ISSUE TITLE
Key in dictionary Path to PATH

### ISSUE THREAD

**Issue by thollis9** [goatcorp/FFXIVQuickLauncher#1071]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

standard installation with auto login and Gshade optimization

### Platform

Windows

**Comment by goaaats** [comment]
Need more info

**Comment by thollis9** [comment]
issue resolved, simply needed to reboot program for it to path properly apologies for the erroneous report.
