### ISSUE TITLE
abort() has been called on latest version

### ISSUE THREAD

**Issue by sgilissen** [goatcorp/FFXIVQuickLauncher#1073]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

This is a minor issue, but I thought I'd mention it. 
Everything runs fine, only if I close the game, I get the error message that abort() has been called. 
Possible a debug version flag that's still enabled in the latest releases? This is just a wild guess though.
![Screenshot_20220717_034439](https://user-images.githubusercontent.com/187589/179380776-50acf307-9f8d-4d7b-bdc5-4bb5d1d1e911.png)
![dalamuderror](https://user-images.githubusercontent.com/187589/179381167-e0abad3a-b772-42d5-af22-d387e1570778.png)

This happens on both Fedora 35 and on a different system in a new install with Debian Buster, which is completely clean and has no addons whatsoever installed.
The Fedora machine is using Lutris, the Debian machine is using the standalone version of XIVLauncher (the one which, I think, is optimized for Steam Deck)

### Platform

Linux (native)

### Wine/Proton runner version

lutris-ge-6.16-1-x86_64 (Fedora) and wine-7.12 (Debian)

### Relevant log output

```shell
Log files do not seem to be updated. I checked <appdata>/Roaming/XIVLauncher and <appdata>/Local/XIVLauncher

Perhaps I'm looking in the wrong directory?
I'd be happy to add logs if I am, and they are needed.
```

**Comment by reiichi001** [comment]
This is a known issue, but we're not sure why it happens. It is harmless and you can just dismiss it with the "abort" button.
