### ISSUE TITLE
Debug error when you close

### ISSUE THREAD

**Issue by coreybruce** [goatcorp/FFXIVQuickLauncher#1077]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

When I close the game I get a debug error, the game works fine but this error will come up every time I quit the game

![image](https://user-images.githubusercontent.com/8393780/180615696-50bce4a6-86a7-477a-8f18-9dd8835aa6ef.png)

### Platform

Linux (native)

### Wine/Proton runner version

Proton Experimental

**Comment by NotNite** [comment]
Will be fixed soon - see https://github.com/goatcorp/Dalamud/pull/925.
