### ISSUE TITLE
[Steam Deck] Unable to launch game through XIVlauncher

### ISSUE THREAD

**Issue by biolyeon** [goatcorp/FFXIVQuickLauncher#1103]
Hi,

I have been able to run the game previously, but I haven't tried launching it since Steam OS 3.3 dropped. I am currently unable to launch the game, with the error "XIVLauncher was not able to check the boot version for the select installation...".

When I first installed the game, it was the day the flatpak launcher came out, and the game was installed from desktop mode (it does still launch the free trial version in game mode). Is this an issue where I need to delete the game from my Steam Deck and download the free trial version manually from game mode?

If this is a known issue, let me know as well.

**Comment by NotNite** [comment]
This sounds like likely an issue with your internet. Could you send `~/.xlcore/logs/launcher.log` (or, if you're not comfortable with sharing it, the exception at the end of it)?

**Comment by biolyeon** [comment]
[launcher.log](https://github.com/goatcorp/FFXIVQuickLauncher/files/9333548/launcher.log)

I attached the launcher logs. To note, on my browser on my steam deck, I can't even access Github from there (google, youtube, and facebook opened just fine). It might be a network issue on my steam deck but this was occurring both over wifi and wired. Everything network-wise is fine on my PC.

**Comment by NotNite** [comment]
This is definitely a network error, yeah. See [this](https://goatcorp.github.io/faq/xl_troubleshooting#q-the-official-launcher-isnt-working--xivlauncher-failed-to-check-for-updates--patch-files-could-not-be-verified) FAQ entry - does any of these help? They might be hard to pull off, because, y'know, Steam Deck.

**Comment by biolyeon** [comment]
Looks like this is fixed now. I changed DNS settings and rebooted my deck and modem. Whether this was due to steam OS 3.3 I'm not too sure about, but this current OS has been a performance/functionality hit overall.
