### ISSUE TITLE
Game stays as a zombie process after exiting

### ISSUE THREAD

**Issue by Daktyl198** [goatcorp/FFXIVQuickLauncher#1107]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Everything works fine, but when I exit the game the window closes but it leaves a zombie process behind. It uses resources, and even thought it doesn't have a window it can be streamed on Discord and it shows a black screen with a FF14 exit message in the middle.

### Platform

Windows

**Comment by NotNite** [comment]
Do you use Logitech GHub?

**Comment by Daktyl198** [comment]
I do, is that related?

**Comment by NotNite** [comment]
Yes. That is the issue. Please reopen if you're still having problems.
