### ISSUE TITLE
Version %1 Not Compatible With Version of Windows

### ISSUE THREAD

**Issue by penumbrabard** [goatcorp/FFXIVQuickLauncher#1110]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

I was simply attempting to log in from my laptop, and it never had any issues before. 

### Platform

Windows

### Relevant log output

```shell
System.ComponentModel.Win32Exception (0x80004005): This version of %1 is not compatible with the version of Windows you're running. Check your computer's system information and then contact the software publisher
   at XIVLauncher.Common.Game.NativeAclFix.LaunchGame(String workingDir, String exePath, String arguments, IDictionary`2 envVars, DpiAwareness dpiAwareness, Action`1 beforeResume) in C:\goatsoft\xl\XIVLauncher.Common.Windows\NativeAclFix.cs:line 448
   at XIVLauncher.Common.Game.Launcher.LaunchGame(IGameRunner runner, String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments, DpiAwareness dpiAwareness) in C:\goatsoft\xl\XIVLauncher.Common\Game\Launcher.cs:line 268
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<StartGameAndAddon>d__29.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<TryProcessLoginResult>d__24.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 616

Version: 6.2.44.0
Git Hash: 6.2.44-0-g9f0b8dd
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: F:\SquareEnix\FINAL FANTASY XIV - A Realm Reborn
```

**Comment by NotNite** [comment]
Does this consistently happen? Can you attach `%AppData%/XIVLauncher/output.log`?

**Comment by penumbrabard** [comment]
I have tried running an integrity check, which says everything is fine, did a repair through xivlauncher, restarted it and then also the laptop too. It keeps showing up despite having worked yesterday.
[output.log](https://github.com/goatcorp/FFXIVQuickLauncher/files/9409480/output.log)

**Comment by NotNite** [comment]
What version of Windows do you use?

**Comment by NotNite** [comment]
Your troubleshooting blob indicates `Microsoft Windows NT 6.2.9200.0` - is XIVLauncher/FFXIV set to run in compatibility mode (right click exe -> Properties)? This is the version for Windows 8, IIRC.

**Comment by penumbrabard** [comment]
Doesn't appear to be.
![image_2022-08-23_130012981](https://user-images.githubusercontent.com/6371055/186231184-c2046d69-0872-40fe-8415-fb2c9abb5694.png)

**Comment by reiichi001** [comment]
This is gonna sound weird, but could you take a screenshot of your C:\ (or wherever to boot Windows from) drive?

**Comment by penumbrabard** [comment]
> This is gonna sound weird, but could you take a screenshot of your C:\ (or wherever to boot Windows from) drive?

I have FFXIV on an external drive that is connected to the laptop, if that makes any difference.

**Comment by reiichi001** [comment]
> > This is gonna sound weird, but could you take a screenshot of your C:\ (or wherever to boot Windows from) drive?
> 
> I have FFXIV on an external drive that is connected to the laptop, if that makes any difference.

For the potential cause I'm thinking of, that doesn't matter. It's based on boot drive. (Because it's related to a file existing somewhere it's not supposed to).

And do you use a third party antivirus?

**Comment by penumbrabard** [comment]
> For the potential cause I'm thinking of, that doesn't matter. It's based on boot drive. (Because it's related to a file existing somewhere it's not supposed to).
Attached.
![image_2022-08-23_130734750](https://user-images.githubusercontent.com/6371055/186232400-b8240dc0-99d8-44a5-a8af-f58061cfff55.png)

> And do you use a third party antivirus?
I do not.

**Comment by penumbrabard** [comment]
![image_2022-08-23_131737748](https://user-images.githubusercontent.com/6371055/186234065-abf41976-b559-464a-97a3-de3b61bcf929.png)

This also appears, if it's relevant.

**Comment by reiichi001** [comment]
OK, the C:\ screenshot looks ok. On the same drive as your FFXIV install, do you have a file/folder named just "program" on it?

Like:
`C:\Program`
`D:\Program`
`E:\Program`
`F:\Program`
etc

**Comment by penumbrabard** [comment]
> OK, the C:\ screenshot looks ok. On the same drive as your FFXIV install, do you have a file/folder named just "program" on it?
> 
> Like: `C:\Program` `D:\Program` `E:\Program` `F:\Program` etc

No, I do not.

**Comment by reiichi001** [comment]
Can you also let us know which version of Windows you're running (version / build number / arm64/x86/x64)

And if you open XIVLauncher and go into its settings, can you run an integrity check and see if that finishes? If it says the game install appears to be valid, then we don't need to worry about your ffxiv install. If it says anything else, please upload the integrityreport.txt file from `%appdata%\xivlauncher` please.

**Comment by reiichi001** [comment]
ok. Well that's definitely not a good integrity check. Let me recheck what we have filed and then grab some followup files. Because it the integrity check is accurate, your game install is very corrupted.

**Comment by penumbrabard** [comment]
Weird, cause it was woring earlier this morning. I wonder what happened. o.o

**Comment by reiichi001** [comment]
OK, so integrity for the current client version is correct. Can I have you upload a few files from your game install to check over?

```
\game\ffxivgame.bck
\game\ffxivgame.ver
\game\sqpack\ex1\ex1.bck
\game\sqpack\ex1\ex1.ver
\game\sqpack\ex2\ex2.bck
\game\sqpack\ex2\ex2.ver
\game\sqpack\ex3\ex3.bck
\game\sqpack\ex3\ex3.ver
\game\sqpack\ex4\ex4.bck
\game\sqpack\ex4\ex4.ver
```

These are used during the integrity check process, and before we continue, I want to validate them by hand.

**Comment by penumbrabard** [comment]
I am in the goat discord if that will make any of this easier. Pen#1510
Compiling those files now, regardless.

**Comment by reiichi001** [comment]
Right now, we have our troubleshooting channels closed until Dalamud is back up, so this is the best place for launcher issues!

**Comment by penumbrabard** [comment]
[FFXIV Troubleshooting.zip](https://github.com/goatcorp/FFXIVQuickLauncher/files/9409960/FFXIV.Troubleshooting.zip)

**Comment by reiichi001** [comment]
Excellent. Your version files all match what they should be. On XIVLauncher's main window, please right-click the login button and select "repair" to initiate a client file repair. XIVLauncher will need to download some patch files if you don't normally save them.

It will also reset the game install to stock, removing any textools mods, reshade/gshade injectors, etc. (All the non-standard files will be placed into a repair_recycler folder, but I'd recommend re-running the reshade/gshade installers if you use one of those.)

**Comment by penumbrabard** [comment]
It works! Thank you so much! <3
