### ISSUE TITLE
Ignore SupportedGameVer

### ISSUE THREAD

**Issue by ChaosInfinited** [goatcorp/FFXIVQuickLauncher#1115]
### Update disclaimer

- [X] Yes, I have checked and my request is not related to the game updating and plugins not working correctly.

### What happened, what did not, what did you want to happen?

Hiho! o/
I was thinking - checking your code I've noticed you check whether or not to enable Dalamud with a json from your repo - would it be plausible for you to add [DEV ONLY] ignore gameversion check in the launcher? (disabled by default ofc) - will try to give you a PR unless Dalamud will really be completely broken even with smallest of patches.

My reasoning: sometimes patches are extremely small, sometimes you need more time to make sure things work just right - most plugins would still work I think, and I think that patching through discrepancy is easier - you could get more logs about `what broke what` to trace it back and patch it more easily, while having less requests `when will it be working again?` and guesses.

But maybe I'm wrong and it's not worth it - please let me know - if you find such option/setting useful (be it for you, devs, or us, players) - I'll provide a PR for it

### Version

Both

### Platform

Applies to all

**Comment by ritmototal** [comment]
A setting would be fine to to ignore version or not via checkbox so that we can at least run it while waiting for updates when dealing with a small patch.

This would also be useful for some add-ons assuming there could be a safe mode or a way to disable them outside the game.

**Comment by ChaosInfinited** [comment]
Right.. plugins are checked against game version too..
Dalamud already comes with safe mode fortunately - if something crashes it will ask you if you want to run with plugins disabled next time

**Comment by lmcintyre** [comment]
>most plugins would still work I think
You think? In the kindest way; you're wrong. Even hotfixes can break plugins. 5.58 hotfix 1 broke a signature Orchestrion was using.
This is a great idea until they change the way some server interaction behaves internally and now a plugin is doing something easily detectable at best or sending invalid data that could crash the server at worst. We prevent Dalamud from loading specifically to avoid any possibility of this, so nobody has ever had to question this kind of thing.

**Comment by ChaosInfinited** [comment]
Thank you for clarifying!

Now I see it's a very bad idea.. sorry about it.
Cheers!
