### ISSUE TITLE
XIVLauncher incompatible with textools

### ISSUE THREAD

**Issue by Endbringer7** [goatcorp/FFXIVQuickLauncher#1116]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

I downloaded textools for some minor (map and UI) mods. For some reason, when I start the game via XIVLauncher, those mods don't show, and only the ones in the plugins do (chat bubbles, for example). Is this proper or is something going wrong?

### Platform

Windows

**Comment by NotNite** [comment]
You have two game installs, and XIVLauncher is pointed to the wrong one.

**Comment by lmcintyre** [comment]
You installed the game twice. Please make sure that XIVLauncher is running the same copy of the game as the official launcher and that you are installing your mods on.

**Comment by Endbringer7** [comment]
It was pointing to steam and not the client. I had a feeling this was it but never got around to checking it out. Thank you.
