### ISSUE TITLE
[Linux] Steam says FFXIV is still running after I close it.

### ISSUE THREAD

**Issue by LordBrainless** [goatcorp/FFXIVQuickLauncher#1139]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

After closing the game, my Steam says that the FFXIV game is still running (launcher closes as usual), 
although the window is already closed. I only have the problem since I use the XIVLauncher.

Version: XIVLauncher 1.0.1.0 (6246fde)

### Platform

Linux (native)

### Wine/Proton runner version

FFXIV: Proton GE 7-30, Launcher: none (installed with flatpak and added it in Steam)

**Comment by tommadness** [comment]
The Flatpak version requires a few extra launch arguments to allow the Launcher to fully talk to steam.

Add `--parent-expose-pids --parent-share-pids --parent-pid=1` to the launch args section of however you run the launcher (Non-Steam Game entry, .Desktop, etc)

**Comment by coreybruce** [comment]
Issue is back, game stays open even with the launch option after you close the launcher
