### ISSUE TITLE
Request for Build guide of flatpack version of FFXIVQuickLauncher

### ISSUE THREAD

**Issue by Elegantwolf** [goatcorp/FFXIVQuickLauncher#1148]
### Update disclaimer

- [X] Yes, I have checked and my request is not related to the game updating and plugins not working correctly.

### What happened, what did not, what did you want to happen?

FFXIVQuickLauncher have support linux and flatpack, that is awesome. However, CN server still need wine to install. Current version of FFXIVQuickLauncher CN(6.2.44) runs great on wine 5.0, but can't install on wine 7.0+ or any version of proton. It says please re-run with normal user, which is an old question. CN developers won't help solving this problem. Thus I'm trying to build a linux version myself.

Could you please provide build guide on linux, or ways to solve errors like "re-run with normal user"?

Thanks a lot.

### Version

Standard version (Windows, Lutris)

### Platform

Linux (Wine/Proton)

**Comment by NotNite** [comment]
The flatpak uses a custom launcher made specifically for Linux. We aren't affiliated with the CN devs, so you'd need to get them to modify XIVLauncher.Core to support the Chinese client. We don't really support running XIVLauncher's Windows version through Wine/Lutris anymore.

Depending on their fork, it might Just Work™, you'll need to go to their codebase and check. The login process is completely different in China, and we don't know what they've changed in XIVLauncher.Common to support the Chinese client.

**Comment by Elegantwolf** [comment]
> 

That's what I'm looking for. How come I totally missed it. Thank you, I will have a try!
