### ISSUE TITLE
No service account or subscription

### ISSUE THREAD

**Issue by p0lq** [goatcorp/FFXIVQuickLauncher#1162]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Hello,
I installed XIVLauncher from flathub and added it to my steam as a non-steam game. After that I pasted these commands to FFXIV launcher options: XL_SECRET_PROVIDER=FILE %command% run --parent-expose-pids --parent-share-pids --parent-pid=1 --branch=stable --arch=x86_64 --command=xivlauncher dev.goats.xivlauncher

I launched XIVLauncher and it started fine, but I am getting and error that says: No service account or subscription
I have checked and confirmed that my username and password is correct and that I have an active subsription on my account. I tried reinstalling XIVLauncher once more, but I am still getting the same error message.
![2022-09-24_23-06](https://user-images.githubusercontent.com/94566300/192117461-069f02d1-0d41-4dec-a492-a0481cf39389.png)
![2022-09-24_23-05](https://user-images.githubusercontent.com/94566300/192117462-fe7fa3e8-5cec-416d-af25-0f0debfe0adc.png)

### Platform

Linux (native)

### Wine/Proton runner version

GE-Proton7-30

**Comment by NotNite** [comment]
Did you check the box to enable Steam integration?

**Comment by p0lq** [comment]
Do you mean that "Use steam service" box below username and password fields? Yes, but it requires reinstalling the whole game.

**Comment by NotNite** [comment]
Do you use an OTP? Is that checked, too?

**Comment by p0lq** [comment]
No I don't use an OTP. I use only my account name and password

**Comment by p0lq** [comment]
![2022-09-24_23-27_1](https://user-images.githubusercontent.com/94566300/192117747-4b6c8fcc-9e21-4059-8577-5f72c4bcfebd.png)
here's my system info, if you need it.

**Comment by NotNite** [comment]
Can you please upload `~/.xlcore/logs/launcher.log`?

**Comment by p0lq** [comment]
sure, just a moment

**Comment by p0lq** [comment]
[launcher.log](https://github.com/goatcorp/FFXIVQuickLauncher/files/9639535/launcher.log)

**Comment by NotNite** [comment]
The only times I'm seeing this error in your log is when you had the Steam service account checkbox unchecked. It still happens with it checked?

**Comment by p0lq** [comment]
nope, but it gives me this window

![2022-09-24_23-36](https://user-images.githubusercontent.com/94566300/192117986-58a0c353-73bb-4678-a6a8-90dd5dbbb17f.png)

**Comment by p0lq** [comment]
when it is checked. When I uncheck it, then the account error pops up.

**Comment by NotNite** [comment]
That's a different error. You should have mentioned that.

Verify there's enough space on the drive you set XIVLauncher to install to.

**Comment by p0lq** [comment]
But I just wonder why it would require me to patch this for 81gb when my game is already installed and so is XIVLauncher? It doesn't make sense in my eyes

**Comment by NotNite** [comment]
You probably haven't told XIVLauncher correctly where your game is. You need to point it to the folders containing `game` and `boot`.

**Comment by p0lq** [comment]
Well, thanks anyways for your quick reaction and trying to help out. I'll clear out some room for that patch and try again after that.

**Comment by p0lq** [comment]
Oh I see, I'll check those aswell right now.

**Comment by tommadness** [comment]
In addition to pointing XIVLauncher to the correct folder, you'll need to use Flatseal to give XIVLauncher permission to read/write to those folders.

**Comment by p0lq** [comment]
Okay, I'll install that aswell and check that the folders are correct in the game path and config path.

**Comment by p0lq** [comment]
Thank you so much, it started patching now after correcting file paths and allowing the file permissions.

![2022-09-24_23-53](https://user-images.githubusercontent.com/94566300/192118458-498a3bab-96b4-4fc4-a969-28e2342f1319.png)
