### ISSUE TITLE
Compiling from tarball fails with fatal: not a git repository (or any of the parent directories): .git

### ISSUE THREAD

**Issue by a-crate** [goatcorp/FFXIVQuickLauncher#1179]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Trying to compile the native linux version from the published tarball on github fails to with the message `fatal: not a git repository (or any of the parent directories): .git`
It seems to be a failure of src/XIVLauncher.Core/XIVLauncher.Core.csproj line 115. Can this information be embedded at release time and the version hash creation skipped if the file is non-empty? On Linux this would be a pretty simple `test -n $(cat VerFile) || git [...]`, I'm not sure what a cross-platform solution would look like.

### Platform

Linux (native)

### Relevant log output

```shell
amy@waifu ~/g/x/F/s/XIVLauncher.Core [1]> dotnet publish -r linux-x64 --sc -o ~/git/xl/build --configuration Release -p:DefineConstants=WINE_XIV_GENTOO_LINUX
MSBuild version 17.3.1+2badb37d1 for .NET
  Determining projects to restore...
  All projects are up-to-date for restore.
  XIVLauncher.VersionGenerator -> /home/amy/git/xl/FFXIVQuickLauncher-6.2.44/src/XIVLauncher.VersionGenerator/bin/Release/netstandard2.0/XIVLauncher.VersionGenerator.dll
  XIVLauncher.Common -> /home/amy/git/xl/FFXIVQuickLauncher-6.2.44/src/XIVLauncher.Common/bin/Release/net6.0/XIVLauncher.Common.dll
  XIVLauncher.Common.Unix -> /home/amy/git/xl/FFXIVQuickLauncher-6.2.44/src/XIVLauncher.Common.Unix/bin/Release/net6.0/XIVLauncher.Common.Unix.dll
  XIVLauncher.Common.Windows -> /home/amy/git/xl/FFXIVQuickLauncher-6.2.44/src/XIVLauncher.Common.Windows/bin/Release/net6.0/XIVLauncher.Common.Windows.dll
  fatal: not a git repository (or any of the parent directories): .git
/home/amy/git/xl/FFXIVQuickLauncher-6.2.44/src/XIVLauncher.Core/XIVLauncher.Core.csproj(115,5): error MSB3073: The command "git -C "/home/amy/git/xl/FFXIVQuickLauncher-6.2.44/src/XIVLauncher.Core/" describe --long --always --dirty > obj/Release/net6.0/linux-x64/gitver" exited with code 128.
amy@waifu ~/g/x/F/s/XIVLauncher.Core [1]>
```

**Comment by reiichi001** [comment]
There are some fields that are looking for a git hash, as those are put in the titlebar and debug info.

When compiling from a tarball, the git repo bits aren't there and you'll need to provide that on command line args with `-p:BuildHash=SomeHashHere`

Here's what I'm doing for the MPR PKGBUILD (AUR pulls from git, but the MPR wasn't doing that properly).
<https://mpr.makedeb.org/pkgbase/xivlauncher/git/tree/PKGBUILD>

**Comment by a-crate** [comment]
That works, thank you.
