### ISSUE TITLE
Unable to use Support Desk

### ISSUE THREAD

**Issue by ChaosInfinited** [goatcorp/FFXIVQuickLauncher#1186]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Since... can't remember what version, I'm unable to use support desk in 14 - maybe it was made like that on purpose, maybe it's normal - was able to use it just fine prior to swtich to `new` launcher...
AccessViolationException
Dalamud.Game.Framework::HandleFrameworkUpadate
On every try to contact their devs - maybe that's on purpose... maybe I'm the dumb trying to report real bots. Would be nice to know though.

### Platform

Linux (Wine/Proton)

### Wine/Proton runner version

wine-xiv-staging-fsync-git-7.10.r3.g560db77d

**Comment by ChaosInfinited** [comment]
Support Desk still will crash the game, it was working just fine prior (about a month), no plugins enabled, still the same error.

**Comment by NotNite** [comment]
Likely not a bug with the launcher itself - should be filed in Dalamud instead.

**Comment by ChaosInfinited** [comment]
> Likely not a bug with the launcher itself - should be filed in Dalamud instead.

What do you mean? Can I provide you some logs to help out?

**Comment by NotNite** [comment]
This is not a bug in the launcher (you filed this issue on the launcher repository). You can either file it on the Dalamud repository or [join our Discord for better help](https://goat.place/).

**Comment by ChaosInfinited** [comment]
Ah! Ok! Will do that, thanks and sorry!
