### ISSUE TITLE
Add time and date stamps to the Changelog

### ISSUE THREAD

**Issue by chernobog** [goatcorp/FFXIVQuickLauncher#1195]
### Update disclaimer

- [X] Yes, I have checked and my request is not related to the game updating and plugins not working correctly.

### What happened, what did not, what did you want to happen?

Please add the time and/or date of releases in the Changelog section of the Plugin Installer.

### Version

Standard version (Windows, Lutris)

### Platform

Windows

**Comment by reiichi001** [comment]
Plugin installer feature requests/improvements should go to https://github.com/goatcorp/Dalamud/issues as they're not part of the launcher, they're part of Dalamud.
