### ISSUE TITLE
Option to ignore steam entirely on Linux

### ISSUE THREAD

**Issue by CodeAndGin** [goatcorp/FFXIVQuickLauncher#1213]
### Update disclaimer

- [x] Yes, I have checked and my request is not related to the game updating and plugins not working correctly.

### What happened, what did not, what did you want to happen?

At the minute xlcore communicates with steam and tells steam that you are playing "Final Fantasy XIV Online Free Trial" whenever it's running. 

An option to completely disable this functionality would be nice. I'm not running the steam version, nor am I on a steamdeck, so I don't need steam to know about XIV and I don't need XIV to know about steam. 

(To be honest, this is partially fuelled by the annoying behaviour of steam not knowing when the game is closed if you forget to include the `--parent-expose-pids --parent-share-pids --parent-pid=1` args in your .Desktop file or however you're launching xlcore)

### Version

Native/Core version (Linux)

### Platform

Linux (native)

**Comment by reiichi001** [comment]
Hey there! XLCore is handled in a separate repo these days (although it still pulls XIVLauncher.Common from here)

Could you please migrate this issue over to https://github.com/goatcorp/XIVLauncher.Core/issues instead?

**Comment by CodeAndGin** [comment]
Oh, my bad, will do!
