### ISSUE TITLE
Font becomes blocky shortly after launch

### ISSUE THREAD

**Issue by aquova** [goatcorp/FFXIVQuickLauncher#1221]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

When the launcher first starts up, everything looks and acts correctly. Shortly after launch, Steam will always pop up a Steam community notification, which seems to cause the text to become blocky and unreadable. All functionality seems to remain, it's just difficult to read anything. I'm not sure when this started happening, but within the last month or two. Once the game starts, everything works as normal.

![xivlauncher](https://user-images.githubusercontent.com/24580844/211177077-5c1899b5-bfe5-45f7-b168-3812fbc96722.png)

System details:
OS: Arch Linux
CPU: Ryzen 5 5600X
GPU: Radeon 6650 XT
DE: KDE Plasma Wayland
Install method: Tried both the AUR xivlauncher and xivlauncher-git packages, both display the same issue.

### Platform

Linux (native)

### Wine/Proton runner version

Proton Experimental

**Comment by tommadness** [comment]
XLCore has a separate project, linked here:
https://github.com/goatcorp/XIVLauncher.Core

Please move the issue over to that repo for better tracking.

**Comment by aquova** [comment]
Will do, thanks
