### ISSUE TITLE
Need help with unique XIVLauncher + Steam issue

### ISSUE THREAD

**Issue by CreativeJojo** [goatcorp/FFXIVQuickLauncher#1236]
Hello, 

I am new to XIV Launcher, but I'm having trouble launching it with Steam.

For context, I do not have the steam version of FFXIV, I use the PC version; however, I added FFXIV and always launch it through my steam library in order to use the steam controller configurations when I play. I enabled "Use Steam Service account" and "Start Steam when Starting XIVLauncher," but apart from enabling that and Direct X 11, there are no other setting changes made to the XIVLauncher. When I try to launch the game the error message "Could not authenticate with steam" appears (see image).

Do you have any suggestions as to how I can fix this? I read through the FAQ but could not find anything specific to my issue. Perhaps I should launch it without steam? I fear I may lose the ability to use steam configs. Thanks in advance for all the help!

![Screenshot 2023-01-13 154400](https://user-images.githubusercontent.com/14060433/212416456-2abd13ee-b813-422a-b8fc-f5c498b57990.png)

**Comment by Maxunit** [comment]
If you do not own a Steam version of it, then using the "Use Steam Service account" option is not needed, since it otherwise will try to log in into FFXIV with your Steam Account, which has no FFXIV copy registered.

There are 2 types of FFXIV Accounts on PC:

Square Enix Account
Steam Account

**Comment by CreativeJojo** [comment]
I see, thank you! That fixed it. I was able to add XIVLauncher as a Steam game and launch it from there, which then launched FFXIV normally.
