### ISSUE TITLE
XIVAlex and ReShade

### ISSUE THREAD

**Issue by wolfjake-uoft** [goatcorp/FFXIVQuickLauncher#1269]
![image](https://user-images.githubusercontent.com/78000577/217364119-70373ebe-e795-4f7a-83e0-b8a59e8455ef.png)

This error pops up after I uninstalled Gshade and moved to reshade. I'm not sure if this is a quick launcher problem, but I do remember getting a pop up in quicklauncher last time I had to update gshade asking if I wanted quicklauncher to make it compatible with alex or something along those lines. I can press ignore and everything works fine, but its kind of annoying when launching the game. It's looking for the gshade dll that I deleted in the xivalex.chaindll folder that I also deleted.

**Comment by NotNite** [comment]
It is definitely not an issue with XIVLauncher.
