### ISSUE TITLE
Wine do not see some directories 

### ISSUE THREAD

**Issue by Charlignon** [goatcorp/FFXIVQuickLauncher#1371]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

_On XIVLauncher 1.0.4.0 installed via Flatpack
Running native Wine version (not Steam)_

## Description of the issue

I'm trying to add additional drives to the wine config so the game can access it. More precisely, it is a partition mounted on `/media/charles/mydrivename`
However, some directories in my system are not visible by the wine managed by xivlauncher.

Below : from xivlauncher > Settings > Wine > Open Wine configuration > Drives > Browse
<details><summary>Screenshot 1</summary>

![image](https://github.com/goatcorp/FFXIVQuickLauncher/assets/41714460/72221f44-69d5-4289-b8cf-d68dd8209e7a)

</details>

Below : `winecfg` started directly from command line in shell. 
You can see that there is a lot more folder. This is what is expected 
<details><summary>Screenshot 2</summary>

![image](https://github.com/goatcorp/FFXIVQuickLauncher/assets/41714460/4688a115-bfb2-4d48-ac31-a03d363f4bfa) 
![image](https://github.com/goatcorp/FFXIVQuickLauncher/assets/41714460/7b089de3-dfcb-4188-9c1e-2aec1a96133b)

</details>

Another difference is that Wine version is not displayed in the xivlauncher managed version. 
Below : side by side comparison of the About tab (left: wine on shell / right: wivlauncher wine)
<details><summary>Screenshot 3</summary>

![image](https://github.com/goatcorp/FFXIVQuickLauncher/assets/41714460/21ed3949-dc22-42ca-a7cb-fcf962a610f0)

</details>

## What I have already tried (and other comments)
- creating symlink directly in `wineprefix/dosdevices` with `ln -s /my/path <...>/wineprefix/dosdevices`. Wine will just create a drive that points to nothing
- I looked extensively in the issues in this repo
- I did not try to use a custom wine version instead of the one managed by xivlauncher
- [I am aware](https://www.reddit.com/r/winehq/comments/t5z3ca/comment/hzbnhv8/) that I could mount my drive in my `$HOME`, but I would do that only as a last resort

This may be some sort of permission issue ? Or just an issue with linux filesystem, symlink and hidden folders are not shown in the interface either.

Thanks in advance for your help !

### Platform

Linux (Wine/Proton)

### Wine/Proton runner version

8.0 (running wine --version in shell)

**Comment by reiichi001** [comment]
I think you meant to post this in https://github.com/goatcorp/XIVLauncher.Core as this is the repository for the **Windows** launcher program (and common elements) and has nothing to do with Wine or Wine Prefix management.

If you're using the Flatpak, this sandboxing is by design. Our default settings only allow read/write access to the user's home folder. You can use a tool like Flatseal to grant access to other directories or to all system directories/devices as desired.

**Comment by Charlignon** [comment]
Sorry, I mixed up the repos ! Thank you for your answer :)

**Comment by Charlignon** [comment]
For the record if anyone find this : using flatseal to grant more permission fixed the issue !
