### ISSUE TITLE
[Linux/Steamdeck] Dalamud not compatible with ReShade 5.9.2

### ISSUE THREAD

**Issue by cimba007** [goatcorp/FFXIVQuickLauncher#1374]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

XIVLauncher Core v1.0.4.0 from XIVLauncher Flathub 1.0.4
ReShade 5.9.2

ReShade and Dalamud both get loaded correctly. ReShade is configured to "NoReloadInit=1".
ReShade does not load any shader in this configuration. As soon as you enter ReShade via "Home" Button and press "Reload" FF14 crashes. With NoReloadInit=0 this happens right at the start of the game. With no Shaders installed no crash occurs.

If Dalamud is disabled ReShade is working correctly and is able to compile the shaders.
I was not able to find anything relevant in the ReShade logfiles but can provide anything that is needed for further investigation.

Best regards

### Platform

Linux (native)

**Comment by reiichi001** [comment]
Please open Linux-related issues for XIVLauncher.Core/the flatpak on https://github.com/goatcorp/XIVLauncher.Core

Reshade will crash the game when Dalamud injects if it's busy compiling shaders

What you generally want to do is:

1. Disable Dalamud
2. Install Reshade 
3. Launch the game.
4. Configure Reshade 
5. Put Reshade into Performance Mode
6. Relaunch again to verify shader compilation is complete
7. Enable Dalamud.

Alternatively, set an injection delay for Dalamud that's 10-15 seconds, based on how long it takes your computer to compile shaders on game launch.

**Comment by cimba007** [comment]
This is actually the solution. Adding a injection delay solves the issue.
