### ISSUE TITLE
A way to install the update on Steam Deck

### ISSUE THREAD

**Issue by Keldium** [goatcorp/FFXIVQuickLauncher#1390]
### Update disclaimer

- [X] Yes, I have checked and my request is not related to the game updating and plugins not working correctly.

### What happened, what did not, what did you want to happen?

Hi ! I want to install the update to my steam deck but can't do it because of wine. Could you put the update in the discover app ? The setup.exe won't work and I don't know how to use the rest of the package. 

### Version

Native/Core version (Linux)

### Platform

Linux (native)

**Comment by nhongooi** [comment]
it's the first one, https://github.com/goatcorp/FFXIVQuickLauncher/issues/1393, i saw and it has more watchers more.  the patch is out if youre wiling to makepkg it

**Comment by Keldium** [comment]
Can you tell me how I can do it ? I tried to extract it and then to launch the only launchable app and I've got it :
![IMG_20231003_162414](https://github.com/goatcorp/FFXIVQuickLauncher/assets/123789778/416829f4-499d-46f3-bea2-2e0eb4409052)

**Comment by reiichi001** [comment]
Please wait for the xivlauncher.core 1.0.5 update. It includes a fix for applying patch files.
