### ISSUE TITLE
Patch Error on Steam Deck

### ISSUE THREAD

**Issue by Jkyrie22** [goatcorp/FFXIVQuickLauncher#1393]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

I am using the 1.0.4.0 flatpak (XIVLauncher installed from the Steam Deck's Discover store). I can no longer patch the game successfully. Below are the steps I took: 

1. I am on Game Mode on Steam Deck
2. I run XIVLauncher from my Library
3. I auto-log in and the patch attempts to run 
4. During the patching, an error occurs: The patch installer ran into an error. Please report this error. Please try again or use the official launcher. 

I have a video but the file is too large (19.8MB) so I uploaded it to Streamable, the link provided below is good for 2 days. I can upload a new link if needed once it expires. 

https://streamable.com/cq7w3v

### Platform

Linux (native)

### Wine/Proton runner version

When I go to the Wine tab in XIVLauncher Settings, Wine Version is: "Managed by XIVLauncher"

### Relevant log output

```shell
The patch installer ran into an error. Please report this error. Please try again or use the official launcher.
```

**Comment by evangeltepes** [comment]
Mine's doing the same. I like your post better, I'm going to close my post.

**Comment by Borril** [comment]
Same issue here, hopefully a patch will come sooner rather than later

**Comment by nhongooi** [comment]
patch is out https://github.com/goatcorp/XIVLauncher.Core/releases/tag/1.0.5

**Comment by evangeltepes** [comment]
How does one install the patch?

**Comment by Jkyrie22** [comment]
I'd like to know how to manually update to the 1.0.5 patch too, the Discover store doesn't recognize that there's an update for XIVLauncher yet.

**Comment by reiichi001** [comment]
If you're using the flatpak, please wait for it to make it onto flathub. 

Copying a slightly adjusted post from our support discord. 

I want to be super clear as a project administrator about something. 

__**please for love of all that is good do not go around trying to patchwork files into the flatpak. Seriously.**__

I've seen that mentioned in the discord server chat and on github and I'm absolutely horrified. 

For the experimental or the impatient, use a community build or manually build the project. But please under no circumstances mess with system or package-manager installed files like that. You can and will break things and when it later fails to update, we won't be able to help you. Do not make a mess that cannot be cleaned up.

**Comment by NotNite** [comment]
Closing in favor of https://github.com/goatcorp/XIVLauncher.Core/issues/78.
