### ISSUE TITLE
Please push todays fix to Flathub version of XIVLauncher

### ISSUE THREAD

**Issue by posrgl** [goatcorp/FFXIVQuickLauncher#1395]
Hi, not sure if this is the right place to post, however I noticed the fix was already out for Windows and such.  I use XIVLauncher as a flatpak and it doesn't seem like the fix has been pushed out to it on there specifically https://flathub.org/apps/dev.goats.xivlauncher .

I understand if this isnt considered urgent, but thank you all the same.

**Comment by NotNite** [comment]
https://github.com/goatcorp/XIVLauncher.Core/issues/78
