### ISSUE TITLE
dalamud dont work

### ISSUE THREAD

**Issue by Yamiama** [goatcorp/FFXIVQuickLauncher#1403]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

hi, is it me or dalamud still dont work ?
i have the 6.3.10 update. did i have something specificaly to manipulate cause it perfectly worked for the last 2 years and now it seems to work perfectly fine for everyone but me ?

### Platform

Windows

**Comment by Zyian** [comment]
Dalamud has not yet been released for Patch 6.5, please wait a little longer for the other developers to finish it
