### ISSUE TITLE
ex0:D2023.09.23.0000.0001.patch not found in _patchSources

### ISSUE THREAD

**Issue by tengatwist** [goatcorp/FFXIVQuickLauncher#1415]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Updated game, was kicked due to connection loss, opened XIV Launcher and selected "Repair Game" 

And that's when the error presented itself.

### Platform

Windows

### Relevant log output

```shell
System.InvalidOperationException: Key "ex0:D2023.09.23.0000.0001.patch" not found in _patchSources
   at XIVLauncher.Common.Game.Patch.PatchVerifier.<RunVerifier>d__83.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchVerifier.cs:line 418

Version: 6.3.10.0
Git Hash: 6.3.10-0-ge8e22c3
Context: PatchVerifier
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn
```

**Comment by reiichi001** [comment]
Repair indexes are not pushed for 6.51 yet. Only the reference for 6.5 is there, and SE has changed the patchlist and it's no longer valid.
