### ISSUE TITLE
Cannot update or add new external Plugins

### ISSUE THREAD

**Issue by darkrapsody** [goatcorp/FFXIVQuickLauncher#1429]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

I already repaired the launcher, thinking it might be a file issue. Still, I cant add external plugins. Would appreciate some help. None of the FAQ questions or anything asked here before covers my issue. Playing on Windows 10.
(It basically reads: Failed to download: Brio)
![downloadfail](https://github.com/goatcorp/FFXIVQuickLauncher/assets/87188212/e9728dc2-82b8-4c3e-98a2-ae3bcc2babfa)

### Platform

Windows

**Comment by goaaats** [comment]
We can't help with this. It's your internet, PC or setup.
