### ISSUE TITLE
FFXIV running in steam after closing

### ISSUE THREAD

**Issue by Denisgsv** [goatcorp/FFXIVQuickLauncher#1442]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Basically i have ffxiv installed exclusively through ffxiv launcher, steam doesn't have any version installed.  

Yet when i start it and the worst when i close it, its still stuck in steam as "running", any way to fix that ?

### Platform

Linux (native)

### Wine/Proton runner version

mint 21

### Relevant log output

```shell
no error messages
```

**Comment by thembees** [comment]
in the launcher, under Settings > Game, do you have "Ignore Steam" checked?...

**Comment by Denisgsv** [comment]
I tried that, steam still saw the game running .

I wanted to use the launcher independently from steam - didnt work, in the end to solve the issue of ffxiv always "running" i did the opposite added it to steam the launcher,  so it can properly communicate when it open and when it closes.

Still odd that the game was installed separately from steam not related at all, why steam keeps seeing it :| 

for can be closed i suppose as my main problem it being stuck is in a way solved
