### ISSUE TITLE
.exe flagged as malware by malwarebytes AI

### ISSUE THREAD

**Issue by NyxIgnyte** [goatcorp/FFXIVQuickLauncher#1457]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Woke up, malwarebytes quarantined 3 files relating to xivlauncher, including install files and setup.exe

### Platform

Windows

**Comment by tommadness** [comment]
Dupe of #1455 , happens every single time we update XL. MalwareBytes AI flagging is trash and incredibly prone to false positives
