### ISSUE TITLE
Updated with FFXIV Patch now launcher won't open

### ISSUE THREAD

**Issue by thebluecaboose** [goatcorp/FFXIVQuickLauncher#1458]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Hi! I updated as usual with the laucnher yesterday along with the other updates pushed out through the day. I was playing on quick launcher fine last night around 8pm EST.
Shut PC down. This morning Quick Launcher will not open at all even when ran as admin. Restarted PC and doesn't change anything.

### Platform

Windows

**Comment by tommadness** [comment]
Never run XIVLauncher as admin. FFXIV does not handle it gracefully and you will break your configs.

If you use an aftermarket antivirus, that is the cause.

**Comment by thebluecaboose** [comment]
i tried adding it to the ignore list on Malwarebytes and its still not launching even with Malwarebytes turned off or removed.

**Comment by thebluecaboose** [comment]
solved. was malwarebytes
had to go in restore files and restart pc with adding exception
