### ISSUE TITLE
Launcher is swallowing up system resources

### ISSUE THREAD

**Issue by PVRAMID** [goatcorp/FFXIVQuickLauncher#1474]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

1. Fresh install of the game
2. 98GB worth of downloads to complete ( Patching through 208 updates).
3. Download speed tolerable at 60-80MB/s.
4. C Drive Usage at 100% (Installing files to D Drive)
5. Launcher is being run from AppData (C Drive)

https://i.pvramid.gg/Q1dDxzR2SM-EDrfMexc5v.png

### Platform

Windows

**Comment by NotNite** [comment]
XIVLauncher by default downloads patches to a folder in AppData (and deletes them after application). Try moving the patch directory (Settings > Patching); let us know if that improves disk usage.

There is a download speed limit, but I wonder if a patch application limit would be good too (kizer code 2fast). I notice that repairs especially eat disk usage.

**Comment by PVRAMID** [comment]
> XIVLauncher by default downloads patches to a folder in AppData (and deletes them after application). Try moving the patch directory (Settings > Patching); let us know if that improves disk usage.
> 
> There is a download speed limit, but I wonder if a patch application limit would be good too (kizer code 2fast). I notice that repairs especially eat disk usage.

This fixed the issue immediately. Yeah - before this fix, it brought my PC to an absolute halt. Which is impressive considering I'm running 3 x 1TB M.2 Drives, A 13900k with an RTX 4090.

I'd suggest some change be implemented to prevent it crushing peoples harddrives. Thank you for the prompt response.
