### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by Melyia0373** [goatcorp/FFXIVQuickLauncher#1475]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

I was trying to fix the game files and it gave an error and told me to send this.

### Platform

Windows

**Comment by reiichi001** [comment]
I've updated integiry and repair indexes for the current client version, 2024.03.27.0000.0000.

Please retry @Melyia0373
