### ISSUE TITLE
Profiles

### ISSUE THREAD

**Issue by Schwegg** [goatcorp/FFXIVQuickLauncher#1478]
### Update disclaimer

- [X] Yes, I have checked and my request is not related to the game updating and plugins not working correctly.

### What happened, what did not, what did you want to happen?

ability to add/manage profiles which saves login info for those who have multiple accounts

### Version

Standard version (Windows, Lutris)

### Platform

Applies to all

**Comment by tommadness** [comment]
This exists already. Click the People icon below the username/password fields.
