### ISSUE TITLE
Could not find the drive <path to what is not a drive>

### ISSUE THREAD

**Issue by y0shir** [goatcorp/FFXIVQuickLauncher#1486]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

FFXIV takes up quite a lot of space, so I transferred already downloaded .xlcore directory to other drive that has more space and replaced paths that have` /home/username/.xlcore` with` /mnt/files/xlcore`
Now launcher could not find drive `/mnt/files/xlcore/ffxiv`, despite it obviously not being a drive.

### Platform

Linux (native)

### Wine/Proton runner version

Managed by XIVLauncher

### Relevant log output

```shell
An error occured (HandlePatchAsync)

System.IO.DriveNotFoundException: Could not find the drive '/mnt/files/xlcore/ffxiv'. The drive might not be ready or might not be mapped.
 at System.IO.DriveInfo
CheckStatfsResultAndThrowInfNecessary(Int32 result)
 at System.IO.DriveInfo.get_AvailableFreeSpace()
 at XIVLauncher.Common.Util.PlatformHelpers.
GetDiskFreeSpace(DrectoryInfo info) in C:/goatsoft/xl/XIVLauncher.
Common/Game/Patch/PatchManager.cs:line 125
at XIVLauncher.Core.Components.MainPage.MainPage.TryHandlePAtchAsynch(Repository repository, PatchListEntry[] pendingPatches, String sid) in 
C:/goatsoft/xl/XIVLauncher.
Core/Components/MainPage/MainPage.cs:line 1042
```

**Comment by tommadness** [comment]
Flatpak? If so you need to use something like Flatseal to allow read/write access to any non-default paths

**Comment by NotNite** [comment]
This issue is on the wrong repository: https://github.com/goatcorp/XIVLauncher.Core
