### ISSUE TITLE
Time stamp

### ISSUE THREAD

**Issue by ElinaMidnight** [goatcorp/FFXIVQuickLauncher#1492]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

I can no longer start FF14 via Dalamund Launcher because I have an error.

{"resources":{"core":{"limit":60,"remaining":60,"reset":1715107964,"used":0,"resource":"core"},"graphql":{"limit":0,"remaining":0,"reset":1715107964,"used":0,"resource":"graphql"},"integration_manifest":{"limit":5000,"remaining":5000,"reset":1715107964,"used":0,"resource":"integration_manifest"},"search":{"limit":10,"remaining":10,"reset":1715104424,"used":0,"resource":"search"}},"rate":{"limit":60,"remaining":60,"reset":1715107964,"used":0,"resource":"core"}}

### Platform

Windows

### Wine/Proton runner version

Windows 11

### Relevant log output

```shell
{"resources":{"core":{"limit":60,"remaining":60,"reset":1715107964,"used":0,"resource":"core"},"graphql":{"limit":0,"remaining":0,"reset":1715107964,"used":0,"resource":"graphql"},"integration_manifest":{"limit":5000,"remaining":5000,"reset":1715107964,"used":0,"resource":"integration_manifest"},"search":{"limit":10,"remaining":10,"reset":1715104424,"used":0,"resource":"search"}},"rate":{"limit":60,"remaining":60,"reset":1715107964,"used":0,"resource":"core"}}
```

**Comment by reiichi001** [comment]
You need to actually provide the error and a launcher log. GitHub rate limit output doesn't give us anything to work with.

**Comment by ElinaMidnight** [comment]
![Screenshot 2024-05-07 201635](https://github.com/goatcorp/FFXIVQuickLauncher/assets/169189879/bc773354-4503-4a9f-966e-aff8d36cc63e)

System.ComponentModel.Win32Exception (0x80004005): Das System kann die angegebene Datei nicht finden
   bei System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   bei System.Diagnostics.Process.Start(ProcessStartInfo startInfo)
   bei XIVLauncher.Windows.SettingsControl.BackupToolButton_OnClick(Object sender, RoutedEventArgs e) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\SettingsControl.xaml.cs:Zeile 151.
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   bei System.Windows.Controls.Primitives.ButtonBase.OnClick()
   bei System.Windows.Controls.Button.OnClick()
   bei System.Windows.Controls.Primitives.ButtonBase.OnMouseLeftButtonUp(MouseButtonEventArgs e)
   bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.ReRaiseEventAs(DependencyObject sender, RoutedEventArgs args, RoutedEvent newEvent)
   bei System.Windows.UIElement.OnMouseUpThunk(Object sender, MouseButtonEventArgs e)
   bei System.Windows.RoutedEventArgs.InvokeHandler(Delegate handler, Object target)
   bei System.Windows.RoutedEventHandlerInfo.InvokeHandler(Object target, RoutedEventArgs routedEventArgs)
   bei System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   bei System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   bei System.Windows.UIElement.RaiseTrustedEvent(RoutedEventArgs args)
   bei System.Windows.Input.InputManager.ProcessStagingArea()
   bei System.Windows.Input.InputManager.ProcessInput(InputEventArgs input)
   bei System.Windows.Input.InputProviderSite.ReportInput(InputReport inputReport)
   bei System.Windows.Interop.HwndMouseInputProvider.ReportInput(IntPtr hwnd, InputMode mode, Int32 timestamp, RawMouseActions actions, Int32 x, Int32 y, Int32 wheel)
   bei System.Windows.Interop.HwndMouseInputProvider.FilterMessage(IntPtr hwnd, WindowMessage msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei System.Windows.Interop.HwndSource.InputFilterMessage(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   bei MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   bei System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   bei System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   bei System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   bei MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   bei MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   bei System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   bei System.Windows.Application.RunDispatcher(Object ignore)
   bei System.Windows.Application.RunInternal(Window window)
   bei XIVLauncher.App.Main()

Version: 6.3.16.0
Git Hash: 6.3.16-0-g020dde9
Context: Unhandled
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
Addons Enabled? True
Auto Login Enabled? False
Language: German
LauncherLanguage: English
Game path: C:\Games\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

**Comment by reiichi001** [comment]
Please also attach your output.log log file from `%appdata%\XIVLauncher\`, so we can look into this further.

Most likely, you're being affected by a connection issue to CloudFlare, which is in front our proxy server that handles XIVLauncher's version check and asset downloads. A VPN may help.

**Comment by ElinaMidnight** [comment]
[output.log](https://github.com/goatcorp/FFXIVQuickLauncher/files/15239568/output.log)
