### ISSUE TITLE
More DXVK HUD options

### ISSUE THREAD

**Issue by EGBland** [goatcorp/FFXIVQuickLauncher#1506]
### Update disclaimer

- [X] Yes, I have checked and my request is not related to the game updating and plugins not working correctly.

### What happened, what did not, what did you want to happen?

Currently within Settings -> Wine is a DXVK Overlay combo box that lets me select if I want nothing, just FPS, or full diagnostics on the DXVK HUD.

However, DXVK supports several more options than are available in XL (there is a list [here](https://github.com/doitsujin/dxvk?tab=readme-ov-file#hud)). I want FPS and frame time on my HUD, but XL doesn't seem to currently provide an in-launcher way to set precisely which HUD elements I want.

I would like the ability to select individual components for my DXVK HUD within the launcher, or at least more options in the combo box.

### Version

Native/Core version (Linux)

### Platform

Linux (native)

**Comment by NotNite** [comment]
This repository is for the Windows launcher and core library. Please report this on the cross-platform repository instead: <https://github.com/goatcorp/XIVLauncher.Core>
