### ISSUE TITLE
The ability to change the location of where settings are stored on your hard drive.

### ISSUE THREAD

**Issue by WilliamW1979** [goatcorp/FFXIVQuickLauncher#1511]
### Update disclaimer

- [X] Yes, I have checked and my request is not related to the game updating and plugins not working correctly.

### What happened, what did not, what did you want to happen?

I know you put them  in the appdata but some of us use multiple drives and I would like the option to move the settings to a different location so that if I reinstall my operating system, I don't lose all my settings.

### Version

Standard version (Windows, Lutris)

### Platform

Applies to all

**Comment by reiichi001** [comment]
You can do this by using the `--roamingPath` launcher argument to set a custom location instead of appdata\roaming\xivlauncher.
