### ISSUE TITLE
ACT needs to launch before the game

### ISSUE THREAD

**Issue by CrackersLad** [goatcorp/FFXIVQuickLauncher#1515]
### Update disclaimer

- [X] Yes, I have checked and my request is not related to the game updating and plugins not working correctly.

### What happened, what did not, what did you want to happen?

ACT now needs to be running before the game is opened to be able to function. Unfortunately the auto launch functionality in the quick launcher launches it after the game so renders it useless.

### Version

Standard version (Windows, Lutris)

### Platform

Windows

**Comment by Buckfutt** [comment]
Here's a band-aid fix:
https://github.com/Buckfutt/XIVLauncherLauncher

**Comment by lmcintyre** [comment]
ACT does not need to be launched before the game. ACT needs to be launched *before logging into the world*. You can open it as late as the queue in the lobby and be fine. You can also swap to Deucalion injection mode and not have to do that at all.

**Comment by reiichi001** [comment]
[lmcintyre](https://github.com/lmcintyre) beat me to making the same post. I went to check on the FFXIV ACT Discord and their documentation states the same.
