### ISSUE TITLE
Setup always thinks ACT is installed, even if it isn't

### ISSUE THREAD

**Issue by SlyAceZeta** [goatcorp/FFXIVQuickLauncher#1516]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

When installing XIVLauncher 6.3.16 using Setup.exe on Windows 11, the setup process always shows this message:

![image](https://github.com/goatcorp/FFXIVQuickLauncher/assets/11371137/9df5d039-a5bf-49c9-920c-f3f25d8a06bd)

On two separate computers where I newly installed XIVLauncher, neither computer had Advanced Combat Tracker installed, so this message should not have appeared.

### Platform

Windows

**Comment by reiichi001** [comment]
This has been fixed as of XIVLauncher 6.4.0.
