### ISSUE TITLE
When starting xivlauncher.core before steam it closes with an unhandled exception

### ISSUE THREAD

**Issue by nairol203** [goatcorp/FFXIVQuickLauncher#1517]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

When starting xivlauncher.core before steam it closes with an unhandled exception when clicking the "Login" button even if steam is fully running.

Steps to reproduce:
1. Start xivlauncher
2. Start steam
3. Login into ffxiv

Workaround:
Start steam before starting xivlauncher

### Platform

Linux (native)

### Relevant log output

```shell
Unhandled exception. System.NullReferenceException: Object reference not set to an instance of an object.
   at Steamworks.SteamUtils.get_DoesOverlayNeedPresent()
   at XIVLauncher.Common.Unix.UnixSteam.get_BOverlayNeedsPresent() in C:/goatsoft/xl/XIVLauncher.Common.Unix/UnixSteam.cs:line 31
   at XIVLauncher.Core.Program.Main(String[] args) in C:/goatsoft/xl/XIVLauncher.Core/Program.cs:line 308
```

**Comment by reiichi001** [comment]
Please direct any XIVLauncher.Core issues over to https://github.com/goatcorp/XIVLauncher.Core instead.
