### ISSUE TITLE
Unable to repair game after PC crashed during 7.0 update

### ISSUE THREAD

**Issue by TheVekter** [goatcorp/FFXIVQuickLauncher#1523]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

I was in the process of downloading the new update when my PC crashed mid-update. I restarted XIVLauncher and got the following error:

![image](https://github.com/goatcorp/FFXIVQuickLauncher/assets/7019927/72dec8cd-67fa-46a5-aa54-212cab23b949)

Upon trying to repair the game, I get this error:

![image](https://github.com/goatcorp/FFXIVQuickLauncher/assets/7019927/fb4fc38e-3a61-45a8-b4bd-7e5278f4b1e2)

I have tried deleting the patch and patchmeta folders in Documents in the hopes it would get the launcher to just redownload and reapply the patch but that didn't work. Is there a way to tell the launcher to download and apply the patch again without me having to completely reinstall the game at this point?

### Platform

Windows

**Comment by TheVekter** [comment]
Replacing `ffxivgame.ver` with `ffxivgame.bak` seems to have let me download the patch again, but I have no idea if this is actually going to reapply it properly or if my files are just screwed and I'll have to reinstall. I'll update this again once things go live to let folks know.

**Comment by reiichi001** [comment]
As of XIVLauncher 6.4.1, repair indexes have been updated. You'll need to ensure you have that release (or later) to use the repair function. Otherwise, you may need to reinstall the game using the official launcher.

If you want to check your installation before making any changes, you can run an integrity check from inside of XIVLauncher's settings to verify if it matches a stock install of the game.

**Comment by TheVekter** [comment]
> As of XIVLauncher 6.4.1, repair indexes have been updated. You'll need to ensure you have that release (or later) to use the repair function. Otherwise, you may need to reinstall the game using the official launcher.
> 
> If you want to check your installation before making any changes, you can run an integrity check from inside of XIVLauncher's settings to verify if it matches a stock install of the game.

I ran the integrity check and it came back fine, so I reckon we're good. If somehow it doesn't work tomorrow, I'll just run the repair.
