### ISSUE TITLE
System.InvalidOperationException while repairing game files

### ISSUE THREAD

**Issue by 8bllgrl** [goatcorp/FFXIVQuickLauncher#1544]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Forgot to Start Over Textools.
Did a Start Over after patching to 7.0, realized my mistake, tried to repair the game with XIVLauncher. 

( I noticed the file path says goatsoft. Is this intended? ) 

### Platform

Windows

### Relevant log output

```shell
System.InvalidOperationException: Key "ex0:H2017.06.06.0000.0001a.patch" not found in _patchSources
   at XIVLauncher.Common.Game.Patch.PatchVerifier.<RunVerifier>d__83.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchVerifier.cs:line 424

Version: 6.4.0.0
Git Hash: 6.4.0-0-gf7e3cea
Context: PatchVerifier
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn
```

**Comment by tommadness** [comment]
Yes, that's a path from the compiling environment. It's how compiled .NET programs report errors.

Repair indexes have not been updated for Dawntrail yet. This is expected.

**Comment by reiichi001** [comment]
As of XIVLauncher 6.4.1, this should be resolved. We needed to make some fixes to how repair works and then update/create the repair indexes needed.

Please let us know if repair does not work for you after updating XIVLauncher or close the issue if it does!

**Comment by 8bllgrl** [comment]
Closing issue as I was able to repair it with vanilla. Someone can reopen the issue if it occurs again
