### ISSUE TITLE
Dawntrail content not downloaded/installed on Linux

### ISSUE THREAD

**Issue by lilidredear** [goatcorp/FFXIVQuickLauncher#1555]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Running EndeavourOS (based on Arch) with KDE Plasma 6.1 on Wayland. Running with Steam services.

I updated the game beforehand. Got my ffxiv_boot.cfg file with the updated EULA from my W11 computer, copied it to the /.xlcore/ffxivConfig directory. Game launches and runs fine, but I can't accept the newest MSQ as it doesn't think I have the expansion/early access registered or downloaded (I checked MogStation and I do in fact have Early Access for Dawntrail).

### Platform

Linux (native)

### Wine/Proton runner version

Don't know how to verify, I'm using the launcher defaults.

**Comment by tommadness** [comment]
This is fixed in XIVLauncher version 1.0.0.9. Flathub is not currently updated to that version. I am unsure about the status of any of the community packages (AUR in your case).

**Comment by TannerStevens** [comment]
Having the same issue. Is there a way to manually update to 1.0.0.9?

**Comment by tommadness** [comment]
No. We have submitted the update to Flathub, please wait for them to distribute it.

**Comment by TannerStevens** [comment]
👍 Can you give any sort of ETA on FlatPak's turn around time? Mostly so I can determine whether or not to go back to sleep.

**Comment by FunFighter** [comment]
> 👍 Can you give any sort of ETA on FlatPak's turn around time? Mostly so I can determine whether or not to go back to sleep.

It just came online for me. `flatpak update` away
