### ISSUE TITLE
DLSS with XIVLauncher in Linux/Flatpak

### ISSUE THREAD

**Issue by Kitsune-Kuro** [goatcorp/FFXIVQuickLauncher#1559]
### Update disclaimer

- [X] Yes, I have checked and my request is not related to the game updating and plugins not working correctly.

### What happened, what did not, what did you want to happen?

Hello,

I have installed XIVLauncher on Ubuntu via Flatpak.
However, I cannot enable DLSS from Nvidia in the system settings.
When I start FFXIV on Steam without XIVLauncher, I can select it.
(By the way, the settings also work with the XIVLauncher on Windows. Therefore, I think it has something to do with the isolation feature of Flatpak, but I'm not sure what needs to be changed.)

DLSS is supported in FFXIV since dawntrail/v7.0.
I know it's early, but this feature is already supported by the XIVLauncher.

I have installed version 1.1.0 of dev.goats.xivlauncher.
Nvidia driver version: nvidia-driver-535

OS: Ubuntu 22.04.4 LTS x86_64
Kernel: 6.5.0-41-generic
Shell: bash 5.1.16
Resolution: 3840x2160
DE: GNOME 42.9
CPU: Intel i7-6700K (8) @ 4.200GHz
GPU: NVIDIA GeForce RTX 3070 Ti
Memory: 5377MiB / 23962MiB

Thank you for your assistance.

### Version

Native/Core version (Linux)

### Platform

Linux (Wine/Proton)

**Comment by oryschakj** [comment]
I'm also seeing a grayed out upscaling setting box when using the launcher. GPU is an Nvidia GTX 4080.

**Comment by marco-kretz** [comment]
Same problem for me. Tried setting PROTON_DISABLE_NVAPI=0 as well as PROTON_ENABLE_NVAPI=1, nothing helps. Boths DLSS and FSR are greyed out :(

Distro: Fedora 40 (GNOME 46.1, X11)
Graphics: NVIDIA RTX 4070Ti (550.90.07)
Default wine from Launcher is used (wine-xiv-staging-fsync-git-8.5.r4.g4211bac7)

**Comment by Jovicic** [comment]
Same problem.
Is this the cause of the issue? https://github.com/goatcorp/wine-xiv-git/blob/8bf9cd7adda9e6d00e23f8193a609b723c54e0a6/proton-tkg/proton_template/conf/user_settings.py#L33C1-L37C33

**Comment by reiichi001** [comment]
Please put xivlauncher.core issues in the correct repository. https://github.com/goatcorp/XIVLauncher.Core/issues
