### ISSUE TITLE
由於程式更新，暫時無法使用外掛Due to the program update, plug-ins are temporarily unavailable.

### ISSUE THREAD

**Issue by yuehxian** [goatcorp/FFXIVQuickLauncher#1581]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

As title

### Platform

Windows

**Comment by Sohtoren** [comment]
7.01 patch. As always, dalamud is disabled for a bit
