### ISSUE TITLE
discord unban

### ISSUE THREAD

**Issue by Skadus82** [goatcorp/FFXIVQuickLauncher#1597]
### Update disclaimer

- [X] Yes, I have checked and my request is not related to the game updating and plugins not working correctly.

### What happened, what did not, what did you want to happen?

Hi Guys,
my discord account got hacked back in June 23, so i was banned from your Discord server.
perfectly fine, i would have done the same. 
i found no other way to contact you for an unban to rejoin the discord community.
thx Skadus

### Version

Standard version (Windows, Lutris)

### Platform

Windows

**Comment by goaaats** [comment]
Should be good now.
