### ISSUE TITLE
Game repair gets a error

### ISSUE THREAD

**Issue by RedactedFFXIV** [goatcorp/FFXIVQuickLauncher#1606]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

1. Updated the Game
2. PC crashed
3. XIVLauncher didnt want to update anymore
4. Tried the Repair Feature
5. Got the error

### Platform

Windows

### Relevant log output

```shell
System.InvalidOperationException: Key "ex0:D2024.07.09.0000.0000.patch" not found in _patchSources
   bei XIVLauncher.Common.Game.Patch.PatchVerifier.<RunVerifier>d__83.MoveNext() in C:\goatsoft\xl\XIVLauncher.Common\Game\Patch\PatchVerifier.cs:Zeile 424.

Version: 6.4.1.0
Git Hash: 6.4.1-0-g21a73f3c
Context: PatchVerifier
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: F:\FFXIV
```

**Comment by reiichi001** [comment]
Any time there is a new game patch download, we will have to update XIVLauncher's repair indexes to match. I try to get this out same-day usually. These are now present.
