### ISSUE TITLE
System.IO.DriveNotFoundException when trying to launch from another drive

### ISSUE THREAD

**Issue by Bamowen** [goatcorp/FFXIVQuickLauncher#1616]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

I installed and ran xivlauncher from flatpak, changed the Game Configuration Path in settings to my folder containing game and boot; which for me is "/media/bamowen/BIG CHUNGUS/SquareEnix/FINAL FANTASY XIV - A Realm Reborn" as my OS SSD has no space for FFXIV and I already play on Windows (dual boot). I left the Game Configuration path to "/home/bamowen/.xlcore/ffxivConfig". I have mounted the drive before launcher xivLauncher

When I click login with my credentials, I have a popup that says 
`"System.IO.DriveNotFoundException: Could not find the drive '/media/bamowen/BIG CHUNGUS/SquareEnix/FINAL FANTASY XIV - A Realm Reborn'. The drive might not be ready or be mapped`

I did not install wine, nor am I launching from steam. I just followed the [installation steps](https://goatcorp.github.io/faq/steamdeck) specifically "Install XIVLauncher as a Flatpak from the terminal"

Attached are pics of the popup as I can't copy paste, and "generate tspack" only gives me a json (also attached)
[trouble.json](https://github.com/user-attachments/files/17072581/trouble.json)

![Screenshot from 2024-09-20 10-53-05](https://github.com/user-attachments/assets/acf30c64-dd70-4080-a6bd-ff6d043b80d9)
![Screenshot from 2024-09-20 10-53-34](https://github.com/user-attachments/assets/4e163aa1-88d9-4595-85ad-fa7ed103e5bc)
![Screenshot from 2024-09-20 10-53-45](https://github.com/user-attachments/assets/a70ec5ee-a457-4ff1-a463-7b1e20135811)

Here's a neofetch aswell:
![Screenshot from 2024-09-20 10-56-32](https://github.com/user-attachments/assets/a63bb18f-ead2-4bb5-8907-facc86c65728)

### Platform

Linux (native)

**Comment by tommadness** [comment]
Since you’re installing to a non-standard location, you need to grant XIVLauncher read/write permissions to that folder using Flatseal.

**Comment by Bamowen** [comment]
Thanks for the fast answer, I forgot to mention I did this. Didn't touch anything but Filesystem category. Here it is 
![Screenshot from 2024-09-20 12-59-30](https://github.com/user-attachments/assets/a52aba6d-483e-424f-bf61-e596cc39a9a0)

**Comment by tommadness** [comment]
The ~ at the beginning of your Flatseal entry means it’s relative to your user’s home directory: /home/USERNAME/media/bamowen/ […]

The path you put into XIVLauncher is an absolute directory: /media/bamowen/ […]

These are not the same path.

**Comment by Bamowen** [comment]
Quite new to all this, I didn't even realise. I works now, thank you very much :)
