### ISSUE TITLE
Launcher shows server error on first login.

### ISSUE THREAD

**Issue by Nin9sKi** [goatcorp/FFXIVQuickLauncher#1637]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Launcher shows an error on login "could nto establish a connection", however, I noticed that this error goes away on the second login attempt.

Meaning:
I log in > error
I login again > no error and loads fine
I close the login, attempt to login again > error
I login again > no error and loads fine

I have done the above process about 5 times to make sure it's consistent, and it is.

![205806](https://github.com/user-attachments/assets/870146d7-522b-4ca9-854c-0bff8e621774)

### Platform

Windows

**Comment by reiichi001** [comment]
Can you please upload your launcher log from `%appdata%\xivlauncher` please? It will be be named `output.log` (or labeled as a text document if you have known file extensions hidden)

Typically, this error is related to your network connect / internet / a VPN service you may be using.

**Comment by Nin9sKi** [comment]
Apologies, I missed that part. 
I do not use a VPN I believe, and this issue appeared only after the 7.1 update.

[output.log](https://github.com/user-attachments/files/17792193/output.log)

**Comment by reiichi001** [comment]
Looking at your log, here's the pertinent part of the error.
```
2024-11-17 21:42:25.147 +02:00 [ERR] StartGame failed... (LoginStatus=true)
System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: Unable to connect to the remote server ---> System.Net.Sockets.SocketException: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond 119.252.37.136:443
```

This means your computer isn't able to reach FFXIV's login server in Japan.

We do have some assorted networking troubleshooting steps you can try on our FAQ, https://goatcorp.github.io/faq/xl_troubleshooting#q-the-official-launcher-isnt-working--xivlauncher-failed-to-check-for-updates--patch-files-could-not-be-verified

The easiest is to just restart your computer. If that doesn't work, then your modem/router. This doesn't look like a DNS issue, so trying a  VPN would then be the last-resort option. (We link a couple free ones for testing)

**Comment by Nin9sKi** [comment]
Thank you. If it's just a "me" issue, I'll troubleshoot on my end.
Thanks again for the reply.
