### ISSUE TITLE
Steam Deck Black Screen after login but can here cinematic playing 

### ISSUE THREAD

**Issue by Frappple** [goatcorp/FFXIVQuickLauncher#1653]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to the game updating and plugins not working correctly.

### What did you do?

Tried the cutscenemovieopening = 1 in the cfg file 

Game works in desktop mode when I can use a keyboard to hit esc and get past it but gaming mode doesn't have an esc key 

### Platform

Linux (Wine/Proton)

**Comment by rankynbass** [comment]
Try going into the troubleshooting tab and enabling the "Hack: Disable gameoverlayrenderer.so"

**Comment by Frappple** [comment]
Perfect, thanks so much!
