### ISSUE TITLE
Encrypted Arguments failing under certain conditions

### ISSUE THREAD

**Issue by goaaats** [goatcorp/FFXIVQuickLauncher#205]
The encrypted arguments added in 4.8 sometimes cannot be decrypted by the client under certain conditions.
As a workaround, a checkbox to disable the behaviour was added.

**Comment by perize** [comment]
Apparently ffxiv has a broken Blowfish implementation (surpise surpise) which causes P and S-boxes to be generated incorrectly if the cipher key contains a negative number. (`byte >= 0x80`)

Needs to be investigated this is actually the case.

**Comment by goaaats** [comment]
This seems fine nowadays
