### ISSUE TITLE
Update plugins error

### ISSUE THREAD

**Issue by CalionSilus** [goatcorp/FFXIVQuickLauncher#219]
**Describe the bug here:**
Plugin update error when I click update plugins.

Here is attachment screenshot.

![image](https://user-images.githubusercontent.com/66424727/83896437-2324d600-a78f-11ea-9d24-739e141f3552.png)

**Steps to reproduce the bug:**

1. launch xiv launcher.
2. input /xlpulgins
3. click update plugins
4. error message appear
![xiv launcher error screen_20200606](https://user-images.githubusercontent.com/66424727/83896870-c544be00-a78f-11ea-9723-77008fd6a103.png)

```


**Expected behavior**
A clear and concise description of what you expected to happen.
Example: ``I expected the game to start when I put in the Konami code``


**Screenshots**
If applicable, add screenshots to help explain your problem.
Example:
![Super cool screenshot](https://i.imgur.com/y99ALui.png)


**Other information (*please* complete the following information):**
  Operating System: windows 10 pro
  XIVLauncher version: 4.9.2.0
  Launching as admin?: no
  Using Steam?: no
  Addons/Plugins enabled: refer screenshot

**Additional information**
Add any other context about the problem here.

**Comment by ccp6128** [comment]
Would like to confirmate the issue and request for any way to update the plugins before the game is launched, as it also happens quite often that some plugin update will crash the game immediately and I'll have to uninstall them all / restart the game / reinstall and redo the settings for those requiring custom settings.

**Comment by Aida-Enna** [comment]
This is likely fixed since the plugin code has been worked on since then - If not, feel free to reply here or open a new issue.
