### ISSUE TITLE
Crashing when loading into a new area

### ISSUE THREAD

**Issue by LunarGaze** [goatcorp/FFXIVQuickLauncher#221]
**Describe the bug here:**
Sometimes when I teleport to an aetheryte, enter an inn room, or even finish a dungeon, I will get a specific error and the game will crash to desktop.

**Steps to reproduce the bug:**
1. Load into a new area

**Expected behavior**
For the game not to crash when entering a new area.

**Screenshots**
![image](https://user-images.githubusercontent.com/20742787/84345191-b3419180-ab7a-11ea-8e8a-7c140c17a199.png)

**Other information (*please* complete the following information):**
  Operating System: W10
  XIVLauncher version: v4.9.2.0
  Launching as admin?: Tried it with both
  Using Steam?: No
  Addons/Plugins enabled: Tried it without Discord integration since someone in the Textools Discord suggested.

**Additional information**
It happens even if I disable all of my mods.

**Comment by Haplo064** [comment]
Hi Lunar,

Do you have _any_ other plugins loaded? There has been a case of XIVStats causing crashes on changing areas.

**Comment by LunarGaze** [comment]
I was using Character Data Sync, Discord Rich Presence, Marketboard, Orchestion, Title Edit, and XIV Combo. Have any of those been causing similar crashes?

**Comment by Poliwrath** [comment]
Could you post / screenshot the last few lines of your dalamud log file? (I think the stuff at the very bottom about a "exception" should be enough, the full file might have chat info and other stuff so be careful with that) ``%AppData%XIVLauncher\addon\Hooks\dalamud.txt``
Also, there's a discord server for XIVLauncher + Dalamud https://discord.gg/3NMcUV5

**Comment by LunarGaze** [comment]
Is it this part?

2020-06-11 01:58:57.191 -04:00 [FTL] Unhandled exception on AppDomain
System.NullReferenceException: Object reference not set to an instance of an object.
   at XIVStats.Plugin.<Loop>b__12_0(ClassInfo a)
   at System.Collections.Generic.List`1.FindIndex(Int32 startIndex, Int32 count, Predicate`1 match)
   at XIVStats.Plugin.Loop()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()

**Comment by LunarGaze** [comment]
I thought i had XIVstats disabled. Do I have to disable it in the launcher, not in game?

**Comment by Caraxi** [comment]
You have XIVStats installed. Delete the `XIVStats` folder from `%appdata%\XIVLauncher\installedPlugins`

**Comment by LunarGaze** [comment]
Alright, let me try that.

**Comment by LunarGaze** [comment]
I think that did it! I'm not getting anymore crashes.
