### ISSUE TITLE
Latest update to antivirus denies access to app

### ISSUE THREAD

**Issue by captice** [goatcorp/FFXIVQuickLauncher#222]
As the title says, the latest update of antivirus (using avast) had blocked quicklauncher.
Had to reinstall it with shields disabled and add the application folder and exe to the exceptions.

**Comment by captice** [comment]
My editing sucks. i wanted to update this but misclicked. 
after adding it to exceptions and reinstalling it again, it worked for a while till next update of the launcher started refusing permissions from the appdata folder. tried to force permissions and inherit it but still would refuse to open again.

**Comment by Aida-Enna** [comment]
Hey there! It's been a while since this was opened - Are you still having this issue? Try disabling your AV and see if that fixes it. If so, then that's an issue with avast and not us, sorry!
