### ISSUE TITLE
Downloading from scratch issues.

### ISSUE THREAD

**Issue by Kyuuso** [goatcorp/FFXIVQuickLauncher#228]
**Describe the bug here:**
``There are two errors I've found with patcher. First, you'll get error when trying to patch folders ex2 and ex3 since they aren't created on location game\sqpack.
The other ones is due to encoding on versioning files, both .ver and .bck. The files afected are ex1.ver, ex1.bck, ex2.ver, ex2.bck, ex3.ver, ex3.bck, ffxivgame.bck and ffxivgame.ver.
They're encoded on UTF-8 BOM, but the ones downloaded from Original patcher are encoded to ANSI.``

**Steps to reproduce the bug:**
```
1. Create empty folder
2. Download game with XIVLauncher on that folder
3. You will get the first error.

1. Create empty folder
2. Download game with XIVLauncher on that folder
3. You will get the first error.
3.1 You create the folders needed on game\sqpack.
4. Download will be completed but you won't be able to open the game due to a "version update required".
5. If you open the original patcher, you will see a "Unable to complete version check error".
```

**Expected behavior**
``Patcher works flawless as a goat.``

**Screenshots**
Example:
![Game not launching](https://i.imgur.com/v2pOsRC.png)
![Original patching error](https://i.imgur.com/ByU8C9p.png)

**Other information (*please* complete the following information):**
  Operating System: W10 Proffesional 64Bits
  XIVLauncher version: 5.0.0.0
  Launching as admin?: No
  Using Steam?: No
  Addons/Plugins enabled: Character Data Sync, Discord Rich Presence, Market board, Pixel Perfect, SlideCast.

**Additional information**
Creating ex2, ex3 folders, and changing encoding on .ver and .bck files worked perfectly.

**Comment by goaaats** [comment]
Are you sure about this?
I've asked multiple people to check, and they always have been encoded in UTF-8 without BOM.

**Comment by NotAdam** [comment]
this would be a system code page issue as File.WriteAllText uses that by default, you can use the overload to write with a specific encoding

**Comment by goaaats** [comment]
Oh thanks, I didn't know about that, hardcoded them to UTF8 now

**Comment by Kyuuso** [comment]
> Are you sure about this?
> I've asked multiple people to check, and they always have been encoded in UTF-8 without BOM.

I've checked with Beyond Compare, on the right side Original patcher, on the left side XIVLauncher
[Compare](https://i.imgur.com/U5u6Jre.png)

**Comment by Kyuuso** [comment]
About the error with ex2 and ex3 folders, here's the log.
![](https://i.imgur.com/LHiBj4U.png)

**Comment by Kyuuso** [comment]
Uh, so, forgot to close it, working fine <3
