### ISSUE TITLE
Option to bypass Squirrel in Linux environments

### ISSUE THREAD

**Issue by RodrigoLeiteF** [goatcorp/FFXIVQuickLauncher#231]
**What is your suggestion/feature request?**
Squirrel is problematic on Linux. The regular `Setup.exe` doesn't seem to always work, requiring users to extract it (and the resulting `.nupkg` file) to access the launcher. Obviously this disables automatic updates (which are a hard requirement for this project), which is worked around through [this script](https://gist.github.com/cking/8be0bf9a030940df3de7eeeab582180e#file-readme-md), generously provided by Kura#0010 on Discord. Unfortunately Squirrel seems to break on newer versions of XL, so the best solution would be to add an option to disable it, either through a command-line flag or separate Linux-targeted builds.

**Describe how you'd like this to work**
#### Command-line argument to skip Squirrel
This has the benefit of not having to mess with CI, but Windows users can use it to bypass updates and create problems in the long term.

#### Separate Linux build with Squirrel removed
Clearly marking it as a Linux build on releases reduce the chances of Windows users downloading it, but requires messing with CI and build directives.

Either option works.

**Comment by goaaats** [comment]
I implemented this with https://github.com/goatcorp/FFXIVQuickLauncher/commit/5b1b3eeaab8c9f104d4f7a8f11f2c30977519345. Setting the "XL_WINEONLINUX" environment variable to "True" will disable Squirrel. Please make sure your autoupdater scripts are working alright before publishing :p

If there's any other issue with Linux we can solve, just create another issue or reopen this one.
Thanks a lot!
