### ISSUE TITLE
Patch Installer doesn't like umlauts in path

### ISSUE THREAD

**Issue by cking** [goatcorp/FFXIVQuickLauncher#236]
**Describe the bug here:**
I installed XIV Launcher on my company laptop (relevant later, see log files).
Everything works like expected (no problems with Squirrel or XL itself).
XL launches the Patch Installer because there is no FFXIV installed.
Patch Installer starts and crashes with the following message box:
![grafik](https://user-images.githubusercontent.com/196108/87820427-58ccdc80-c86e-11ea-8363-d9a1126e5efb.png)
Here is the [patcher.log](https://hastebin.com/nelerucege.log) and the [output.log](https://hastebin.com/evagobilaf.log).

**Steps to reproduce the bug:**
1. Have a user account that uses umlauts in the file path
2. Install XL
3. Launch XL
4. Follow first start wizard
5. After wizard, Patcher is immediatly launched
6. Patcher crashes

**Expected behavior**
Patcher launches and successfully patches, or at least launch XL itself so i can change the patches directory.

**Screenshots**
See above

**Other information (*please* complete the following information):**
  Operating System: Windows 10 Pro 64 Bit (German)
  XIVLauncher version: 5.0.3 (Latest)
  Launching as admin?: No
  Using Steam?: Not applicable (but yes)
  Addons/Plugins enabled: Not applicable

**Additional information**
- Userfolder contains a German umlaut (`ö`)

**Comment by goaaats** [comment]
Fixed this
