### ISSUE TITLE
FFXIV Quick Launcher Not Working With Steam

### ISSUE THREAD

**Issue by GentlemanGamer94** [goatcorp/FFXIVQuickLauncher#237]
To be clear, I do not own the Steam version of the game: what I usually do is run the Quick Launcher through Steam so I can use my Nintendo Switch Pro Controller with the game. What's happening though is that if I run the Quick Launcher through Steam, I get a crash and FFXIV does not load.  This happens both when Steam Integration is checked and unchecked in the settings. And if I run it outside of Steam, everything works fine. 

Now I realize there are other ways to get my controller working with FFXIV other than Steam, which I'll probably end up doing if I don't end up finding a fix to this issue.  I'm just wondering why exactly I'm having problems with Steam all of a sudden.  

***

System.Exception: Game exited prematurely
   at XIVLauncher.Game.Launcher.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Launcher.cs:line 255
Version: 5.0.3.0
Git Hash: 8dd4055
Context: XG LaunchGame
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? False
Auto Login Enabled? True
Language: English
Game path: F:\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

Addons: []

**Comment by GentlemanGamer94** [comment]
I just updated my computer and apparently, that's all that was required to fix the Steam issue. I don't know exactly how and why, but I'm obviously not complaining.  :)

**Comment by RodrigoLeiteF** [comment]
I should point out that for people doing this using Lutris as a non-steam game, make sure Lutris is closed before you launch the game. That way you get proper controller and overlay support.
