### ISSUE TITLE
XIV Combo 1.0.3.3 (X)

### ISSUE THREAD

**Issue by BlackHole9** [goatcorp/FFXIVQuickLauncher#238]
Getting an error like this and the plugin is not found on the list:
`Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: ". Path 'RepoUrl', line 9, position 1.
   w Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments)
   w Newtonsoft.Json.JsonTextReader.Read()
   w Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)
   w Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
   w Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
   w Newtonsoft.Json.Linq.JObject.Parse(String json, JsonLoadSettings settings)
   w XIVLauncher.Windows.SettingsControl.TogglePlugin_OnClick(Object sender, RoutedEventArgs e) w D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\SettingsControl.xaml.cs:wiersz 410
   w System.Windows.EventRoute.InvokeHandlersImpl(Object source, RoutedEventArgs args, Boolean reRaised)
   w System.Windows.UIElement.RaiseEventImpl(DependencyObject sender, RoutedEventArgs args)
   w System.Windows.Controls.MenuItem.InvokeClickAfterRender(Object arg)
   w System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   w System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   w System.Windows.Threading.DispatcherOperation.InvokeImpl()
   w MS.Internal.CulturePreservingExecutionContext.CallbackWrapper(Object obj)
   w System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   w System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   w MS.Internal.CulturePreservingExecutionContext.Run(CulturePreservingExecutionContext executionContext, ContextCallback callback, Object state)
   w System.Windows.Threading.DispatcherOperation.Invoke()
   w System.Windows.Threading.Dispatcher.ProcessQueue()
   w System.Windows.Threading.Dispatcher.WndProcHook(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   w MS.Win32.HwndWrapper.WndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam, Boolean& handled)
   w MS.Win32.HwndSubclass.DispatcherCallbackOperation(Object o)
   w System.Windows.Threading.ExceptionWrapper.InternalRealCall(Delegate callback, Object args, Int32 numArgs)
   w System.Windows.Threading.ExceptionWrapper.TryCatchWhen(Object source, Delegate callback, Object args, Int32 numArgs, Delegate catchHandler)
   w System.Windows.Threading.Dispatcher.LegacyInvokeImpl(DispatcherPriority priority, TimeSpan timeout, Delegate method, Object args, Int32 numArgs)
   w MS.Win32.HwndSubclass.SubclassWndProc(IntPtr hwnd, Int32 msg, IntPtr wParam, IntPtr lParam)
   w MS.Win32.UnsafeNativeMethods.DispatchMessage(MSG& msg)
   w System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   w System.Windows.Application.RunDispatcher(Object ignore)
   w System.Windows.Application.RunInternal(Window window)
   w XIVLauncher.App.Main()
Version: 5.0.3.0
Git Hash: 8dd4055
Context: Unhandled
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
Game path: E:\Games\FF14\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

Addons: []
`

Current list of plugins in /xlplugins:
https://i.imgur.com/Vf5Y0w4.png

**Comment by BlackHole9** [comment]
Solved.
Deleted the .disable files in folder, all plugins back.
Issue remains at:Why did this happen in the first place ?

**Comment by reiichi001** [comment]
Dalamud was updated to 5.0 which was a major change.

Per #announcements channel in the XIVLauncher discord,
```
Due to some backend changes, after your next FFXIV restart, you will have to reinstall all XIVLauncher plugins via the /xlplugins command.
All of your settings will still be there.
We have a lot of new and interesting plugins though, so maybe this is a chance for you to check out some of the others!

If you encounter any issues, please make sure to hop into #xivlauncher_issues so we can help you out!
```

**Comment by BlackHole9** [comment]
Was this the reason the plugins got disabled, if so, there should be a heads up beforehand as there was no information about this earlier and I read all patch notes, perhaps in the future do take a moment to write it down.

**Comment by goaaats** [comment]
Thank you for your feedback, it has been directed to our development team which will consider it carefully. Our sales representatives may get back to you regarding your feedback to follow up on possible changes and improvements.
