### ISSUE TITLE
chat extender version 2.0.2.4

### ISSUE THREAD

**Issue by AmenneHolelane** [goatcorp/FFXIVQuickLauncher#240]
**Describe the bug here:**
chat extender font size doesn't stay between game launches. it saves it in the config window and hitting apply does make it change to what it should be but on initial launch it's like font size 15

**Steps to reproduce the bug:**
install chat extender, change font size to something besides default, kill game, relaunch, look at the font size, open chat extender config, hit apply on the font size button, kill game, relaunch, look at the font size, open chat extender config, hit apply on the font size button.

**Expected behavior**
the font size to stay static between game launches

**Comment by Caraxi** [comment]
Issues with individual plugins should really go onto their respective github

https://github.com/Haplo064/ffxiv-chat-extender
