### ISSUE TITLE
Environment variable to disable autologin

### ISSUE THREAD

**Issue by feffes** [goatcorp/FFXIVQuickLauncher#241]
**What is your suggestion/feature request?**
Allow for an environment variable to be set to ignore autologin

**Describe how you'd like this to work**
In the case of the environment variable being present/having a certain value(1, true, whatever), autologin will not be initiated and the launcher will open. I suggest to just use a pretty descriptive env variable name like `FFXIVQUICKLAUNCHER_AUTOLOGIN_DISABLE` or something along those lines perhaps.

**Additional context**
Polling the shift key can sometimes be unreliable on certain setups.

**Comment by goaaats** [comment]
Will have this in the next update.

**Comment by goaaats** [comment]
Done https://github.com/goatcorp/FFXIVQuickLauncher/commit/46aa922e171cb210977ce8b2931060d106022ece
