### ISSUE TITLE
"-1.8GB left to download"

### ISSUE THREAD

**Issue by PrincessRTFM** [goatcorp/FFXIVQuickLauncher#247]
**Describe the bug here:**
When the launcher was patching, after all downloads finished, it reported `-1.8GB left to download`.

**Steps to reproduce the bug:**
1. Let the launcher install 39 patches, wait until your downloads finish, hope your disk doesn't melt from an hour of maximum activity
2. Look at the amount remaining to download while the patches are installed

I don't actually know if this is really reproducible since you might need to have 39 patches trying to install at once, but I got a screenshot at least.

**Expected behavior**
Not attempting to download a negative amount of data

**Screenshots**
![](https://cdn.discordapp.com/attachments/443879875208544266/738116837472075826/unknown.png)

**Other information (*please* complete the following information):**
  Operating System: windows 10 home edition
  XIVLauncher version: no idea how to _properly_ tell that but I see `app-5.0.4` in the folder so I assume it's 5.0.4 (although I also see `app-5.0.3`)
  Launching as admin?: not as far as I'm aware
  Using Steam?: literally just stopped doing that yesterday
  Addons/Plugins enabled: don't think it'll be relevant, but here:
![](https://i.imgur.com/tCJFkjn.png)

**Additional information**
I mean, nothing seems to have actually _broken_, just the "download remaining" counter went negative. Probably not a real "problem" but I figured it couldn't hurt to report it anyway.

**Comment by goaaats** [comment]
Yeah, the "data left" counter is a bit broken, but the actual install should work as expected!
Did you have any problems with the game after this?

**Comment by PrincessRTFM** [comment]
Just loaded in, but nothing seems to be acting wonky. All plugins loaded, no updates (I usually check every day or so), game is responsive, FPS is normal, I can talk to this NPC just fine... looks like the game itself is all good, just the counter is iffy. As far as I can tell from turning in one quest before I saw the github notification, the game is fine!

**Comment by goaaats** [comment]
I added a fix for this and it seems like it worked, so good job me
