### ISSUE TITLE
Expansion

### ISSUE THREAD

**Issue by Mina1881** [goatcorp/FFXIVQuickLauncher#248]
Is there a chance to adjust with a plugin which addon is started? I play Final Fantasy XIV since 4 years and I want see the old titlescreens again.  I hope of feeling of the past years. If  that is not possible, is there a chance to make it possible?

**Comment by Zyian** [comment]
There is the `TitleEdit` plugin you can install and configure which will allow you to do exactly that. Play Shadowbringers with the Heavensward title screen (or any other title screen)

**Comment by goaaats** [comment]
This is the wrong project to ask this in, but you can actually do this already: type /xlplugins in-game and install the "Title Edit" plugin. It'll let you choose which expansion to show at the start!
Make sure the in-game add-on is enabled in the settings.
