### ISSUE TITLE
updating universalis other than just with a marketboard search

### ISSUE THREAD

**Issue by AmenneHolelane** [goatcorp/FFXIVQuickLauncher#249]
**What is your suggestion/feature request?**
updating universalis when you post an item for sale, not just when you search for an item.

**Describe how you'd like this to work**
1) call retainer 
2) either post an item or adjust price of an item
3) exit the menu
4) ????
5) check universalis for new price

**Comment by Caraxi** [comment]
Updating when you post an item is hard, because the item isn't actually on the market board when you do it, until you close the retainer's UI. Best way to do it is check the price after you post

**Comment by Krude** [comment]
What about buying an item? IME, buying an item doesn't update universalis unless you close and then reopen the item listing after the transaction. Which tripped me up the first time i did big cross world trips for cheap bulk material shopping.

You don't get a full list refresh on buying the item, but maybe you can send an order to delist an entry when the "you bought this" packet comes in?
