### ISSUE TITLE
Installation has failed

### ISSUE THREAD

**Issue by CalionSilus** [goatcorp/FFXIVQuickLauncher#250]
**Describe the bug here:**
I can't install FFXIV Launcher in new pc.

**Steps to reproduce the bug:**
Example:
```
1. Click on setup.exe
2. error happens :(
```

**Expected behavior**
Example: ``I expected the game to start when I put in the Konami code``

**Screenshots**

![image](https://user-images.githubusercontent.com/66424727/89161975-55478e00-d5ae-11ea-91fd-654234c0d0e6.png)

**Other information (*please* complete the following information):**
  Operating System: Windows 10 pro
  XIVLauncher version: 5.0.5
  Launching as admin?: yes
  Using Steam?: no
  Addons/Plugins enabled: n/a

**Additional information**

error log
2020-08-03 17:21:42> Program: Starting Squirrel Updater: --install .
2020-08-03 17:21:42> Program: Starting install, writing to C:\Users\bookn\AppData\Local\SquirrelTemp
2020-08-03 17:21:42> Program: About to install to: C:\Users\bookn\AppData\Local\XIVLauncher
2020-08-03 17:21:42> CheckForUpdateImpl: Couldn't write out staging user ID, this user probably shouldn't get beta anything: System.IO.DirectoryNotFoundException: 'C:\Users\bookn\AppData\Local\XIVLauncher\packages\.betaId' 경로의 일부를 찾을 수 없습니다.
   위치: System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   위치: System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   위치: System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   위치: System.IO.StreamWriter.CreateFile(String path, Boolean append, Boolean checkHost)
   위치: System.IO.StreamWriter..ctor(String path, Boolean append, Encoding encoding, Int32 bufferSize, Boolean checkHost)
   위치: System.IO.File.InternalWriteAllText(String path, String contents, Encoding encoding, Boolean checkHost)
   위치: System.IO.File.WriteAllText(String path, String contents, Encoding encoding)
   위치: Squirrel.UpdateManager.CheckForUpdateImpl.getOrCreateStagedUserId()
2020-08-03 17:21:42> CheckForUpdateImpl: Failed to load local releases, starting from scratch: System.IO.DirectoryNotFoundException: 'C:\Users\bookn\AppData\Local\XIVLauncher\packages\RELEASES' 경로의 일부를 찾을 수 없습니다.
   위치: System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   위치: System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   위치: System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   위치: Squirrel.Utility.LoadLocalReleases(String localReleaseFile)
   위치: Squirrel.UpdateManager.CheckForUpdateImpl.<CheckForUpdate>d__2.MoveNext()
2020-08-03 17:21:42> CheckForUpdateImpl: Reading RELEASES file from C:\Users\bookn\AppData\Local\SquirrelTemp
2020-08-03 17:21:42> CheckForUpdateImpl: First run or local directory is corrupt, starting from scratch
2020-08-03 17:21:42> ApplyReleasesImpl: Writing files to app directory: C:\Users\bookn\AppData\Local\XIVLauncher\app-5.0.5
2020-08-03 17:21:44> IEnableLogger: Failed to install package to app dir: System.UnauthorizedAccessException: 'C:\Users\bookn\AppData\Local\XIVLauncher\app-5.0.5\XIVLauncher.exe' 경로에 대한 액세스가 거부되었습니다.
   위치: System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   위치: System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   위치: System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   위치: SharpCompress.Readers.IReaderExtensions.WriteEntryToFile(IReader reader, String destinationFileName, ExtractionOptions options)
   위치: Squirrel.ReleasePackage.<>c__DisplayClass15_2.<ExtractZipForInstall>b__1()
   위치: Squirrel.Utility.<>c__DisplayClass8_0.<Retry>b__0()
   위치: Squirrel.Utility.Retry[T](Func`1 block, Int32 retries)
   위치: Squirrel.Utility.Retry(Action block, Int32 retries)
   위치: Squirrel.ReleasePackage.<>c__DisplayClass15_0.<ExtractZipForInstall>b__0()
   위치: System.Threading.Tasks.Task.InnerInvoke()
   위치: System.Threading.Tasks.Task.Execute()
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass7_0.<<installPackageToAppDir>b__0>d.MoveNext()
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: Squirrel.Utility.<LogIfThrows>d__43`1.MoveNext()
2020-08-03 17:21:44> Unhandled exception: System.AggregateException: 하나 이상의 오류가 발생했습니다. ---> System.UnauthorizedAccessException: 'C:\Users\bookn\AppData\Local\XIVLauncher\app-5.0.5\XIVLauncher.exe' 경로에 대한 액세스가 거부되었습니다.
   위치: System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   위치: System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   위치: System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   위치: SharpCompress.Readers.IReaderExtensions.WriteEntryToFile(IReader reader, String destinationFileName, ExtractionOptions options)
   위치: Squirrel.ReleasePackage.<>c__DisplayClass15_2.<ExtractZipForInstall>b__1()
   위치: Squirrel.Utility.<>c__DisplayClass8_0.<Retry>b__0()
   위치: Squirrel.Utility.Retry[T](Func`1 block, Int32 retries)
   위치: Squirrel.Utility.Retry(Action block, Int32 retries)
   위치: Squirrel.ReleasePackage.<>c__DisplayClass15_0.<ExtractZipForInstall>b__0()
   위치: System.Threading.Tasks.Task.InnerInvoke()
   위치: System.Threading.Tasks.Task.Execute()
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass7_0.<<installPackageToAppDir>b__0>d.MoveNext()
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: Squirrel.Utility.<LogIfThrows>d__43`1.MoveNext()
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   위치: Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: Squirrel.UpdateManager.<FullInstall>d__10.MoveNext()
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   위치: Squirrel.Update.Program.<Install>d__4.MoveNext()
   --- 내부 예외 스택 추적의 끝 ---
   위치: System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   위치: System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   위치: System.Threading.Tasks.Task.Wait()
   위치: Squirrel.Update.Program.executeCommandLine(String[] args)
   위치: Squirrel.Update.Program.main(String[] args)
---> (내부 예외 #0) System.UnauthorizedAccessException: 'C:\Users\bookn\AppData\Local\XIVLauncher\app-5.0.5\XIVLauncher.exe' 경로에 대한 액세스가 거부되었습니다.
   위치: System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   위치: System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   위치: System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   위치: SharpCompress.Readers.IReaderExtensions.WriteEntryToFile(IReader reader, String destinationFileName, ExtractionOptions options)
   위치: Squirrel.ReleasePackage.<>c__DisplayClass15_2.<ExtractZipForInstall>b__1()
   위치: Squirrel.Utility.<>c__DisplayClass8_0.<Retry>b__0()
   위치: Squirrel.Utility.Retry[T](Func`1 block, Int32 retries)
   위치: Squirrel.Utility.Retry(Action block, Int32 retries)
   위치: Squirrel.ReleasePackage.<>c__DisplayClass15_0.<ExtractZipForInstall>b__0()
   위치: System.Threading.Tasks.Task.InnerInvoke()
   위치: System.Threading.Tasks.Task.Execute()
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: Squirrel.UpdateManager.ApplyReleasesImpl.<>c__DisplayClass7_0.<<installPackageToAppDir>b__0>d.MoveNext()
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: Squirrel.Utility.<LogIfThrows>d__43`1.MoveNext()
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   위치: Squirrel.UpdateManager.ApplyReleasesImpl.<ApplyReleases>d__2.MoveNext()
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: Squirrel.UpdateManager.<FullInstall>d__10.MoveNext()
--- 예외가 throw된 이전 위치의 스택 추적 끝 ---
   위치: System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   위치: System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   위치: Squirrel.Update.Program.<Install>d__4.MoveNext()<---

**Comment by goaaats** [comment]
Please check your antivirus, it may remove the launcher while installing.

**Comment by CalionSilus** [comment]
Thank you for your reply.

I turned antivirus off and tried again, but still the same issue occurred.

**Comment by Aida-Enna** [comment]
Hello @CalionSilus - Is this still an issue?

**Comment by CalionSilus** [comment]
No. It is no more a issue.

2020년 9월 23일 (수) 20:06, Aida Enna <notifications@github.com>님이 작성:

**Comment by Aida-Enna** [comment]
Thank you for responding. Stay safe!
