### ISSUE TITLE
Launch error

### ISSUE THREAD

**Issue by Jaleney** [goatcorp/FFXIVQuickLauncher#251]
**Describe the bug here:**
Example: I tried starting the launcher and get the error I submitted in the screenshot

**Steps to reproduce the bug:**
Example:
1. Click on XIVlauncher

**Expected behavior**
Example: the launcher to start

**Screenshots**
https://i.imgur.com/6eRsIlB.png

**Other information (*please* complete the following information):**
  Operating System: Windows 10
  XIVLauncher version: 5.0.5.
  Launching as admin?: Yes
  Using Steam?: No
  Addons/Plugins enabled: No

**Additional information**
I tried uninstalling and reinstalling but I keep getting the error.

**Comment by Aida-Enna** [comment]
Hey there! It's been a while since this was opened - Are you still having this issue?
