### ISSUE TITLE
Option to not delete downloaded patch files after installation

### ISSUE THREAD

**Issue by lucky1804** [goatcorp/FFXIVQuickLauncher#252]
**What is your suggestion/feature request?**
After the launcher is finished with instalation of patches it deletes .patch files in downloads folder which pervents archiving

**Describe how you'd like this to work**
It would be really great if under patching option there is an checkbox that pervents .patch files from being deleted after installation of patches is complete to make it easier to keep an archive of patch file for perservation

**Comment by goaaats** [comment]
So this definitely works now, I fucked up the initial fix because I accidentally implemented deletion twice and only removed one of them, oops
