### ISSUE TITLE
Patch installer deletes game when patch dl location is == game location

### ISSUE THREAD

**Issue by AmenneHolelane** [goatcorp/FFXIVQuickLauncher#253]
**Describe the bug here:**
putting patch location in same folder as game install will nuke the entire folder including your newly installed game when it deletes patches

**Expected behavior**
for it not to do that

**Comment by AmenneHolelane** [comment]
Is this fixed?

**Comment by goaaats** [comment]
This should not be allowed in the first place so I'll add a check for it
