### ISSUE TITLE
Addons not working after 5.3

### ISSUE THREAD

**Issue by seathasky** [goatcorp/FFXIVQuickLauncher#257]
Addons not working after 5.3

**Expected behavior**
I checked plugin folder and all my addons are there yet none are working in game. /xlplugins command does not work either. Ingame features is turned on in launcher.

**Screenshots**
https://imgur.com/a/ctM8Yh8

**Other information (*please* complete the following information):**
  Operating System: win 10
  XIVLauncher version: latest release
  Launching as admin?: yes
  Using Steam?: no
  Addons/Plugins enabled: fps plugin, mouseover, slide.

**Additional information**
Doesnt work.

**Comment by goaaats** [comment]
Still need to be updated for patch 5.3, please be patient

**Comment by seathasky** [comment]
sry didnt realize
