### ISSUE TITLE
MacroRecursion "not ready"

### ISSUE THREAD

**Issue by flemur** [goatcorp/FFXIVQuickLauncher#259]
**Describe the bug here:**
When trying to run a macro, it reaches the link to the second macro and says "macrorecursion is not ready, run a macro to setup" then fails. 

**Steps to reproduce the bug:**
1) Create two macros.
2) Link first macro to second (ie, "/macro 30")
3) Run first macro.
4) It runs through all steps until /macro, then fails

**Expected behavior**
Should continue past /macro

**Other information (*please* complete the following information):**
  Operating System: Win10
  XIVLauncher version: Updated for 5.3
  Launching as admin?: Yes
  Using Steam?: No
  Addons/Plugins enabled: Macrorecursion, pingplugin

**Additional information**

**Comment by goaaats** [comment]
Hi, this was seemingly related to patch 5.3. I will close this, please open an issue in the MacroRecursion repository if it occurs again.
