### ISSUE TITLE
running setup.exe doesnt do anything

### ISSUE THREAD

**Issue by Mete0** [goatcorp/FFXIVQuickLauncher#265]
Im trying to install the launcher using setup.exe but when I double click it, nothing happens. Also tried running in admin mode. Recently just reinstalled FFXIV. Or maybe a Windows update broke it?

**Comment by Aida-Enna** [comment]
Do you have a XIVLauncher folder in your %APPDATA% folder?

**Comment by Mete0** [comment]
I was able to install it by downloading an older version and having that update so at least theres a workaround.

**Comment by Aida-Enna** [comment]
Gonna close this as it doesn't seem to be a common issue - Feel free to reference it in future issues if it happens again.
