### ISSUE TITLE
dalamud no longer works after 2020.08.19.0000 update

### ISSUE THREAD

**Issue by LastExceed** [goatcorp/FFXIVQuickLauncher#266]
After tonight's update everything Dalamud related stopped working as if it was disabled (e.g. nothing happens when using /xlplugins)

  Operating System: Win10
  XIVLauncher version: 5.1.1.0
  Launching as admin?: No
  Using Steam?: Yes
  Addons/Plugins enabled: None

**Comment by ackwell** [comment]
As is to be expected. This will happen every game update.

**Comment by Sanaki** [comment]
Well damn. It's already fixed. That was fast.
