### ISSUE TITLE
Installer failed

### ISSUE THREAD

**Issue by bdr85** [goatcorp/FFXIVQuickLauncher#274]
When I go to plugins installer> Teleporter, I click install and it says "Installer failed : The plugin installer ran into an issue or the plugin is incompatible. Please restart the game and report this error on our discord."

**Steps to reproduce the bug:**

1. Launch XIVLauncher
2. Type /xlplugins
3. Go to The Teleporter section in click install.
```


**Expected behavior**
I would expect the plugin to just install and work. I have not had an issue with any other plugins so far.



**Other information (*please* complete the following information):**
  Operating System: Windows 10
  XIVLauncher version: 5.1.1.0 - 877acc0 - 4.0.30319.42000
  Launching as admin?: No, xiv launcher says not to launch as admin
  Using Steam?: No
  Addons/Plugins enabled: Browser.Host.Plugins, Globetrotter, NeatNoter, SonarPlugin

**Comment by Aida-Enna** [comment]
It works fine for me - Can you post a screenshot of your %APPDATA%\XIVLauncher\installedPlugins folder and %APPDATA%\XIVLauncher\pluginConfigs folder?

**Comment by Caraxi** [comment]
I believe this an issue caused by being on the test branch of plugins and trying to update while the live version is ahead of the test version. This is more of a Dalamud issue than XIVLauncher though

**Comment by bdr85** [comment]
Ok thanks for the swift replies :) I wasn't too sure whether to post here or elsewhere about the issue. When I get in I will take a ss for ya. I do appreciate it!
