### ISSUE TITLE
Random Crash

### ISSUE THREAD

**Issue by AGShiel** [goatcorp/FFXIVQuickLauncher#276]
Game will randomly crash, and this is exclusive to using the quicklauncher.  I didn't have this issue before using it, and stopped having it after I stopped using the launcher.  Not sure what could be causing it as the game force closes with no error message.

**Comment by Zyian** [comment]
Could you provide more details about the crash? What operating system, version of XL you're using, any plugins, what you were doing when the crashes happen (walking around town, entering certain zones, etc). It's quite hard to try to find a solution without any additional information

**Comment by AGShiel** [comment]
OS: Windows 10
Plugins: Accurate Countdown, Damage Info, Neat Noter, No Soliciting, Ping Plugin, Pixel Perfect, Slidecast, Title Edit, XIV Combo
Accurate Countdown, Title Edit, and IV Combo were toggled off.
Version: 5.1.1.0
I was in the middle of Unending Coil of Bahamut, and experienced crashes at different times in the fight when I crashed the most, but that's more of a product of me raid logging.  I have crashed while just running around in Crystarium as well.
I'm using DX11.

If there's any more information I can provide please let me know, and I'd be happy to provide it.

**Comment by utoxin** [comment]
I'm seeing this issue as well. When Dalamud is injected, I get seemingly random dx11 crashes.

OS: Windows 10
Plugins: Adventurer in Need, Price Check
Current version of the launcher as of this writing (not at that computer right now, just doing research about the crash)

**Comment by goaaats** [comment]
We don't have enough information to find the cause for this, if we run into it ourselves, we will check it out - thank you!

**Comment by x04ty29er** [comment]
Sorry to revive an old thread here, but I wanted to add information here as I believe I have isolated the issue.

I was getting similar crashes here (DX11 error), and noticed that I was getting frameskips when PixelPerfect was being rendered offscreen (camera very close to character, or actual character position offscreen [Delbrum Reginae encounter Queen's Guard Bomb launch]). Repeated exposure to this frameskip would eventually lead to DX crash. I'm not sure if this is related to the plugin or the launcher, but I am able to consistently reproduce this with PixelPerfect enabled, and it goes away when PixelPerfect is disabled.

Also does not appear to affect everybody as others do not appear to have this issue.

May also be interaction with GShade as this is also on my installation.
