### ISSUE TITLE
Browser Host Plug-In always triggers "need update" message.

### ISSUE THREAD

**Issue by iconius2000** [goatcorp/FFXIVQuickLauncher#277]
Every time I launch FFXIV using the Launcher, I get the message 'One or more of your plugins needs to be updated. Please use the /xlplugins command in-game to update them!'. However, when I go and update, it only shows that Browser Host updates and the version number doesn't change [it was last at version 1.1.0.3 and updating didn't change it from 1.1.0.3]

**Steps to reproduce the bug:**

1. Launch FFXIV through Launcher
2. Update Message Shows after login
3. Click Update
4. Browser Host "updates"
5. Version number is the same for Browser Host
6. Repeat whole process and same thing.
```


**Expected behavior**
Should not be telling me to update every login and do nothing.

**Other information (*please* complete the following information):**
  Operating System: Windows 10 Home Edition
  XIVLauncher version: v5.1.1.0
  Launching as admin?: No
  Using Steam?: No
  Addons/Plugins enabled: Yes

**Comment by karashiiro** [comment]
CC @ackwell

**Comment by deonfoxfangs** [comment]
Having a similar issue though it tells me it's incompatible when it tries to update. Have tried uninstalling and re-installing and still has the same problem.

**Comment by ackwell** [comment]
Given reports I've seen, it's likely caused by an existing version you have installed. Please go to `%appdata%\XIVLauncher\installedPlugins` and remove the `BrowserHost.Plugin` folder - it should work fine after that point. Let me know if it doesn't.

**Comment by ackwell** [comment]
version `1.1.1.0` is released, and should hopefully resolve this issue. please let us know if it persists beyond the update to `1.1.1.0`

**Comment by goaaats** [comment]
Thank you ack, very good

**Comment by iconius2000** [comment]
Thank you,

The issue no longer occurs on 1.1.1.0

Paul Zullo
