### ISSUE TITLE
Crash to desktop after patching 5.31

### ISSUE THREAD

**Issue by seathasky** [goatcorp/FFXIVQuickLauncher#281]
https://www.youtube.com/watch?v=7WldJ-79NbU   <--what happens with launcher

**Describe the bug here:**
Immediately crashes game when launching with XIV Launcher after patching to 5.31.

Game runs great with Squares launcher.

**Steps to reproduce the bug:**

Starting game with ffxiv launcher after patch 5.31

**Other information (*please* complete the following information):**
  Operating System: windows 95
  XIVLauncher version: latest
  Launching as admin?: no
  Using Steam?: no
  Addons/Plugins enabled: xivcombo, market, penny, mouseover, fps, ms

**Comment by darkyshiny** [comment]
The latest version of PingPlugin is bugged and causes the game to crash, this is a known issue and is being looked into. 

Try deleting it manually from `%appdata%\XIVLauncher\InstalledPlugins`

**Comment by seathasky** [comment]
> The latest version of PingPlugin is bugged and causes the game to crash, this is a known issue and is being looked into.
> 
> Try deleting it manually from `%appdata%\XIVLauncher\InstalledPlugins`

Thanks, that fixed it. Appreciate it.
