### ISSUE TITLE
Character Data Sync syncing issue

### ISSUE THREAD

**Issue by ThatCatLune** [goatcorp/FFXIVQuickLauncher#288]
I have the Character Data Sync plugin downloaded and set to my main character, but sometimes it will change my main character's UI after being logged into another character.

Most recently: My partner logged in using the launcher, and when I logged in, my main character had his UI and hotbar setup despite him not touching plugins.

Previously: The odd hotbar has gone missing/reset or changed itself around, usually after I change something on another character.

**Comment by goaaats** [comment]
This is an issue for char data sync, not related to this - acknowledged though, however, seems to be a game issue
