### ISSUE TITLE
Third-party language changing apps hang the game

### ISSUE THREAD

**Issue by InkyQuill** [goatcorp/FFXIVQuickLauncher#289]
**Describe the bug here:**
I am not a native English speaker so I have multiple keyboard layouts. I use an app that changes keyboard layout on a certain combinations of buttons instead of a native Windows one. When I use those combinations in FFXIV with XIVLauncher, the game hangs.

**Steps to reproduce the bug:**
```
1. Have two or more layouts
2. Use third-party layout changer
3. Use layout changing combination in FFXIV chat
4. Game hangs.
```

**Expected behavior**
Layout changes, game still works

**Other information (*please* complete the following information):**
  Operating System: Win 10
  XIVLauncher version: latest (bug persists through the latest 4 versions)
  Launching as admin?: no
  Using Steam?: yes
  Addons/Plugins enabled: Discord Rich Presence, Damage Info Plugin, Item Search, Good Memory, Market Board, Orchestrion, SlideCast, XIVCombo

**Additional information**
It seems that this behavior is linked to native Windows hook that changes keyboard layouts that all layout changers use. Game works fine when new patch comes out (when there is no Dalamud, with just launcher functionality).

**Comment by InkyQuill** [comment]
One of those apps that hang the game (with just layout changing, no text conversion options): https://github.com/BladeMight/Mahou/releases

**Comment by goaaats** [comment]
Not a bug - this is because of the anticheat SE has added a while ago.
Not planning to change the way we circumvent it at the moment, however we may do so in the future.
