### ISSUE TITLE
Text box too small in French

### ISSUE THREAD

**Issue by Aireil** [goatcorp/FFXIVQuickLauncher#296]
Here are three text boxes that are too small for the French localization.

![3tAwUCl](https://user-images.githubusercontent.com/33433913/97714737-d3d69d80-1ac1-11eb-8633-63452b4cd14d.png)
1: "Utiliser un mot de passe à usage unique"
2: "Utiliser le compte de service Steam"
3: "Connexion"

If needed, the text could be changed as follows:
1: "Mot de passe à usage unique"
2: "Compte de service Steam"
3: "Connexion"

**Comment by aUsefulMethod** [comment]
Is this still open? I could look into it after finals this week if so.

**Comment by Aireil** [comment]
Soon fixed by goat's rescaling :)
