### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by HitagiSenjougaharaFFXIV** [goatcorp/FFXIVQuickLauncher#300]
System.Exception: Game exited prematurely
   à XIVLauncher.Game.Launcher.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments) dans D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Launcher.cs:ligne 255
Version: 5.1.1.0
Git Hash: 807acc0
Context: XG LaunchGame
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: French
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

Addons: []

**Comment by reiichi001** [comment]
Can you please upload your output.log file from `%appdata%\XIVLauncher` and your dalamud.txt file from `%appdata%\XIVLauncher\addon\Hooks` please?

Do you have any other programs that interact with FFXIV such as RivaTuner/RTSS, MSI Afterburner, Reshade/Gshade/etc, OBS streaming, or VPNs?

If you have not already, please try to install the VC Redist from Microsoft at [https://aka.ms/vs/16/release/VC_redist.x64.exe](https://aka.ms/vs/16/release/VC_redist.x64.exe) as well as the .NET 4.8 Runtime [https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net48-web-installer](https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net48-web-installer).

**Comment by AmenneHolelane** [comment]
That is a very old version of windows. The required .Net 4.8 Runtime won't install on 8.0, only 8.1 per https://docs.microsoft.com/en-us/dotnet/framework/install/on-windows-8. As that version of windows stopped being supported on January 12, 2016, I don't know of anything for workarounds for the .net franework

**Comment by HitagiSenjougaharaFFXIV** [comment]
i've desinstalled xivlauncher then reinstalled with setup last update. it
works now... thx
