### ISSUE TITLE
fix it plz. My game is not steam btw

### ISSUE THREAD

**Issue by HitagiSenjougaharaFFXIV** [goatcorp/FFXIVQuickLauncher#301]
System.Exception: Game exited prematurely
   à XIVLauncher.Game.Launcher.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments) dans D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Launcher.cs:ligne 255
Version: 5.1.1.0
Git Hash: 807acc0
Context: XG LaunchGame
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: French
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

Addons: []

**Comment by goaaats** [comment]
posting it again won't make anyone help you faster
