### ISSUE TITLE
Unable to install

### ISSUE THREAD

**Issue by jj94523** [goatcorp/FFXIVQuickLauncher#306]
**Describe the bug here:**
Get an error with every attempt to install

**Steps to reproduce the bug:**
Run setup.exe

**Expected behavior**
Install program

**Screenshots**
Error I'm given
https://imgur.com/a/nMAKysQ

**Other information (*please* complete the following information):**
  Operating System: Current windows 10 pro
  XIVLauncher version: current version on github
  Launching as admin?: yes
  Using Steam?:no
  Addons/Plugins enabled: N/A

**Additional information**

**Comment by PrincessRTFM** [comment]
Possibly related to #251 - the error (failed to connect to remote server, attempt to access socket in way forbidden by access permissions) matches up.

**Comment by jj94523** [comment]
Yup that was it. It was the firewall. Thank you!
