### ISSUE TITLE
failed to launch

### ISSUE THREAD

**Issue by lee89tw14** [goatcorp/FFXIVQuickLauncher#314]
System.Net.WebException: リモート サーバーがエラーを返しました: (504) ゲートウェイ タイムアウト
   場所 System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   場所 System.Net.WebClient.DownloadString(Uri address)
   場所 XIVLauncher.Game.Launcher.CheckBootVersion(DirectoryInfo gamePath) 場所 D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Launcher.cs:行 326
   場所 XIVLauncher.Windows.MainWindow.HandleBootCheck(Action whenFinishAction) 場所 D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\MainWindow.xaml.cs:行 260
Version: 5.1.1.0
Git Hash: 807acc0
Context: HandleBootCheck
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: Japanese
Game path: F:\Games\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

Addons: []

**Comment by lee89tw14** [comment]
![image](https://user-images.githubusercontent.com/22855239/101360031-0dc46c00-38d8-11eb-99c3-8533f3bbe4e4.png)

**Comment by goaaats** [comment]
maintenance: https://is.xivup.com/
