### ISSUE TITLE
Error preventing start

### ISSUE THREAD

**Issue by GolumAmicicide** [goatcorp/FFXIVQuickLauncher#316]
System.Net.WebException: Fjärrservern returnerade ett fel: (504) Gateway-timeout.
   vid System.Net.WebClient.DownloadDataInternal(Uri address, WebRequest& request)
   vid System.Net.WebClient.DownloadString(Uri address)
   vid XIVLauncher.Game.Launcher.CheckBootVersion(DirectoryInfo gamePath) i D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Launcher.cs:rad 326
   vid XIVLauncher.Windows.MainWindow.HandleBootCheck(Action whenFinishAction) i D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\MainWindow.xaml.cs:rad 260
Version: 5.1.1.0
Git Hash: 807acc0
Context: HandleBootCheck
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
Game path: C:\Program Files (x86)\SteamLibrary\steamapps\common\FINAL FANTASY XIV Online

Addons: []

**Comment by Aireil** [comment]
The game is currently under maintenance: https://eu.finalfantasyxiv.com/lodestone/news/detail/dcebc13b405f041779b82648c3a08ab54a7b085e

**Comment by GolumAmicicide** [comment]
big brain moment, i was trying to find a verify for the steam version because nothing worked, thanks lmao
