### ISSUE TITLE
The launcher 

### ISSUE THREAD

**Issue by LuluNight** [goatcorp/FFXIVQuickLauncher#317]
I keep trying to start on ffxiv for both launchers and none are working so I'm not sure on how to fix's it T_T

**Comment by Aireil** [comment]
Wait for Square Enix to fix both. The game is currently under maintenance: https://eu.finalfantasyxiv.com/lodestone/news/detail/dcebc13b405f041779b82648c3a08ab54a7b085e

**Comment by Aida-Enna** [comment]
The game is currently under maintenance: https://eu.finalfantasyxiv.com/lodestone/news/detail/dcebc13b405f041779b82648c3a08ab54a7b085e
