### ISSUE TITLE
Multiboxing Issue?

### ISSUE THREAD

**Issue by wakefieldite** [goatcorp/FFXIVQuickLauncher#318]
I can load only two clients now after the most recent patch, previously I've had five clients running at the same time. Closing one of the two clients resolves this error, but trying to launch a third again causes it to return.

System.Exception: Game exited prematurely
   at XIVLauncher.Game.Launcher.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments) in D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Launcher.cs:line 255
Version: 5.2.0.0
Git Hash: 7f46f54
Context: XG LaunchGame
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

Addons: []

**Comment by Caraxi** [comment]
> previously I've had five clients running at the same time. 
Not possible

**Comment by wakefieldite** [comment]
> 
> 
> > previously I've had five clients running at the same time.
> 
> Not possible. The max, capped by square enix, is 2.

So you're telling me I did not have 5 clients running on 3 monitors off of my one laptop? I have been multiboxing with a minimum of 3 clients for several months. I've had 5 on my laptop and 4 on my desktop, so yes it is possible.

**Comment by wakefieldite** [comment]
Resolved it on my own, thanks anyways.
