### ISSUE TITLE
Opening Custom Deliveries Menu for Ehll Tou Or Her Crafts in the Crafting Menu Crashes Game with No Error

### ISSUE THREAD

**Issue by bicbeep** [goatcorp/FFXIVQuickLauncher#322]
**Describe the bug here:**
``
Using CTRL+U > Custom Deliveries > Click Ehll Tou, crashes the game instantly with no error. 
Also, opening the crafting menu and trying to pull up any of her recipes instantly crashes the game. 
Opened the game with the normal launcher, and the issue does not occur. Only when using XIVLauncher.
``

**Steps to reproduce the bug:**
```
1. Log into the game fully
2. Press CTRL+U > Custom Deliveries > Click on Ehll Tou, or talk to Ehll Tou directly at the Firmament
3. Alternatively to #2, open the crafting menu (N), and search for Ehll Tou's recipes (any of them), 
or check under the Custom Deliveries tab for Ehll Tou
4. The game instantly closes with no error or warning
```

**Expected behavior**
It's supposed to not crash, so you can see what you can craft/gather for the week, 
and actually do the custom deliveries for Ehll Tou

**Screenshots**
n/a, easy to follow instructions (or, I think they are; I can add screenshots if needed)

**Other information (*please* complete the following information):**
  Operating System: **Windows 10, 64 bit**
  XIVLauncher version: **5.2.0.0**
  Launching as admin?: **Yes**
  Using Steam?: **Yes**
  Addons/Plugins enabled: **Happens with plugins and without plugins (all disabled)**

**Additional information**
Tested this with my friend, who is also using XIVLauncher on an entirely different machine. He gets the same exact results as me. He discovered launching the game with the regular launcher bypasses this bug. He also tried launching with XIVLauncher and disabling all his addons, but it didn't help. Still crashed.

**Comment by reiichi001** [comment]
Hello,

Can you please try the following? This looks more like a plugin issue, but not all of the plugins that may load show in the plugin installer for you to disable them. (Things that should have automatically been disabled going from 5.35 Hotfix to 5.4).

1. Close the game
2. Go to `%AppData%\XIVLauncher\installedPlugins`
3. Remove the folder[s] for the plugin[s]
4. Relaunch
5. Let us know if the issue persists

**Comment by bicbeep** [comment]
Hi,

Thanks! That did fix it. I only deleted the addon folder in that directory, and not installedPlugins. I appreciate it!
