### ISSUE TITLE
/xlplugins command not working

### ISSUE THREAD

**Issue by OfficerBooty** [goatcorp/FFXIVQuickLauncher#323]
**Describe the bug here:**
So seeing as how people were able to get their command to work in-game post-update, I'm sort of stuck with the issue of it not working.

I launch the game, type in the command, and I get "The command /xlplugins does not exist."

Not sure if this changes anything, but I do utilize the launcher's "launch through Steam" feature.

So I went through the files after joining the Discord to see what's going on, and the funny thing is? I don't have... a dalamud.txt log.
I do have:
Dalamud.dll
Dalamud.Injector.exe.config
Dalamud.Injector.pdb
Dalamud.pdb
Dalamud.xml

For the first time today, when I booted up the game, Norton told me that it was removing dalamud.injector.exe, and forced me to restart my computer to remove it.

I didn't have any issues with this, even my antivirus, before yesterday's patch.

**Things I have tried:**
- Deleting the output.log to clear it and deleting all the plugins in the installedPlugins folder. I didn't have a dalamud.txt file when I did these steps, so I had to skip it. Launching the game didn't get it to work.
- Uninstalling the XIVLauncher and goatsoft from my localappdata and uninstalling the XIVLauncher from my appdata, only to do a full reinstall. After launching, I got the same issue.

**Other information (*please* complete the following information):**
  Operating System: Windows 10
  XIVLauncher version: v5.2.0.0
  Launching as admin?: No
  Using Steam?: Yes
  Addons/Plugins enabled: They were, but I've since then done a full reinstall.

**Comment by goaaats** [comment]
You may need to add the entire %AppData%\XIVLauncher folder to your exceptions. Especially Norton is notorious for preventing XL from working.

**Comment by OfficerBooty** [comment]
The thing is, I don't know how to add that to my exceptions, and Norton keeps removing dalamud.injector.exe every time I open the game.

**Comment by goaaats** [comment]
Try this: https://community.norton.com/en/forums/how-add-exception-norton-360-v4

**Comment by OfficerBooty** [comment]
I got it to work. Unfortunately my appdata folder wasn't selectable in Norton configuration, but I can tell you how I got it to work in case anyone else has the issue. You can add it to the Discord list if you'd like.

1. Type **%AppData%** into your computer's search bar
2. Scroll down and right click on **XIVLauncher**, then hit Properties.
3. On the General tab of the window, copy the Location _( it should look like C:\Users\name\AppData\Roaming )_
4. Open Norton 360
5. In the search bar (top right), search for **Exclusion**
6. Click on **Auto-Protect Exclusion**
7. On the Real Time Exclusions window, click on **Add Folders**
8. In the bar, paste your copied location and add **\XIVLauncher** at the end of it
9. Make sure you click OK, Apply, and then OK again before closing
10. Launch the game and make sure it works

**Comment by goaaats** [comment]
Thanks, we'll keep it in mind! Hope everything is working fine for you now.
