### ISSUE TITLE
The game won't start.

### ISSUE THREAD

**Issue by fanotsu** [goatcorp/FFXIVQuickLauncher#325]
It won't start with multiple accounts (3 accounts). 2 accounts are fine.
---------------------------
System.Exception: Game exited prematurely
   場所 XIVLauncher.Game.Launcher.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments) 場所 D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Launcher.cs:行 255
Version: 5.2.0.0
Git Hash: 7f46f54
Context: XG LaunchGame
OS: Microsoft Windows NT 6.1.7601 Service Pack 1
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: Japanese
LauncherLanguage: Japanese
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

Addons: []

**Comment by Aida-Enna** [comment]
You cannot open more than 2 copies of FFXIV without some sort of virual machine or isolation stuff going on.
