### ISSUE TITLE
If you enter a bad password and check automatic connexion, FFXIVQuickLauncher does not request a new password

### ISSUE THREAD

**Issue by legluondunet** [goatcorp/FFXIVQuickLauncher#342]
Hello,
I entered a bad password and checked "automatic connexion".
So FFXIVQuickLauncher quit and now when I launch it only shows me this error message:

![ArcoLinux_2020-12-23_12-35-10](https://user-images.githubusercontent.com/325405/102992764-22317700-451c-11eb-92f7-6a2c78a86bb5.png)

I expected it ask me to enter a new password.

I had to manually delete json files from /home/legluondunet/Games/final-fantasy-xiv-a-realm-reborn.bak/drive_c/users/legluondunet/Application Data/XIVLauncher/ folder, it is not very user friendly.

**Comment by Zyian** [comment]
You can hold **shift** when you open the Launcher in order to disable the autolaunch. The simple fix for this would be to ensure you have entered the correct password before you enable autolaunch

**Comment by legluondunet** [comment]
"The simple fix for this would be to ensure you have entered the correct password before you enable autolaunch"
I entered the correct password but today Square Enix disabled my account to force me to change password. 
Anyway it would be more user friendly to just return to the interface after clicking on "ok" on this error dialog box.
Close all windows after this error dialog box is a little "brutal".

**Comment by Aida-Enna** [comment]
Solved in #348.
