### ISSUE TITLE
5.2.1 CutSceneMovieOpening

### ISSUE THREAD

**Issue by NoakPalander** [goatcorp/FFXIVQuickLauncher#346]
Installing the newest version of the XIVlauncher using the bundled Lutris script, it does unfortunately _not_ set the required parameter for CutSceneMovieOpening in the FFXIV.cfg file. It's defaulted to 0 which doesn't allow you to get past the "connecting to data center" prompt. Manually changing the value from a 0 to 1 does work, but it appears to me that it's a bug with the install script, and not a conscious decision. I've only tried this once however on arch-5.9.14 so it might not be 100% generic.

**Comment by legluondunet** [comment]
Hello @NoakPalander,
thank you for your report, this issue is now fixed in Lutris script.
Please next time do not annoy FFXIVQuickLauncher with issues related to Lutris script.
Come on Lutris Discord to obtain support.

**Comment by legluondunet** [comment]
@goaaats this issue is resolved.

**Comment by goaaats** [comment]
Thanks! If it wouldn't have been possible in Lutris, we could have additionally enforced it in XIVLauncher code - but if it works like this, all good 👍
