### ISSUE TITLE
FFXIVQuickLauncher error

### ISSUE THREAD

**Issue by hellxh0225** [goatcorp/FFXIVQuickLauncher#353]
System.ArgumentNullException: 值不能为 null。
参数名: source
   在 System.Linq.Enumerable.Select[TSource,TResult](IEnumerable`1 source, Func`2 selector)
   在 XIVLauncher.Game.Patch.PatchManager..ctor(Repository repository, IEnumerable`1 patches, DirectoryInfo gamePath, DirectoryInfo patchStore, PatchInstaller installer) 位置 D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Patch\PatchManager.cs:行号 91
   在 XIVLauncher.Windows.MainWindow.InstallGamePatch(LoginResult loginResult, Boolean gateStatus) 位置 D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\MainWindow.xaml.cs:行号 414
   在 XIVLauncher.Windows.MainWindow.<StartLogin>d__17.MoveNext() 位置 D:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\MainWindow.xaml.cs:行号 494
Version: 5.2.1.0
Git Hash: 0fc3088
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: Japanese
LauncherLanguage: English
Game path: F:\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

Addons: []

**Comment by Aida-Enna** [comment]
Are you still having this issue?
