### ISSUE TITLE
Need to install plugins every time I launch the game

### ISSUE THREAD

**Issue by AzarathAI** [goatcorp/FFXIVQuickLauncher#357]
Plugin settings are still there when I install them again.

**Comment by reiichi001** [comment]
This sounds like they're being removed by your antivirus. Can you please try whitelisting/making exceptions for the following folders?
 - %localappdata%\XIVLauncher
 - %localappdata%\goatsoft
 - %appdata%\XIVLauncher

You can also check our FAQ on the XIVLauncher Discord server for steps for a variety of common AV programs if unsure how to do so. https://discord.com/channels/581875019861328007/586590269063954432/695694479923085474

**Comment by AzarathAI** [comment]
It didn't help. but I uninstalled the launcher and went to those same folders you mentioned and deleted everything, now it's working fine again.

Cheers!
