### ISSUE TITLE
"Don't save password" is not functional

### ISSUE THREAD

**Issue by goaaats** [goatcorp/FFXIVQuickLauncher#358]
Guess no one ever uses this huh
Setting doesn't persist on account, saves password after restart

**Comment by Daiki1212** [comment]
Strange thing,
for me it works fine. Even when you Tick it and close the Launcher it deletes the password.

But when you close your Game, the tick isnt set anymore (it still works tho). When you wanna deactivate this option you have to double click it. Seems like a Setting isnt loaded in the UI.

Using:
Single Account
OTP && no Steam
Windows 10
