### ISSUE TITLE
Will Chinese translation be added?

### ISSUE THREAD

**Issue by sunxyw** [goatcorp/FFXIVQuickLauncher#362]
**What is your suggestion/feature request?**
There are many Chinese (both traditional and simplified) players around me who are using xivlauncher. Would you like to add a Chinese translation?

**Describe how you'd like this to work**
A new Chinese translation.

**Additional context**
None

**Comment by goaaats** [comment]
Hi! I just added a section on Crowdin for simplified Chinese - feel free to make an account and help out. Thanks a bunch :)

https://crowdin.com/project/ffxivquicklauncher/zh-CN#

**Comment by sunxyw** [comment]
> Hi! I just added a section on Crowdin for simplified Chinese - feel free to make an account and help out. Thanks a bunch :)
> 
> https://crowdin.com/project/ffxivquicklauncher/zh-CN#

Thank you! I just requested to join the translators team.
