### ISSUE TITLE
"The Square Enix account cannot play Final Fantasy XIV"

### ISSUE THREAD

**Issue by sangoku116** [goatcorp/FFXIVQuickLauncher#367]
**Describe the bug here:**
Getting the following error message when launching: 'The Square Enix account cannot play Final Fantasy XIV"

**Steps to reproduce the bug:**
Example:
```
1. Launch the Launcher
```

**Expected behavior**
Launcher launches the game and logs me in automatically.

**Screenshots**
![9701528feeef21cb6ce95fb189cd9a87 (1)](https://user-images.githubusercontent.com/18174977/106343968-2583f500-6276-11eb-886c-58bf0e70fb59.png)

**Other information (*please* complete the following information):**
  Operating System: Arch Linux
  XIVLauncher version: 5.2.1.0
  Launching as admin?: No
  Using Steam?: Yes
  Addons/Plugins enabled: 

**Additional information**
It was working fine when I played last Sunday.  I tried logging in without auto-login and disabling/re-enabling steam service.

**Comment by Kromilan** [comment]
why was this closed? How did the issue get resolved?

**Comment by Kromilan** [comment]
I replied to this because I am getting the same error message since two days ago and was hoping to find a solution when I saw this threat. but as you suggested, I'll make a new threat for that. thank you for the reply.
