### ISSUE TITLE
Dalamud broken with patch 5.45

### ISSUE THREAD

**Issue by Illumium** [goatcorp/FFXIVQuickLauncher#372]
Dalamud seems to be completely non-functional as of FFXIV patch 5.45. Tested with reinstalling, restarting and on different PCs. Plugins don't work, commands are not recognised and the usual Dalamud greeting message in chat upon login is also missing. :(

**Steps to reproduce the bug:**
```
1. Launch XL as admin
2. FFXIV launches
3. Dalamud does not :(
```

**Other information (*please* complete the following information):**
  Operating System:Win10
  XIVLauncher version:5.2.1
  Launching as admin?:Yes
  Using Steam?:Yes
  Addons/Plugins enabled:XIVCombo, RichPresence, Pennypincher

**Comment by goaaats** [comment]
Needs update
