### ISSUE TITLE
Typoing password while in "automatic login" mode prevents user from correcting password.

### ISSUE THREAD

**Issue by AshenPheonix** [goatcorp/FFXIVQuickLauncher#373]
Pretty much what it says. I was trying to login using the automatic login mode and the launcher kept saying I should check my mail because of security password, even though my password was incorrect. I needed to edit the launching JSON manually to re-open the launcher window.

**Comment by goaaats** [comment]
Could you detail what exactly the issue is, step by step?

If you weren't aware, you can stop the launcher from doing an Autologin by holding shift - it should have told you when enabling Autologin and when starting the launcher.


In master, Autologin will be disabled automatically when login fails.

Thank you!

**Comment by AshenPheonix** [comment]
I tried to sign in. It failed because of a typo. The next time I tried to start the launcherr up, I got a message saying it failed because of security and an email would be incoming. I got no popup saying that I could hold shift, nor did the launcher pop up at all when I had the problem active.

**Comment by ascclemens** [comment]
If an error occurs during automatic login, the launcher could turn off automatic login and/or open the main window. Can't deny it would reduce the volume of people who need to be told to hold shift in the Discord. That would also resolve this issue. Has there been any discussion on doing so?

**Comment by reiichi001** [comment]
Coming soon in the next XL release.
https://github.com/goatcorp/FFXIVQuickLauncher/pull/348
