### ISSUE TITLE
Dalamud no longer works (load)

### ISSUE THREAD

**Issue by Dyr-Fenrir** [goatcorp/FFXIVQuickLauncher#375]
**Describe the bug here:**
Example: ``I can't play Galaga in the FFXIV Launcher as expected``

Dalamud stopped loading in-game recently, I do not remember when it broke as I am spamming Palace of the Dead at the moment and did not pay attention, could have occured with the last Windows update or game update.

**Steps to reproduce the bug:**
Example:
```
1. Click on Settings
2. Click on Auto-Launcher
3. Input the Konami code
4. Nothing happens :(
```

I start the game with XIVLauncher.exe.
After being logged-in, I do not see the Dalamud version echo in the game chat and the commands /xlplugins and /xlsettings do not work.

**Expected behavior**
Example: ``I expected the game to start when I put in the Konami code``

Normally, I would get a message in-game when I log-in stating that Dalamud was loaded and I would be able to use the commands stated above.

**Screenshots**
Example:
![Super cool screenshot](https://i.imgur.com/y99ALui.png)

Nothing relevant (I did provide the dalamud.txt log file for troublehooting though.

**Other information (*please* complete the following information):**
  Operating System: Windows 10 Pro (Version 20H2 - build 19042.789)
  XIVLauncher version: 5.2.1
  Launching as admin?: No
  Using Steam?: No
  Addons/Plugins enabled: Item Search Plugin 1.7.3.2, Market board 0.3.0.3 (X), Sonar 0.1.2.2

**Additional information**

Apparently a path seems to be missing?

See attachment:
[dalamud.txt](https://github.com/goatcorp/FFXIVQuickLauncher/files/5938421/dalamud.txt)

May someone help me out with this issue please?

Thank you for your time and help, it is greatly appreciated.

**Comment by Caraxi** [comment]
You seem to have enabled dalamud testing.

1. Close the game and xivlauncher if open.
2. Go to `%appdata%\xivlauncher\` and open `dalamudConfig.json` in your text editor of choice. 
3. Change the value of `DoDalamudTest` to `false`.

**Comment by Dyr-Fenrir** [comment]
Greetings,

Everything is working now, I had this option set to true for a while though (I do not remember exactly why). I changed it as requested and everything is working correctly.

Thank you again for your help.
