### ISSUE TITLE
Closing the patcher downloader leaves launcher still downloading in the background

### ISSUE THREAD

**Issue by S10MC2015** [goatcorp/FFXIVQuickLauncher#377]
**Describe the bug here:**
Closing the patcher downloader leaves launcher still downloading in the background.
It also has 2 processes in the background.

**Steps to reproduce the bug:**
Open launcher and get it to start downloading files. 
Alt f4 the window

**Expected behavior**
The whole program should close.

**Screenshots**
![image](https://user-images.githubusercontent.com/30575036/107380850-2aeb0600-6ae6-11eb-861b-b094cf5da8da.png)
![image](https://user-images.githubusercontent.com/30575036/107380951-3dfdd600-6ae6-11eb-82e4-c78eb6f9bcd6.png)

**Other information (*please* complete the following information):**
  Operating System: Win 10 2004
  XIVLauncher version: 5.2.1.0
  Launching as admin?: Yes
  Using Steam?: No
  Addons/Plugins enabled: No

**Additional information**
A proposed fix is to have a icon for the launcher in the tray showing that the program is minimised or something and having a right-click context menu option to close the launcher instead of running in the background.

Sorry if I am not too clear.

**Comment by goaaats** [comment]
This should be fixed now. We will probably add proper download cancelling soon
