### ISSUE TITLE
Unexpected error crash -- KERNALBASE.dll+43b29

### ISSUE THREAD

**Issue by Tyrlia** [goatcorp/FFXIVQuickLauncher#379]
Launching XIV through the Quicklauncher causes a .dll error to pop up:

![Error Popup](https://cdn.discordapp.com/attachments/723720052523794493/808891084041617408/ffxiv_dx11_cZrzHNt3jo.png)

Open XIV launcher normally / as administrator.
Type in log in information.
XIV launches.
2-3 Seconds pass.
.dll error which forces XIV to quit.

I do not have this error with the SE launcher.

Windows 10 Home
Steam: Yes

Chat Bubbles 1.2.1.1
Discord Rich Presence 1.5.0.2
Peeping Tom 1.5.8
Penny Pincher 1.1.0.1
PingPlugin 1.11.0.0
Window Title Changer 1.0.0.0

This error happened when I updated XIVLauncher to v5.2.4.0

**Comment by Caraxi** [comment]
Please remove PingPlugin until it is updated. It has an issue with the latest version of Dalamud

**Comment by Tyrlia** [comment]
Thankye, you're a lifesaver
