### ISSUE TITLE
Can't install Launcher after antivirus removed original files

### ISSUE THREAD

**Issue by Prinastripes** [goatcorp/FFXIVQuickLauncher#383]
**Describe the bug here:**
I've had some issues with bitdefender recently, in all its wisdom, deleting various files from installations. I tried to restore all the files it quarantined, but to no avail, so I decided I should do a fresh install. 

I disabled bitdefender, and attempted to reinstall using setup.exe, which gives an error, and a log file:
[SquirrelSetup.log](https://github.com/goatcorp/FFXIVQuickLauncher/files/5961391/SquirrelSetup.log)

**Expected behavior**
I expected the setup.exe to reinstall the launcher. 

This is the window that pops up after running the file as administrator with my antivirus off.
![Screenshot 2021-02-10 153557](https://user-images.githubusercontent.com/78879413/107568917-af588a00-6bb5-11eb-92e5-47c38b6f6c76.png)

**Other information (*please* complete the following information):**
  Operating System: Windows 10, up to date.
  XIVLauncher version: I guess it was up to date? I last used it with working plugins sometime yesterday.
  Launching as admin?: No.
  Using Steam?: Not for FFXIV. 
  Addons/Plugins enabled: I had Discord Rich Presence, the ping plugin, and fps counter plugin. 

**Additional information**
I checked the SE XIV launcher, and it runs as expected. If it would be better I do have a discord account as well.

**Comment by goaaats** [comment]
Sorry, we can't help with this. Try adding exclusions for the following paths to BitDefender:

 - %localappdata%\XIVLauncher
 - %localappdata%\goatsoft
 - %appdata%\XIVLauncher

**Comment by Prinastripes** [comment]
I've done that I'm just confused as to why the setup still doesnt have access to those files? I have no antivirus enabled, and I'm running the program as administrator.

**Comment by Prinastripes** [comment]
Ok I know this is closed so I'm sorry if you get notified of updates on this, but I fixed it by doing an advanced boot of windows 10, disabling early launch malware protection, then ran as administrator. I dont know why bitdefender is still allowed to block programs after being disabled, but this worked at least.
