### ISSUE TITLE
XIVLauncher not working, even after restart

### ISSUE THREAD

**Issue by afiqos4253** [goatcorp/FFXIVQuickLauncher#385]
Started up my XIVLauncher as per usual, and it hangs after launching FFXIV on a black screen and Windows will say it has stopped running, the normal launcher works, only XIVLauncher doesn't. Sorry I'm not sure what details are required.

Below is the error message received:

System.Exception: Game exited prematurely
   at XIVLauncher.Game.Launcher.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments) in G:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Launcher.cs:line 257
Version: 5.2.5.0
Git Hash: 61cd108
Context: XG LaunchGame
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

Addons: []

**Comment by Avenrer** [comment]
Exactly the same issue since yday.

**Comment by Carighan** [comment]
Started getting this as of this morning, too.

```
System.Exception: Game exited prematurely
   at XIVLauncher.Game.Launcher.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments) in G:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Launcher.cs:line 259
Version: 5.3.7.0
Git Hash: e4f8d3a
Context: XG LaunchGame
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: E:\SteamLibrary\steamapps\common\FINAL FANTASY XIV Online


Addons: []
```

**Comment by goaaats** [comment]
Hi, this might be related to your antivirus. Please [check out our FAQ](https://goatcorp.github.io/faq) or join our Discord server for help.
If you think this is a real bug/issue, please submit another report with more information([check the templates](https://github.com/goatcorp/FFXIVQuickLauncher/issues/new/choose)).

**Comment by Prothtoth** [comment]
Hello, I've been experiencing this same issue for a while now. However, I'm not getting any errors or feedback from the game. XIVLauncher launches normally, and so does the game, but it gets stuck on a black screen. I can press the close button ("X") and get the "Exit the game?" prompt, but that's all I can do.

I can still move my mouse, access Dalamud settings, and so on, but the "Square Enix" intro never appears, and I can't reach the main menu. This isn't the first time I've encountered this issue—sometimes it goes away on its own, and other times it persists for months. The last time I had this problem, I was using my old PC. When I switched to a new one, the issue disappeared—until now.

I've already checked every FAQ article and followed the antivirus steps, but the problem still persists. Please help.

**Comment by tommadness** [comment]
Please hold shift, start XIVLauncher with shift still held down to disable auto login, right click the "Login" button, and select "Start w/o Custom Repo Plugins". Does the issue still occur when you start the game this way?

**Comment by Prothtoth** [comment]
> Please hold shift, start XIVLauncher with shift still held down to disable auto login, right click the "Login" button, and select "Start w/o Custom Repo Plugins". Does the issue still occur when you start the game this way?

I don't have auto login enabled, and yes it does start the game that way, but I wish to play with my plugins, which creates this problem.

**Comment by tommadness** [comment]
Then your issue is caused by a custom repo plugin. Those are the ones with the yellow exclamation point that don't show up until you put a special link into the Experimental Custom Plugin Repositories section of /xlsettings.

Custom repo plugins are not vetted by the Dalamud team. There are several warnings when you first install them that we can not provide support for any issues they cause.

Your issue is _probably_ caused by Penumbra. Seek out their support channels for further assistance.
