### ISSUE TITLE
Game closes right after launch

### ISSUE THREAD

**Issue by amthrowaway** [goatcorp/FFXIVQuickLauncher#386]
**Issue:**
After opening the XIVLauncher as normal, the game starts up but around the point of it showing the SQUARE ENIX logo, it just closes again, every single time. Even a restart did not sort things out unfortunately. The normal launcher works as intended.
This only started happening today, yesterday (around exactly 24ish hours ago) it was just fine. No error pop-up whatsoever.

Edit: I did check with my virus protection and XIVLauncher does have full permissions.

**Other information:**
  Operating System: Win 10
  XIVLauncher version: v5.2.8.0
  Launching as admin?: yes
  Using Steam?: no
  Addons/Plugins enabled: bdth

**Comment by Aireil** [comment]
Try deleting the folder %appdata%\XIVLauncher\dalamudAssets and restart.

**Comment by amthrowaway** [comment]
I managed to make it work again with two reinstalls and a system recovery and that did the trick, thank you anyway :) if I stumble upon this problem again I'll make sure to try that!
