### ISSUE TITLE
Market Board Hover refreshes early on Supply Missions List

### ISSUE THREAD

**Issue by TsutetoDracman** [goatcorp/FFXIVQuickLauncher#397]
**Describe the bug here:**
When using the Marketboard plugin, the "Watch for hovered item" doesn't work fully on the Supply Missions listings. Did confirm it does work correctly on things like items in my inventory, equipped, and armoury chest. It loads halfway through on the item I've hovered in the supply missions list, and then refreshes like it just hovered over the next thing.

**Steps to reproduce the bug:**
```
1. Open up Timers list (ctrl+U personally)
2. Click "Next Mission Allowance" to pull up supplies list
3. Hover over an item
4. Watch the timer repeats again and again and again (the Energizer bunny would be proud)
```

**Expected behavior**
Shouldn't be repeating like that. Should treat like other items and fully load after 1 second

**Screenshots**
Sorry, can't easily do a screenshot of something that should be motion. I could ultimately pull a small video if needed?

**Other information (*please* complete the following information):**
  Operating System: Windows 10
  XIVLauncher version: 5.3.7.0
  Launching as admin?: No
  Using Steam?: Yes
  Addons/Plugins enabled:
```
-GatherBuddy (1.3.0.0)
-Globetrotter (1.1.2)
-Market board (0.3.0.8)
-Teleporter (1.0.1.7)
-XIV Combo (1.0.3.8)
```

**Additional information**
Did try with both a wired and wireless Razer mouse. Same thing.

**Comment by reiichi001** [comment]
Please submit plugin issues on the individual plugin repos. This is not an xivlauncher program issue.

If you think this may be caused by a bug in Dalamud, then you could try submitting it there.

**Comment by TsutetoDracman** [comment]
Was not aware of that, my apologies. I'll find their page and ask there.
