### ISSUE TITLE
No Longer Launching 

### ISSUE THREAD

**Issue by sangoku116** [goatcorp/FFXIVQuickLauncher#398]
**Describe the bug here:**
XIV Launcher no longer launching.

**Steps to reproduce the bug:**
Example:
```
1. Run the Script to Launch XIVLauncher
```

**Expected behaviour**
It launches.

**Screenshots**
![d71da04208ad4971c1be33c7be53683f](https://user-images.githubusercontent.com/18174977/110191479-a2b30480-7df6-11eb-9147-00511f7f9361.png)

**Other information (*please* complete the following information):**
  Operating System: Arch Linux
  XIVLauncher version: 5.3.0
  Launching as admin?: N/A
  Using Steam?: Yes
  Addons/Plugins enabled:

**Additional information**
It was working just fine Sunday. 

`esync: up and running.
WARNING: radv is not a conformant vulkan implementation, testing use only.
wine: Unhandled page fault on execute access to 0000000000000000 at address 0000000000000000 (thread 0038), starting debugger...
Unhandled exception: page fault on execute access to 0x00000000 in 64-bit code (0x0000000000000000).
Register dump:
 rip:0000000000000000 rsp:000000001cdbea98 rbp:00007fc4d008ecf0 eflags:00010246 (  R- --  I  Z- -P- )
 rax:0000000000000000 rbx:00007fc4d026f720 rcx:0000000000000000 rdx:00007fc4d026f680
 rsi:000000001cdbeac0 rdi:00007fc4d01508e8  r8:00007fc4d026f680  r9:000000001cdbe570 r10:00007fc4e6195fc0
 r11:0000000000000000 r12:00007fc4d026f6c0 r13:0000000000000000 r14:00007fc4d026f730 r15:00007fc4d026f6d0
Stack dump:
0x000000001cdbea98:  00007fc4e44b319b 000000003b9e0620
0x000000001cdbeaa8:  0000000000000000 0000000000000000
0x000000001cdbeab8:  0000000000000000 000000003b9bb079
0x000000001cdbeac8:  000000001cdbeaa0 0000000000000000
0x000000001cdbead8:  0000000000000000 0000000000000000
0x000000001cdbeae8:  0000000000000000 0000000000000000
0x000000001cdbeaf8:  0000000000000000 0000000000000000
0x000000001cdbeb08:  0000000000000000 0000000000000000
0x000000001cdbeb18:  0000000000000000 0000000000000000
0x000000001cdbeb28:  0000000000000000 0000000000000000
0x000000001cdbeb38:  0000000000000000 0000000000000000
0x000000001cdbeb48:  0000000000000000 0000000000000000
Backtrace:
=>0 0x0000000000000000 (0x00007fc4d008ecf0)
0x0000000000000000: -- no code accessible --
Modules:
Module	Address					Debug info	Name (164 modules)
PE	          340000-          356000	Deferred        vcruntime140_clr0400
PE	          3c0000-          3c8000	Deferred        api-ms-win-core-winrt-string-l1-1-0
PE	          400000-          722000	Deferred        xivlauncher
PE	          d90000-         1857000	Deferred        clr
PE	         1860000-         191d000	Deferred        ucrtbase_clr0400
PE	        1a540000-        1a5da000	Deferred        msvcp140_clr0400
PE	        1a610000-        1a626000	Deferred        nlssorting
PE	        1a720000-        1b579000	Deferred        presentationcore.ni
PE	        1b580000-        1b777000	Deferred        wpfgfx_v0400
PE	        1b780000-        1b89f000	Deferred        presentationnative_v0400
PE	        1b8a0000-        1b9ee000	Deferred        clrjit
PE	        1ba50000-        1ba63000	Deferred        aclui
PE	        1bed0000-        1c013000	Deferred        comctl32
PE	        1c170000-        1c213000	Deferred        system.net.http.ni
PE	        1c860000-        1cbc9000	Deferred        system.data
PE	        1cee0000-        1cf77000	Deferred        openvr_api_dxvk
PE	        61340000-        61347000	Deferred        api-ms-win-core-localization-obsolete-l1-2-0
PE	        62240000-        624c7000	Deferred        d3d9
PE	        62540000-        62548000	Deferred        api-ms-win-core-xstate-l2-1-0
PE	        62600000-        6263c000	Deferred        usp10
PE	        638c0000-        638ce000	Deferred        dwmapi
PE	        64940000-        64959000	Deferred        shcore
PE	        64d40000-        64d4f000	Deferred        vulkan-1
PE	        65000000-        65143000	Deferred        ole32
PE	        65780000-        6578e000	Deferred        version
PE	        66500000-        66532000	Deferred        rsaenh
PE	        66600000-        66607000	Deferred        api-ms-win-core-datetime-l1-1-1
PE	        66780000-        66787000	Deferred        api-ms-win-core-string-l1-1-0
PE	        67600000-        67626000	Deferred        combase
PE	        68a40000-        68a96000	Deferred        shlwapi
PE	        69c80000-        69caa000	Deferred        propsys
PE	        6a100000-        6a231000	Deferred        oleaut32
PE	        6a700000-        6a77e000	Deferred        setupapi
PE	        6b2c0000-        6b340000	Deferred        wininet
PE	        6b880000-        6b887000	Deferred        api-ms-win-core-fibers-l1-1-1
PE	        6bec0000-        6bed9000	Deferred        imm32
PE	        6c100000-        6c108000	Deferred        api-ms-win-appmodel-runtime-l1-1-2
PE	        6d9c0000-        6d9df000	Deferred        mpr
PE	        6e340000-        6e348000	Deferred        api-ms-win-core-synch-l1-2-0
PE	        6e6c0000-        6e6c8000	Deferred        api-ms-win-core-localization-l1-2-1
PE	        6fbc0000-        6fc44000	Deferred        rpcrt4
PE	        6ff80000-        6ff88000	Deferred        api-ms-win-core-quirks-l1-1-0
PE	        7b000000-        7b0bc000	Deferred        kernelbase
ELF	        7b400000-        7b67c000	Deferred        kernel32<elf>
  \-PE	        7b410000-        7b67c000	\               kernel32
ELF	        7bc00000-        7bdad000	Deferred        ntdll<elf>
  \-PE	        7bc20000-        7bdad000	\               ntdll
ELF	        7bfff000-        7c004000	Deferred        <wine-loader>
PE	       180000000-       1800a9000	Deferred        mscoreei
PE	       180370000-       180ce0000	Deferred        system.data.ni
PE	     6427ee50000-     6427eebf000	Deferred        mscoree
PE	     64422540000-     64422884000	Deferred        system.runtime.serialization.ni
PE	     6442cc20000-     6442e32d000	Deferred        presentationframework.ni
PE	     644301a0000-     64430417000	Deferred        system.xaml.ni
PE	     644309c0000-     64430ecf000	Deferred        windowsbase.ni
PE	     644406e0000-     64440813000	Deferred        system.configuration.ni
PE	     64443400000-     64443e75000	Deferred        system.core.ni
PE	     64443ec0000-     64443f11000	Deferred        system.numerics.ni
PE	     644442c0000-     64444b6b000	Deferred        system.xml.ni
PE	     64474a80000-     644756ed000	Deferred        system.ni
PE	     64478000000-     644795e3000	Deferred        mscorlib.ni
ELF	    7fc4c55bc000-    7fc4c5edb000	Deferred        libvulkan_intel.so
ELF	    7fc4c5edb000-    7fc4c65a1000	Deferred        libvulkan_radeon.so
ELF	    7fc4c65a1000-    7fc4cc000000	Deferred        libllvm-11.so
ELF	    7fc4dc01b000-    7fc4dc035000	Deferred        libelf.so.1
ELF	    7fc4dc035000-    7fc4dc041000	Deferred        libdrm_amdgpu.so.1
ELF	    7fc4dc041000-    7fc4ddb82000	Deferred        libicudata.so.68
ELF	    7fc4ddb82000-    7fc4ddd71000	Deferred        libicuuc.so.68
ELF	    7fc4ddd71000-    7fc4ddd99000	Deferred        liblzma.so.5
ELF	    7fc4ddd99000-    7fc4ddf07000	Deferred        libxml2.so.2
ELF	    7fc4ddf07000-    7fc4ddf78000	Deferred        libncursesw.so.6
ELF	    7fc4ddf78000-    7fc4ddfb3000	Deferred        libedit.so.0
ELF	    7fc4ddfb3000-    7fc4ddfc5000	Deferred        libxcb-randr.so.0
ELF	    7fc4ddfc5000-    7fc4ddfd7000	Deferred        libwayland-client.so.0
ELF	    7fc4ddfd7000-    7fc4ddff1000	Deferred        libunwind.so.8
ELF	    7fc4ddff1000-    7fc4de0cc000	Deferred        libzstd.so.1
ELF	    7fc4de0cc000-    7fc4de752000	Deferred        libvulkan_lvp.so
ELF	    7fc4de9ea000-    7fc4ded2e000	Deferred        vrclient_x64<elf>
ELF	    7fc4ded2e000-    7fc4ded8e000	Deferred        libvulkan.so.1
ELF	    7fc4ded8e000-    7fc4dedea000	Deferred        winevulkan<elf>
  \-PE	    7fc4deda0000-    7fc4dedea000	\               winevulkan
ELF	    7fc4dedea000-    7fc4deed4000	Deferred        msvcrt<elf>
  \-PE	    7fc4dee10000-    7fc4deed4000	\               msvcrt
ELF	    7fc4deed4000-    7fc4defe3000	Deferred        windowscodecs<elf>
  \-PE	    7fc4deef0000-    7fc4defe3000	\               windowscodecs
ELF	    7fc4defe3000-    7fc4df025000	Deferred        ws2_32<elf>
  \-PE	    7fc4deff0000-    7fc4df025000	\               ws2_32
ELF	    7fc4df025000-    7fc4df059000	Deferred        iphlpapi<elf>
  \-PE	    7fc4df030000-    7fc4df059000	\               iphlpapi
ELF	    7fc4df059000-    7fc4df09d000	Deferred        uxtheme<elf>
  \-PE	    7fc4df060000-    7fc4df09d000	\               uxtheme
ELF	    7fc4df09d000-    7fc4dfb0e000	Deferred        shell32<elf>
  \-PE	    7fc4df0c0000-    7fc4dfb0e000	\               shell32
ELF	    7fc4dfb0e000-    7fc4dfbb5000	Deferred        dwrite<elf>
  \-PE	    7fc4dfb20000-    7fc4dfbb5000	\               dwrite
ELF	    7fc4dfbb5000-    7fc4dfbdc000	Deferred        libgpg-error.so.0
ELF	    7fc4dfbdc000-    7fc4dfc60000	Deferred        libgcrypt.so.11
ELF	    7fc4dfc60000-    7fc4dfd00000	Deferred        libgmp.so.10
ELF	    7fc4dfd00000-    7fc4dfd49000	Deferred        libhogweed.so.6
ELF	    7fc4dfd49000-    7fc4dfecb000	Deferred        libunistring.so.2
ELF	    7fc4dfecb000-    7fc4e0000000	Deferred        libp11-kit.so.0
ELF	    7fc4e4004000-    7fc4e400e000	Deferred        libxcb-sync.so.1
ELF	    7fc4e400e000-    7fc4e4023000	Deferred        libdrm.so.2
ELF	    7fc4e4023000-    7fc4e406b000	Deferred        libnettle.so.8
ELF	    7fc4e406b000-    7fc4e426e000	Deferred        libgnutls.so.30
ELF	    7fc4e426e000-    7fc4e4376000	Deferred        crypt32<elf>
  \-PE	    7fc4e4280000-    7fc4e4376000	\               crypt32
ELF	    7fc4e446d000-    7fc4e4472000	Deferred        libxshmfence.so.1
ELF	    7fc4e4472000-    7fc4e4488000	Deferred        libtasn1.so.6
ELF	    7fc4e4488000-    7fc4e44a9000	Deferred        libidn2.so.0
ELF	    7fc4e44b1000-    7fc4e44ba000	Deferred        libvklayer_mesa_device_select.so
ELF	    7fc4e44ba000-    7fc4e44d7000	Deferred        steamoverlayvulkanlayer.so
ELF	    7fc4e44d7000-    7fc4e4500000	Deferred        bcrypt<elf>
  \-PE	    7fc4e44e0000-    7fc4e4500000	\               bcrypt
ELF	    7fc4e45a7000-    7fc4e45b3000	Deferred        libffi.so.7
ELF	    7fc4e45b3000-    7fc4e45bc000	Deferred        libxfixes.so.3
ELF	    7fc4e45bc000-    7fc4e45c8000	Deferred        libxcursor.so.1
ELF	    7fc4e45e4000-    7fc4e4613000	Deferred        libexpat.so.1
ELF	    7fc4e4613000-    7fc4e465e000	Deferred        libfontconfig.so.1
ELF	    7fc4e465e000-    7fc4e46d0000	Deferred        libpcre.so.1
ELF	    7fc4e46d0000-    7fc4e4805000	Deferred        libglib-2.0.so.0
ELF	    7fc4e4805000-    7fc4e482a000	Deferred        libgraphite2.so.3
ELF	    7fc4e482a000-    7fc4e48fe000	Deferred        libharfbuzz.so.0
ELF	    7fc4e48fe000-    7fc4e4918000	Deferred        libz.so.1
ELF	    7fc4e4918000-    7fc4e494f000	Deferred        libpng16.so.16
ELF	    7fc4e494f000-    7fc4e4962000	Deferred        libbz2.so.1.0
ELF	    7fc4e4962000-    7fc4e4a36000	Deferred        libfreetype.so.6
ELF	    7fc4e4a36000-    7fc4e4a49000	Deferred        libxi.so.6
ELF	    7fc4e4a49000-    7fc4e4a4e000	Deferred        libxcomposite.so.1
ELF	    7fc4e4a4e000-    7fc4e4a5b000	Deferred        libxrandr.so.2
ELF	    7fc4e4a5b000-    7fc4e4a68000	Deferred        libxrender.so.1
ELF	    7fc4e4a68000-    7fc4e4a6f000	Deferred        libxxf86vm.so.1
ELF	    7fc4e4a6f000-    7fc4e4a74000	Deferred        libxinerama.so.1
ELF	    7fc4e4a74000-    7fc4e4a7c000	Deferred        libxdmcp.so.6
ELF	    7fc4e4a7c000-    7fc4e4aa6000	Deferred        libxcb.so.1
ELF	    7fc4e4aa6000-    7fc4e4be7000	Deferred        libx11.so.6
ELF	    7fc4e4be7000-    7fc4e4bfc000	Deferred        libxext.so.6
ELF	    7fc4e4bff000-    7fc4e4c04000	Deferred        libxcb-present.so.0
ELF	    7fc4e4c0a000-    7fc4e4c10000	Deferred        libxcb-dri3.so.0
ELF	    7fc4e4c25000-    7fc4e4c2a000	Deferred        libx11-xcb.so.1
ELF	    7fc4e4c2a000-    7fc4e4cf5000	Deferred        winex11<elf>
  \-PE	    7fc4e4c40000-    7fc4e4cf5000	\               winex11
ELF	    7fc4e4df5000-    7fc4e5083000	Deferred        user32<elf>
  \-PE	    7fc4e4e20000-    7fc4e5083000	\               user32
ELF	    7fc4e5083000-    7fc4e51be000	Deferred        ucrtbase<elf>
  \-PE	    7fc4e50b0000-    7fc4e51be000	\               ucrtbase
ELF	    7fc4e51be000-    7fc4e536d000	Deferred        gdi32<elf>
  \-PE	    7fc4e51d0000-    7fc4e536d000	\               gdi32
ELF	    7fc4e546d000-    7fc4e54b0000	Deferred        sechost<elf>
  \-PE	    7fc4e5470000-    7fc4e54b0000	\               sechost
ELF	    7fc4e54b0000-    7fc4e5529000	Deferred        advapi32<elf>
  \-PE	    7fc4e54c0000-    7fc4e5529000	\               advapi32
ELF	    7fc4e5c89000-    7fc4e5c9d000	Deferred        libnss_files.so.2
ELF	    7fc4e5e9d000-    7fc4e5eb7000	Deferred        libgcc_s.so.1
ELF	    7fc4e5eb7000-    7fc4e5ffc000	Deferred        libm.so.6
ELF	    7fc4e5ffc000-    7fc4e6007000	Deferred        librt.so.1
ELF	    7fc4e6009000-    7fc4e6010000	Deferred        libdl.so.2
ELF	    7fc4e6010000-    7fc4e61dd000	Deferred        libc.so.6
ELF	    7fc4e61dd000-    7fc4e61fe000	Deferred        libpthread.so.0
ELF	    7fc4e6200000-    7fc4e6205000	Deferred        libxau.so.6
ELF	    7fc4e6218000-    7fc4e622c000	Deferred        wow64cpu<elf>
  \-PE	    7fc4e6220000-    7fc4e622c000	\               wow64cpu
ELF	    7fc4e622c000-    7fc4e65bd000	Export          libwine.so.1
ELF	    7fc4e65bf000-    7fc4e65f2000	Deferred        ld-linux-x86-64.so.2
Threads:
process  tid      prio (all id:s are in hex)
00000008 XIVLauncher.exe
	["C:\users\steamuser\Local Settings\Application Data\XIVLauncher\XIVLauncher.exe"]
	00000009    0
0000000e services.exe
	[C:\windows\system32\services.exe]
	0000002a    0
	00000025    0
	00000020    0
	0000001a    0
	00000015    0
	00000014    0
	00000013    0
	00000010    0
	0000000f    0
00000011 svchost.exe
	[C:\windows\system32\svchost.exe -k LocalServiceNetworkRestricted]
	00000017    0
	00000016    0
	00000012    0
00000018 winedevice.exe
	[C:\windows\system32\winedevice.exe]
	0000001d    0
	0000001c    0
	0000001b    0
	00000019    0
0000001e plugplay.exe
	[C:\windows\system32\plugplay.exe]
	00000022    0
	00000021    0
	0000001f    0
00000023 winedevice.exe
	[C:\windows\system32\winedevice.exe]
	00000029    0
	00000028    0
	00000027    0
	00000026    0
	00000024    0
0000002b explorer.exe
	[C:\windows\system32\explorer.exe /desktop]
	0000002f    0
	0000002e    0
	0000002d    0
	0000002c    0
00000030 (D) C:\users\steamuser\Local Settings\Application Data\XIVLauncher\app-5.3.0\XIVLauncher.exe
	["C:\users\steamuser\Local Settings\Application Data\XIVLauncher\app-5.3.0\XIVLauncher.exe" ]
	00000038    0 <==
	00000037    0
	00000036    0
	00000035    0
	00000034    0
	00000033    2
	00000032    0
	00000031    0
System information:
    Platform: x86_64
    Version: Windows 7
`

**Comment by goaaats** [comment]
We can't help with this since we're not officially supporting Linux and custom wine setups yet.

Make sure you run the newest XIVLauncher version(you're not) and try the Lutris script, it's confirmed to work with the newest XIVLauncher version. It uses wine 5.7-11 esync.
