### ISSUE TITLE
Setup german text cut-off

### ISSUE THREAD

**Issue by CodeQo** [goatcorp/FFXIVQuickLauncher#399]
Fresh 5.3.7 installation, when chosing the game directory path, a lot of text is cutoff from the german localization. There is no way to workaround it, because the setup does not ask for a language first.

**Comment by goaaats** [comment]
Fixed in https://github.com/goatcorp/FFXIVQuickLauncher/commit/b83895ddf8eaea2b99ca30de0177e7cb3b13a968
