### ISSUE TITLE
Migrate FAQ from Discord to GitHub

### ISSUE THREAD

**Issue by goaaats** [goatcorp/FFXIVQuickLauncher#406]
We should migrate the known issues/FAQ channel from Discord to GitHub, either the wiki or a pages setup.

Discord is pretty inaccessible for this.

**Comment by reiichi001** [comment]
Based on how user-unfriendly syncing a github wiki is, I think we'd benefit from either having it be a normal repo or using another medium to hold FAQs on the internet.

While having them in-discord is handy in terms of posts, we could always make FAQs as modules for Franzbot or I can just link to wherever we end up storing the official versions

**Comment by AmenneHolelane** [comment]
I do like the idea of phasing out Discord purely for the ease of editing FAQs etc (what if Franz loses access to his discord etc). why not make it into a FAQ.txt or .md or w/e github uses

**Comment by reiichi001** [comment]
That's exactly my thoughts. We could just add a docs folder to XIVLauncher, Dalamud, and/or a separate Goatsoft/Documentation repo and put things there. Then when everything is copied over, I can just relink Franzbot to those

**Comment by Aida-Enna** [comment]
You don't sync github wikis, though. They are seperate for each repo/fork.
We use it at https://github.com/Arks-Layer/PSO2ENPatchCSV/wiki, but you can
see it doesn't exist on my personal fork of it,
https://github.com/Aida-Enna/PSO2ENPatchCSV .

**Comment by AmenneHolelane** [comment]
you can sync it through git but it's a huge pain in the ass and i don't want to do it again if i don't have to

**Comment by AmenneHolelane** [comment]
for me to make changes i need to clone it locally, edit the files, fork the repo, upload wiki to my fork, have someone with write permissions clone MY wiki locally, then push to master

**Comment by Aida-Enna** [comment]
Why would you sync it through git? It's already saved on the repo itself.

**Comment by reiichi001** [comment]
> You don't sync github wikis, though. They are seperate for each repo/fork. 

Yes, which is why I said a normal repo and not a wiki. You can technically sync them and I have access to Goatsoft/Dalamud plugins to do that, but since they're not forkable, I wouldn't want to use the Github wiki feature for this. 

> Why would you sync it through git? It's already saved on the repo itself.

You can't easily upload images for local storage without using git.

----

Instead, I'd rather make a docs folder with markdown files or something, so we could have it be forkable, whether it's uncluded as part of XL, Dalamud, DalamudPLugins (depending on the FAQ) or in its own dedicated repo. ...since Github already displays markdown files that are opened

**Comment by AmenneHolelane** [comment]
yeah i was mainly speaking of the most recent experience of transitioning from puu.sh links to images saved. i'd imagine if it was just text file edits it would be much easier

**Comment by Aida-Enna** [comment]
It just seems like a vast overcomplication to give everyone the ability to clone and modify a wiki that, realistically, very likely only the four of us will work on aside from the occasional spelling fix.

As for images, you can upload them to the repo or imgur.

**Comment by goaaats** [comment]
I think I'll go for a separate repo, as that will allow me to do special access controls - I don't want to give write access to this repo to anyone but me.

**Comment by Aida-Enna** [comment]
Are you going to use github pages for it?

**Comment by goaaats** [comment]
I guess so - any reason why I shouldn't?

**Comment by Aida-Enna** [comment]
Nope, was gonna recommend it lol

**Comment by goaaats** [comment]
@reiichi001 here's the repo, I gave you access: https://github.com/goatcorp/faq

**Comment by goaaats** [comment]
We're pretty much done with this now actually, thanks a lot to everyone that helped!
