### ISSUE TITLE
FFXIVlauncher reset my settings

### ISSUE THREAD

**Issue by saero** [goatcorp/FFXIVQuickLauncher#408]
I booted up FFXIVlauncher today like any other day, and I found myself staring at FFXIV in windowed 720p with all the System settings reset. It even had me select a Data Center like it was the first time I was playing 14.

Thankfully, all my character settings (UI, etc) were completely fine (for now).

There's no other thing I can think of that reset all my system settings beside FFXIVlauncher; I don't turn off my PC, and nothing had changed since I left my PC before work and came back this evening. Has this been a thing ever before?

  Operating System: Windows 8.1
  XIVLauncher version: latest 
  Launching as admin?: No
  Using Steam?: No
  Addons/Plugins enabled: Just a few plugins, like the better countdown plugin and marketboard one along with RMT, thats it

**Additional information**
At this point Im really confused at how this happened. The only thing I noticed it could be is FFXIVlauncher because I see on github the files were updated in the last 4 hours.

**Comment by goaaats** [comment]
This isn't related to XIVLauncher - it's most likely a bug with the game. Check that you have enough drive space available and make regular backups - your settings are in ``My Documents\My Games\FINAL FANTASY XIV - A Realm Reborn``.

**Comment by saero** [comment]
Well, that's weird, because I do exactly what you suggest every few months just in case. I've played FFXIV for years and I've never encountered this error before, and I don't even update most of my software/Windows simply due to compatibility/stubbornness (except for more crucial things like drivers or the like).

I guess I'll close this, but I just wanted to mention this in case anyone else has this issue too.
