### ISSUE TITLE
Default multi-monitor mode to false due to framerate issues.

### ISSUE THREAD

**Issue by DarkDestry** [goatcorp/FFXIVQuickLauncher#413]
**What is your suggestion/feature request?**
Default multi-monitor mode to false.

**Describe how you'd like this to work**
Set multi-monitor mode to default false.

**Additional context**
With multi-monitor mode on, my framerate drops to 15 fps. It was defaulted to on during the last update. Much trial and error was required to identify the root cause. Disabling it returned to 50 FPS.

Monitor setup:
2x1080p
1x4k
1x720p

**Comment by goaaats** [comment]
Already is since shortly after the update, sorry for the trouble
