### ISSUE TITLE
"Please enter a password"

### ISSUE THREAD

**Issue by goaaats** [goatcorp/FFXIVQuickLauncher#415]
Confusing behavior when using auto-login with a saved account and removing the saved credentials in windows credential manager.

**Comment by Zyian** [comment]
If I'm getting this right:
1. Save credentials
2. Enable autologin
3. Delete credentials from Windows Credential Manager
4. Open Launcher
5. ????? <- Something broken here?

So this needs a validate that the credentials exist before attempting a login?

**Comment by goaaats** [comment]
I think the only thing we need to do is disable Auto-Login and open the main launcher window if the saved password is string.IsNullOrEmpty on Auto-Login

**Comment by goaaats** [comment]
Fixed
