### ISSUE TITLE
[opening the game]

### ISSUE THREAD

**Issue by hzozimo** [goatcorp/FFXIVQuickLauncher#417]
after I click to entry the game, it shows a big black windows that never loads the game

System.Exception: Game exited prematurely
   em XIVLauncher.Game.Launcher.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments) na G:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Game\Launcher.cs:linha 259
Version: 5.4.0.0
Git Hash: caa764d
Context: XG LaunchGame
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: Portuguese
Game path: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY XIV Online

Addons: []

**Comment by goaaats** [comment]
Hi, this might be related to your antivirus. Please check out our FAQ or join our Discord server for help.
If you think this is a real bug/issue, please submit another report with more information([check the templates](https://github.com/goatcorp/FFXIVQuickLauncher/issues/new/choose)).
