### ISSUE TITLE
Redownload assets on parse failure

### ISSUE THREAD

**Issue by lmcintyre** [goatcorp/FFXIVQuickLauncher#419]
At the moment, on asset.ver parse failure (AssetManager.cs:92), the launcher will completely ignore Dalamud. We should simply redownload the assets if an issue occurs when trying to check if we should... download the assets.

**Comment by goaaats** [comment]
assets.json AND the dalamud.zip also have hashes for all important files now, I just didn't get around to actually checking them in XL
