### ISSUE TITLE
Automatically type one-time password

### ISSUE THREAD

**Issue by yjywybb** [goatcorp/FFXIVQuickLauncher#428]
Since Square Enix start to allow users to use third-party OTP app based on 2FA-code such as Google Authenticator, is it possible to add a feature that tell the xivlauncher what my Secret Code of Square Enix Account's OTP is, so that I could get into the game without typing OTP?

**Comment by yjywybb** [comment]
I wrote a tool roughly, maybe you can check it.

https://github.com/yjywybb/FFXIV-OTP-Assistant

**Comment by goaaats** [comment]
Hey, we don't want to add this to XIVLauncher directly since it basically defeats the purpose of OTPs. We have the authenticator app and the macros "officially" which should work, and your tool works just as well I guess.

Thanks!
