### ISSUE TITLE
FFXIV Initialization completely bugged

### ISSUE THREAD

**Issue by dollthehaus** [goatcorp/FFXIVQuickLauncher#429]
System.OutOfMemoryException: Exceção do tipo 'System.OutOfMemoryException' foi acionada.
   em XIVLauncher.Addon.AddonManager.StopAddons()
   em XIVLauncher.Windows.MainWindow.<>c__DisplayClass18_0.<StartGameAndAddon>b__0() na G:\Sapphire\FFXIVQuickLauncher\XIVLauncher\Windows\MainWindow.xaml.cs:linha 721
   em System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   em System.Threading.ThreadHelper.ThreadStart()
Version: 5.4.0.0
Git Hash: caa764d
Context: Unhandled
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: Portuguese
Game path: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY XIV Online

Addons: []

**Comment by goaaats** [comment]
Please write a real issue report([check the templates](https://github.com/goatcorp/FFXIVQuickLauncher/issues/new/choose)) and try again. We need more info to help, sorry. You can also join our Discord server for help.
