### ISSUE TITLE
"Update without starting" launches game anyway

### ISSUE THREAD

**Issue by PrincessRTFM** [goatcorp/FFXIVQuickLauncher#440]
**Describe the bug here:**
Following the hotfix last night, I right-clicked the "log in" button and hit the "update without starting" command. I was required to input my 2fa code, and then the launcher began to patch my files. After it had finished, the game still launched.

**Steps to reproduce the bug:**
1. Ensure that a client update is waiting to be installed
2. Right click the log in button and use the option to update the game without launching it
3. Wait for the updates to finish
4. The game launches anyway

**Expected behavior**
When updating the game without launching, the game shouldn't launch afterward.

**Screenshots**
No applicable screenshots

**Other information (*please* complete the following information):**
  Operating System: windows 10 home, version 20H2, build 19042.985
  XIVLauncher version: v5.4.0.0
  Launching as admin?: no
  Using Steam?: no
  Addons/Plugins enabled: AdventurerInNeed, BDTHPlugin, BetterPartyFinder, BurntToast, ChatBubbles, ChatCoordinates, RichPresence, DeepDungeonDex, EasyEyes, ExpandedSearchInfo, FCNameColor, FPSPlugin, GatherBuddy, Globetrotter, GoodMemory, Housemate, HousingPos, ItemSearchPlugin, Macrology, MacroRecursion, MapLinker, MarketBoardPlugin, MiniCactpotSolver, MOAction, NeatNoter, NoSoliciting, orchestrion, PeepingTom, PingPlugin, PixelPerfect, PlayerTrack, PrefPro, PriceCheck, QoLBar, RemindMe, SimpleTweaksPlugin, SlideCast, SoundSetter, TabTab, TeleporterPlugin, TheGreatSeparator, Tourist, Visibility, WaymarkPresetPlugin, WOLdo, WondrousTailsSolver, XIVChat, XIVComboExpanded, YesAlready

**Additional information**
It may be worth noting that following these exact steps _without_ a pending game update results in a popup telling me that "an update check was executed and any pending updates were installed" _without_ launching the game. The game only launches when it shouldn't if there was an actual update.

**Comment by Zyian** [comment]
I believe this is caused by the false to not start the game is not passed in the case of patching, after finishing patching we immediately launch the game

https://github.com/goatcorp/FFXIVQuickLauncher/blob/master/XIVLauncher/Windows/MainWindow.xaml.cs#L491

**Comment by goaaats** [comment]
Fixed this in https://github.com/goatcorp/FFXIVQuickLauncher/commit/1aa64eb34d89dd4a99db4e2400c6514407b861ae
