### ISSUE TITLE
error on login

### ISSUE THREAD

**Issue by PaulineAngel** [goatcorp/FFXIVQuickLauncher#446]
System.ComponentModel.Win32Exception (0x80004005): O executável especificado não é um aplicativo válido para esta plataforma de SO.
   em System.Diagnostics.Process.StartWithShellExecuteEx(ProcessStartInfo startInfo)
   em XIVLauncher.Dalamud.DalamudLauncher.Run(DirectoryInfo gamePath, ClientLanguage language, Process gameProcess) na D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\XIVLauncher\Dalamud\DalamudLauncher.cs:linha 133
   em XIVLauncher.Addon.AddonManager.RunAddons(Process gameProcess, ILauncherSettingsV3 setting, List`1 addonEntries) na D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\XIVLauncher\Addon\AddonManager.cs:linha 42
   em System.Threading.Tasks.Task.Execute()
--- Fim do rastreamento de pilha do local anterior onde a exceção foi gerada ---
   em System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   em System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   em XIVLauncher.Windows.MainWindow.<StartGameAndAddon>d__19.MoveNext() na D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\XIVLauncher\Windows\MainWindow.xaml.cs:linha 715
Version: 5.5.3.0
Git Hash: 5.5.3-0-g5149e97
Context: Addons
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: Portuguese
Game path: D:\Jogos\Steam\steamapps\common\FINAL FANTASY XIV Online

Addons: []

**Comment by goaaats** [comment]
Please write a real bug report([check the templates](https://github.com/goatcorp/FFXIVQuickLauncher/issues/new/choose)) and try again. We need more information to help.
