### ISSUE TITLE
Crash of the launcher after configuring a profile image

### ISSUE THREAD

**Issue by Luna664** [goatcorp/FFXIVQuickLauncher#448]
**Describe the bug here:**
Crash of the launcher after configuring a profile image

**Steps to reproduce the bug:**
Example:
```
1. Click on Account Switcher
2. Click on Set profile picture
3. Add character information
4. Application crash :(
```

**Expected behavior**
I wanted to put a profile picture, but the launcher crashes right after.
It is possible to restart it, but when you go to the "Account Switcher" menu, the launcher doesn't respond and crashes again

**Other information (*please* complete the following information):**
  Operating System: Windows 10 64bit
  XIVLauncher version: v5.5.3.0 - 5.5.3-0-g5149e97 - 4.0.30319.42000
  Launching as admin?: No
  Using Steam?: No
  Addons/Plugins enabled: 
![ffxiv_dx11_fji8us72r8](https://user-images.githubusercontent.com/75101727/121653802-5d5d3d80-ca9d-11eb-8766-c91d305294e4.png)
![ffxiv_dx11_rZmjyoqH0X](https://user-images.githubusercontent.com/75101727/121653814-60582e00-ca9d-11eb-95b8-229a492a530a.png)

**Comment by goaaats** [comment]
Hey, I can't reproduce this - does this also happen for you if you choose another random character from Lodestone? Could you send a log file from %AppData%\XIVLauncher\output.log?

**Comment by Luna664** [comment]
Hello, I can't reproduce the bug at all, maybe it came from a problem with the lodestone?

In any case it works correctly now
