### ISSUE TITLE
When running setup.exe i get "Installing #0 56 gigs downloading at 5mb/s

### ISSUE THREAD

**Issue by Dystorshun** [goatcorp/FFXIVQuickLauncher#460]
When running setup.exe i get "Installing #0 56 gigs downloading at 5mb/s.  Any idea whats  going on here? Ive tried letting it run for a while and nothing changes.

**Comment by reiichi001** [comment]
Do you currently have a copy of FFXIV installed?

**Yes**
You've selected the wrong gamepath then, and XIVLauncher is trying to reinstall the entire game for you. 

See the FAQ entry here for more info. https://goatcorp.github.io/faq/xl_troubleshooting#q-where-can-i-find-my-ffxiv-installation

**No**
All FFXIV patches have to be installed in order. This usually means a collection of ~1.4GB initial patches (H2017 stuff). If you have for example `H2017.06.06.0000.0001b`, `H2017.06.06.0000.0001c`, and `H2017.06.06.0000.0001d` finished, but `H2017.06.06.0000.0001a` is still downloading, the others will have to wait until the patcher is ready for them. 

If the patcher itself is hanging and isn't waiting on an earlier patch, then you can kill the xivlauncher.exe process from the task manager. (If you see an xivpatcher.exe process, you should leave it alone as it will close on it's own).

**Comment by Dystorshun** [comment]
thanks for the input. Ill give this a go again and report back either way.

**Comment by reiichi001** [comment]
Hello! Is this resolved? 

We'll keep this issue open for ~3 days before closing it if there's no response.

**Comment by Zyian** [comment]
Closing due to no response
