### ISSUE TITLE
Launcher "Hangs" (Stops providing feedback) when writing to disk

### ISSUE THREAD

**Issue by Kio-td** [goatcorp/FFXIVQuickLauncher#462]
The program will provide no visual feedback when downloading patches when it's finished downloading and writing to disk. This has lead me to believe that the program has crashed multiple times, but instead, it's just writing, which means I more than likely corrupted a few archives by accident.

**Comment by goaaats** [comment]
This is supposed to be a thing, but it's not working correctly. I'll have another look, thanks for the heads-up.

**Comment by joncppl** [comment]
Similar issue, where the patch installer seizes up intermittently. In my case, it temporarily freezes my entire system. 
This was only noticeable to me when letting the launcher do the a fresh install of the game (all 50GB or w/e). 
I believe it also occurs with smaller patches, these just install much quicker so it's not that big of a deal in comparison.
