### ISSUE TITLE
Launcher doesn't respect separate drive for patch updates

### ISSUE THREAD

**Issue by Kio-td** [goatcorp/FFXIVQuickLauncher#463]
The launcher, when installing patches, will always use the C Drive, no matter where installed. Most of the installs that I do for friends are in separate game-exclusive drives, with a filled C Drive struggling to contain the patches.

It'd be a treat to have the ability or have an automatic selection, for the downloader to respect the separate drive.

**Comment by goaaats** [comment]
You can set the location patches are downloaded to in the settings under Patching.

**Comment by Kio-td** [comment]
Could there be a possibility of following the drive that the user set their game location too?
