### ISSUE TITLE
Kill after game closes does not work

### ISSUE THREAD

**Issue by Fanatiikon** [goatcorp/FFXIVQuickLauncher#465]
Kill after game closes does not work when using the auto-launch feature.
Example: I have added ACT to auto-launch but it does not close after the game is closed:

**Steps to reproduce the bug:**
```
1. Click on Settings
2. Click on Auto-Launc
3. Add ACT
4. Boot the Title
5. Quit the Title
6. Observe ACT remains open
```

**Expected behavior**
ACT closes once the game is closed if "Kill after game closes" is checked

**Screenshots**
![image](https://user-images.githubusercontent.com/76494177/123817691-08c11b80-d901-11eb-90a7-3367780d98b0.png)

**Comment by Coul33t** [comment]
Same problem here, with an AHK script compiled to an `.exe` file.

**Comment by seathasky** [comment]
This feature has never worked for me unfortunately
