### ISSUE TITLE
Give an option to disable the overlay when pressing L1 + L3 on controller

### ISSUE THREAD

**Issue by toyhalibut** [goatcorp/FFXIVQuickLauncher#470]
Currently, if playing on controller with the quick launcher, pressing L1 (left bumper) and L3 (left analog stick click) together will trigger an overlay that darkens the game window and displays the text "Gamepad mode is ON. Press R1+L3 to deactivate, press R3 to toggle PluginInstaller." at the top left corner.

After fumbling through settings, checking documentation, and trying all kinds of different button combinations I cannot find any way to disable this feature.  Despite what the text says, pressing R1 + L3 does not seem to accomplish anything, either with this overlay on or with it off. Pressing R3 indeed toggles the PluginInstaller, however.

When this overlay is up, all other input is completely disabled, including moving, adjusting camera, and using actions.  There is no way to do anything in game until this overlay is closed by pressing L1 + L3 again.

Pressing L1 and L3 (or R3) together is not uncommon.  Many controller players have combat macros for L3 and R3, such as sprint or some type of targeting, and L1 is used for all forms of targeting.  Personally I have more than a handful of times pushed these two buttons together in the heat of combat only for this overlay to pop up and make me unable to do anything.

Please give us an option to disable this overlay from popping up.

**Comment by reiichi001** [comment]
The `L1 + R3` part is a typo and is actually supposed to be `L1 + L3`. Thisi s already fixed and will be included the next time a Dalamud update is released.

It's also already possible to disable the controller input mode. Type `/xlsettings` in game, click on the Look and Feel tab, and disable the last option.

**Comment by toyhalibut** [comment]
I see.  Thank you for your reply.

**Comment by zyzolol** [comment]
**The fact that it is ON by Default, is so unbelievably stupid.**
