### ISSUE TITLE
STOP with the billion "pre-releases," PLEASE

### ISSUE THREAD

**Issue by GuyInDogSuit** [goatcorp/FFXIVQuickLauncher#478]
This is the second time this has happened, where I've gotten a crap-ton of emails within the spam of just a couple hours, notifying me of a "pre-release" update. How do I disable those without disabling stable update notifications?

**Comment by goaaats** [comment]
Sorry, this is how our CI works.
I had to make a few of them this time around since I had to test the auto-updater. Shouldn't be the case as much in the future.
