### ISSUE TITLE
Crash when resizing game window if in-game features are enabled.

### ISSUE THREAD

**Issue by kamisamamizu** [goatcorp/FFXIVQuickLauncher#482]
**Describe the bug here:**
If in-game features are enabled, game crashes if I try to resize the game window.

**Steps to reproduce the bug:**
```
1. Click on Log In
2. Input OTP
3. Game Starts normally in a window
4. Try to maximize
5. Game Crashes
```

**Expected behavior**
Game maximizes like normal.

**Other information (*please* complete the following information):**
  Operating System: Windows 10 21H1 (19043.1083)
  XIVLauncher version: v6.0.4.0
  Launching as admin?: No
  Using Steam?: No
  Addons/Plugins enabled: No

**Additional information**
I have attached the info WinDbg gives me when the crash occurs.
[xiv_error_windbg.txt](https://github.com/goatcorp/FFXIVQuickLauncher/files/6810758/xiv_error_windbg.txt)
Like I said, no error happens in the in-game features are not enables.

**Comment by reiichi001** [comment]
Hello. 

Do you have a link to the Rich Presence program you're using? If that's supposed to be the Dalamamud.RichPresence plugin, you don't want to add that as a startup program. Plugins are managed in-game after launching.

Can you also please provide the `output.log` and `dalamud.log` files from your most recent crash? They can be found in `%appdata%\xivlauncher` (Appdata\roaming\xivlauncher)

**Comment by kamisamamizu** [comment]
Can you explain what a Rich Presence program is? I use XIVLauncher without any changes apart from the in-game features enabled or disables.
Also, I checked the logs and apart from a "Game has exited" message I don't see anything out of the ordinary.
I am providing them either way.
[output.log](https://github.com/goatcorp/FFXIVQuickLauncher/files/6810853/output.log)
[dalamud.log](https://github.com/goatcorp/FFXIVQuickLauncher/files/6810854/dalamud.log)

**Comment by reiichi001** [comment]
Ah, my apologies. The sample screenshot you had provided was listing a rich presence program. I see that was edited and removed.

I'm checking your logs now.

**Comment by reiichi001** [comment]
After reading through your logs, everything appears to be fine there.

Do you have any other programs that modify FFXIV? 

This includes, but is not limited to:
- shader mods like reshade, gshade, etc
- FPS displays/limiters like RivaTuners/RTSS/MSI Afterburner
- Game-recording/streaming software such as FRAPS or OBS
- ACT (if you specifically use the unsupported ActWebSocketOverlay which should be replaced with OverlayPlugin now)

**Comment by kamisamamizu** [comment]
So looking at your list of possible programs, it seems to be RTSS/MSI Afterburner related.
If I close them, no issue happens.
I should have looked into the FAQ, added the delay and trigger config to rtss and now it seems to work as it should.
Thing is, I don't remember having issues yesterday, so I don't know anymore.
Either way I am closing this issue.

Thanks for your help.
