### ISSUE TITLE
Again updating the game. Doesn't work again.

### ISSUE THREAD

**Issue by gamer4eg** [goatcorp/FFXIVQuickLauncher#487]
Again updating the game. Doesn't work again.
I understand that you are most likely in the know, but suddenly not? ..

**Comment by seathasky** [comment]
Updating worked just fine here.

**Comment by gamer4eg** [comment]
![image](https://user-images.githubusercontent.com/23147230/126308699-e83d8421-afb6-49da-b264-5258f52052b4.png)
Reinstall?

**Comment by Jta26** [comment]
you gotta wait for these guys to update the launcher to support the plugins man. The patch just came out chill.

**Comment by seathasky** [comment]
> you gotta wait for these guys to update the launcher to support the plugins man. The patch just came out chill.

people are impatient and dont  understand how things work lol
