### ISSUE TITLE
Unable to launch with DXVK/DX11

### ISSUE THREAD

**Issue by GingerBobRoss** [goatcorp/FFXIVQuickLauncher#491]
This isnt because of the Launcher, but i have been having issues getting DX11 to run on XIV after i had to do a reinstall of Pop_OS
DX9 mode works fine through the launcher, but DX11 instantly crashes. Launcher reports this error
I do have all frameworks, Runtimes and Direct X plugins installed in my wine prefix and reported under Winetricks

System.Exception: Game exited prematurely
   at XIVLauncher.Game.Launcher.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Launcher.cs:line 269
Version: 6.0.4.0
Git Hash: 6.0.4-0-g635be0c
Context: XG LaunchGame
OS: Microsoft Windows NT 6.1.7601 Service Pack 1
64bit? True
DX11? True
Addons Enabled? False
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: Z:\media\gonger\Games\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

**Comment by reiichi001** [comment]
Hi there!

What version of wine are you using? (Lutris should provide a custom build by default for version 5.7-11)

And have you tried downgrading DXVK from 1.9 back to 1.8.1? We've seen a few Wine users report issues we th DXVK 1.9. You should be able to select older versions in the Lutris interface.

**Comment by reiichi001** [comment]
Closing due to lack of response.
