### ISSUE TITLE
Improve login error

### ISSUE THREAD

**Issue by thibaultmol** [goatcorp/FFXIVQuickLauncher#493]
The login error you get if your password and such are invalid is the same error if you don't have a service account for ffxiv. I'm new to ffxiv so I didn't realize that if you buy the game you still need to activate it via the email code. So I kept trying for hours on end to login and kept getting errors, but it was because I had no service account yet. 
I'm guessing you guys can't detect whether that's the problem or if the login details are actually incorrect or not. 
Either way: Might be good to add a line to that to the error or to the faq about this

**Comment by goaaats** [comment]
Yeah, there is no way to detect this, as far as I can see. Sorry!
Will think about adding a note to the faq.
