### ISSUE TITLE
Error Message, told me to post it in github

### ISSUE THREAD

**Issue by Gamniac** [goatcorp/FFXIVQuickLauncher#494]
System.AggregateException: Ausnahmen einer Aufgabe wurden nicht überwacht (entweder wegen Wartens auf die Aufgabe oder wegen des Zugriffs auf die Ausnahmeeigenschaft. Daher wurde die nicht überwachte Ausnahme vom Finalizer-Thread erneut ausgelöst. ---> System.Net.Http.HttpRequestException: Fehler beim Senden der Anforderung. ---> System.Net.WebException: Die Verbindung mit dem Remoteserver kann nicht hergestellt werden. ---> System.Net.Sockets.SocketException: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte 127.0.0.1:65349
   bei System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   bei System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   bei System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   bei System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei XIVLauncher.Game.Patch.Acquisition.Aria.JsonRpc.JsonRpcHttpClient.<Invoke>d__4`1.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Patch\Acquisition\Aria\JsonRpc\JsonRpcHttpClient.cs:Zeile 40.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei AriaNet.AriaManager.<Invoke>d__3`1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei AriaNet.AriaManager.<Shutdown>d__29.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Patch\Acquisition\Aria\AriaManager.cs:Zeile 188.
   --- Ende der internen Ausnahmestapelüberwachung ---
---> (Interne Ausnahme #0) System.Net.Http.HttpRequestException: Fehler beim Senden der Anforderung. ---> System.Net.WebException: Die Verbindung mit dem Remoteserver kann nicht hergestellt werden. ---> System.Net.Sockets.SocketException: Es konnte keine Verbindung hergestellt werden, da der Zielcomputer die Verbindung verweigerte 127.0.0.1:65349
   bei System.Net.Sockets.Socket.InternalEndConnect(IAsyncResult asyncResult)
   bei System.Net.Sockets.Socket.EndConnect(IAsyncResult asyncResult)
   bei System.Net.ServicePoint.ConnectSocketInternal(Boolean connectFailure, Socket s4, Socket s6, Socket& socket, IPAddress& address, ConnectSocketState state, IAsyncResult asyncResult, Exception& exception)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Net.HttpWebRequest.EndGetResponse(IAsyncResult asyncResult)
   bei System.Net.Http.HttpClientHandler.GetResponseCallback(IAsyncResult ar)
   --- Ende der internen Ausnahmestapelüberwachung ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei XIVLauncher.Game.Patch.Acquisition.Aria.JsonRpc.JsonRpcHttpClient.<Invoke>d__4`1.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Patch\Acquisition\Aria\JsonRpc\JsonRpcHttpClient.cs:Zeile 40.
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei AriaNet.AriaManager.<Invoke>d__3`1.MoveNext()
--- Ende der Stapelüberwachung vom vorhergehenden Ort, an dem die Ausnahme ausgelöst wurde ---
   bei System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   bei System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   bei AriaNet.AriaManager.<Shutdown>d__29.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Patch\Acquisition\Aria\AriaManager.cs:Zeile 188.<---

Version: 6.0.4.0
Git Hash: 6.0.4-0-g635be0c
Context: Unhandled
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? False
Auto Login Enabled? True
Language: English
LauncherLanguage: German
Game path: D:\Game Launcher\FFXIV

**Comment by Gamniac** [comment]
The Error happened when i was downloading XIV fresh via the Quicklauncher, after getting permanents 90002, 10105 or 2002

**Comment by reiichi001** [comment]
Hello!

Is this issue still occuring for you?

Based on the log, it looks like XIVLauncher was not able to communicate with XIVPatcher. Most often, this is caused by your antivirus software. If the issue is still happening, I'd recommend whitelisting all the of the files/folders mentioned in the [FAQ](https://goatcorp.github.io/faq/xl_troubleshooting#q-how-do-i-whitelist-xivlauncher-and-dalamud-so-my-antivirus-leaves-them-alone). 

If you're still running into issues, please let us know!

**Comment by Gamniac** [comment]
Hi there, nope the Launcher purrs like a happy Kitten. I think it had something to do with that the servers at that weekend where still unstable after maintenance. all good now :)
