### ISSUE TITLE
Unable to multibox more than 2 instances/clients

### ISSUE THREAD

**Issue by rumoredlegends** [goatcorp/FFXIVQuickLauncher#498]
Greetings! I am receiving the following error when attempting to login with on my 3rd instance of FFXIVQuickLauncher.

> System.Exception: Game exited prematurely
   at XIVLauncher.Game.Launcher.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Launcher.cs:line 269
Version: 6.0.4.0
Git Hash: 6.0.4-0-g635be0c
Context: XG LaunchGame
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: E:\Games\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

![Error](https://user-images.githubusercontent.com/4657321/127734710-6c5eb806-04b3-40ed-81c3-c9701c6920a5.png)

I have tried completely re-installing (and clearing out Roaming/Local AppData regarding XIVQuickLauncher) with no luck and this seems to be independent of OTP being enabled.

In my case, I am trying to use one account I have a subscription with + 2 trial accounts and the error appears regardless of which combination of accounts I use. Once I attempt to login to the 3rd instance the application seems to fail.

**Comment by Caraxi** [comment]
This is a limitation of the game itself, there is no way to run it with more than two clients because square enix set it that way

**Comment by rumoredlegends** [comment]
Hmm referring to: https://github.com/goatcorp/FFXIVQuickLauncher/issues/28 I thought there was an account/client limit up to 8, but perhaps I was mistaken and not up to speed on the latest methods deployed by SE to prevent multiboxing
