### ISSUE TITLE
Error with Steam

### ISSUE THREAD

**Issue by ChillZwix** [goatcorp/FFXIVQuickLauncher#500]
Trying to start the game with the custom launcher in steam to keep the steam system. The launcher works standalone, and the offical works with steam. 

Get this error:
`System.ComponentModel.Win32Exception (0x80004005): 'CredWrite' call throw an error (Error code: 1312)
   ved AdysTech.CredentialManager.CredentialManager.SaveCredentials(String target, NetworkCredential credential)
   ved XIVLauncher.Accounts.XivAccount.set_Password(String value) i D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Accounts\XivAccount.cs:linje 45
   ved XIVLauncher.Windows.MainWindow.PrepareLogin(Boolean autoLogin, Boolean startGame) i D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\MainWindow.xaml.cs:linje 430
   ved System.Windows.Threading.Dispatcher.Invoke(Action callback, DispatcherPriority priority, CancellationToken cancellationToken, TimeSpan timeout)
   ved System.Windows.Threading.Dispatcher.Invoke(Action callback)
   ved XIVLauncher.Windows.MainWindow.HandleBootCheck(Action whenFinishAction) i D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\MainWindow.xaml.cs:linje 349
Version: 6.0.4.0
Git Hash: 6.0.4-0-g635be0c
Context: HandleBootCheck
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: I:\SteamLibrary\steamapps\common\FINAL FANTASY XIV Online`

IMG: https://ibb.co/7zSpymz

**Comment by reiichi001** [comment]
This issue isn't due to steam. It means XIVLauncher was unable to save your credentials in the Windows Credential Manager.

If you're still experiencing this, please see: https://goatcorp.github.io/faq/xl_troubleshooting#q-xiv-isnt-saving-my-new-password--how-do-i-clear-my-saved-password

**Comment by reiichi001** [comment]
Closing issue - no response
