### ISSUE TITLE
Long black screen when stopping the game

### ISSUE THREAD

**Issue by Alkor1** [goatcorp/FFXIVQuickLauncher#503]
**Describe the bug here:**
When exiting the game normally, there's a long black screen instead of just closing the game instantly like before I started using this launcher.
I'm playing in borderless window mode, and a friend with the same issue is playing in windowed mode, we didn't test if it was happening in full screen mode.

**Steps to reproduce the bug:**
Exit the game normally.

**Expected behavior**
I expected the game to close instantly like before

**Other information (*please* complete the following information):**
  Operating System: W10
  XIVLauncher version: 6.0.4.0
  Launching as admin?: no
  Using Steam?: no 
  Addons/Plugins enabled: penumbra

**Additional information**

**Comment by reiichi001** [comment]
Which plugins do you have installed? 

And if you're still experiencing this issue, can you please upload your `dalamud.log` file from `%appdata%\xivlauncher`

**Comment by splintermind** [comment]
I've had the same issue. Log: [https://pastebin.com/BgucwcMg](https://pastebin.com/BgucwcMg)

**Comment by reiichi001** [comment]
> I've had the same issue. Log: https://pastebin.com/BgucwcMg

Most likely, this was a momentary network issue or an issue with Universalis, as your log shows connection issues coming from the PriceCheck plugin.

Is this issue still occurring for either of you? @Alkor1 @splintermind

**Comment by jamvng** [comment]
same issue here.

**Comment by goaaats** [comment]
If you're using Logitech GHub, it's causing this.

**Comment by reiichi001** [comment]
Closing due to age. If this is still happening on the latest version of XIVLauncher (6.0.9) and Dalamud (6.0.1.2 at time of writing) please open a new issue and we can help troubleshoot it.
