### ISSUE TITLE
Game Crashes on startup

### ISSUE THREAD

**Issue by thelouisianimal** [goatcorp/FFXIVQuickLauncher#514]
As I was installing new dalamud plugins (after using several succesfully for a few days) the game suddenly closed. No error message, no disconnect, just completely shut off. In order to get back in i had to completely remove FFXIV launcher entirely. Upon reinstallation, the game started to crash again so I once again had to delete it. I would like to use the addons like gather buddy etc, but i believe installation of "Job Bars" is what caused the issue. I cannot find the old FFXIV data saved anywhere on computer to get a completely clean install.

**Comment by reiichi001** [comment]
There's currently an issue that occurs between SimpleTweaks and Job Bars. If you have both it'll cause a crash.

You can either delete the plugin files directly from `%appdata%\xivlauncher\installedPlugins` or you can try to use the plugin manager from inside XIVLauncher's settings.

**Comment by thelouisianimal** [comment]
so can i keep Simple Tweaks but remove Job Bars and be ok? thank you for
the quick response, the addons are amazing.

**Comment by reiichi001** [comment]
If all is working well, please let us know or close the issue

**Comment by reiichi001** [comment]
Closing issue - no response
