### ISSUE TITLE
Able to login, but a small window "Updating in-game addon" keeps appearing

### ISSUE THREAD

**Issue by PureDarkZ** [goatcorp/FFXIVQuickLauncher#520]
The custom launcher plugin won't work, and everytime i login there is a small window saying "Updating in-game addon..." that won't go away.

This does not happen because of the update, since it was working fine after the update yesterday.

I already tried checking the game integrity, disabling any other mods, reinstalling the XL, no luck so far.

https://cdn.discordapp.com/attachments/753488049996038174/880026315598729246/unknown.png

  Operating System: Windows 10
  XIVLauncher version: v6.0.6.0 - 6.0.6.0-gac7dd80-4.0.30319.42000
  Launching as admin?: NO
  Using Steam?: NO
  Addons/Plugins enabled: yes

**Comment by reiichi001** [comment]
Closing issue - no response

**Comment by adrkn** [comment]
The same issue on my mac:
![image](https://user-images.githubusercontent.com/23166434/197070357-85e7c7dd-370f-4150-925d-0731ce084697.png)

**Comment by NotNite** [comment]
We do not provide support for XIV on Mac. Go to their repositories or Discord server for support.
