### ISSUE TITLE
Launch Steam before FFXIV

### ISSUE THREAD

**Issue by Quado1** [goatcorp/FFXIVQuickLauncher#522]
**What is your suggestion/feature request?**

Hello.

Is is possible to create function (with a checkbox in the XIVLauncher somewhere) to launch Steam and only then FFXIV?

I have the FFXIV Steam version, but sometimes I forget to launch Steam, and play without it through XIVLauncher, so I'm not online on Steam, the game time doesn't count there etc.

**Describe how you'd like this to work**
1) Check some checkbox in the XIVLauncher (like "Launch Steam before FFXIV") once
2) The XIVLauncher will find or user will show the path to the steam.exe once
3) The XIVLauncher starts the steam.exe
4) Sleep 1000 - 5000 ms (let steam.exe launch) or pop up a window with the "Is Steam launched?" question and the "Yes" button to click it to continue, or/and add an option to disable/enable this pop up window if Steam launches fast
5) (Ask for OTP and) launch the game

**Comment by dariomkdr** [comment]
Same here, it would be a great addition

**Comment by reiichi001** [comment]
You can add Steam as a addon program in XIVLauncher.

It won't start steam -before- FFXIV, but it will start in -with- FFXIV

**Comment by Quado1** [comment]
> You can add Steam as a addon program in XIVLauncher. This is in XIVLauncher's settings ->Auto-Launch
> 
> It won't start steam -before- FFXIV, but it will start in -with- FFXIV

Thank you, but the method doesn't solve the problem - overlay doesn't work, play time doesn't count.

**Comment by reiichi001** [comment]
As long as you have steam integration checked in XIVLAUNCHER, play time will accumulate. 

If you want the overlay or controller support, you have to open Xivlauncher through steam. Please see the FAQ https://goatcorp.github.io/faq/xl_troubleshooting#q-why-do-people-keep-asking-about-steam-so-much

**Comment by Quado1** [comment]
> As long as you have steam integration checked in XIVLauncher, play time will accumulate.
> 
> If you want the overlay or controller support, you have to open XIVLauncher through steam. Please see the FAQ https://goatcorp.github.io/faq/xl_troubleshooting#q-why-do-people-keep-asking-about-steam-so-much

I use both the "Steam Integration" and the "Use Steam service account".

If the Launcher starts the game before the Steam, the play time doesn't accumulate, Steam doesn't see me playing ffxiv, both the overlay and the controller support don't work.

I don't need to open XIVLauncher through Steam to get the overlay and the controller support - they both work perfectly when I launch Steam first and the Launcher second (not through Steam).

**Comment by Quado1** [comment]
I've created a bat file to start the Steam first and the FFXIV Launcher next:
```bat
START C:\"Program Files (x86)"\Steam\steam.exe
timeout /t 1 /nobreak > NUL
START C:\Users\userName\AppData\Local\XIVLauncher\XIVLauncher.exe
```
