### ISSUE TITLE
Discord Rich Presence not updating to 'in menus' after logging into a character

### ISSUE THREAD

**Issue by StrawberryClover** [goatcorp/FFXIVQuickLauncher#524]
**Describe the bug here:**
I use the discord rich presence to show my status on discord, but it only shows 'in menus' when I first launch the game. When it logs me out, or I afk until I get back into the menus, or even just log off and leave the game running overnight, it will just show that I am logged in and show my character all night long pretty much. I assume this isn't that big of a deal, but would love to see it update properly to reflect my status when I am not logged in and just letting it idle on the title screen.

**Steps to reproduce the bug:**
```
1. Open launcher, log in, launch game etc. with rich presence enabled.
2. Notice that the rich presence updates to 'in menus' when you first launch the game, before logging into a character.
3. Log into a character, then immediately log back out again.
4. Notice that the rich presence shows that you are online on that character with all the proper info showing as if you were logged in. It will never update to 'in menus', even if you let it sit overnight like that.
```

**Expected behavior**
I expect the rich presence to update to 'in menus' when you log out of your character and are sitting in character select, or in the title screen.

**Other information (*please* complete the following information):**
  Operating System: Windows 10
  XIVLauncher version: 6.0.6.0
  Launching as admin?: No
  Using Steam?: No
  Addons/Plugins enabled: Chat Bubbles, Compass, Discord Rich Presence, ezMiniCactpot, ezWondrousTails, Fancy Loading Screens, Good Memory, Item Search, Kapture, Market board, OwO, Peeping Tom, PrefPro, PriceCheck, RezPls, Simple Tweaks, Sonar, SoundSetter, TitleEdit

**Comment by reiichi001** [comment]
Hello! Is this still happening?

If so, please let us know on our support discord in the plugin-issues-help channel or file an issue on the plugin's github repo as it's not directly XIVLauncher related.

**Comment by NPittinger** [comment]
Fixed in https://github.com/goaaats/Dalamud.RichPresence/pull/7
