### ISSUE TITLE
Game exited prematurely

### ISSUE THREAD

**Issue by kennedyoliveira** [goatcorp/FFXIVQuickLauncher#526]
Constantly getting errors when trying to open game, if I retry for a few times, 3 - 5 times eventually it works no problem.

```
System.Exception: Game exited prematurely
   at XIVLauncher.Game.Launcher.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Launcher.cs:line 270
Version: 6.0.6.0
Git Hash: 6.0.6-0-gac7dd80
Context: XG LaunchGame
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn
```

I have the non steam version, using two step auth.

**Comment by reiichi001** [comment]
Do you have any other programs that try to inject into FFXIV?

This includes, but is not limited to:

- RivaTuner / RTSS / MSI Afterburner
- FRAPS
- OBS
- Reshade/Gshade
- ghub
- MacType
- ACT WebSocketOverlay

**Comment by kennedyoliveira** [comment]
Yeah, I have a couple of them, RivaTurner and cya, act, Special K.
Seems the culpid is Special K, since I removed it, I didn't see any issue, will keep and eye on it.

**Comment by reiichi001** [comment]
SpecialK will cause issues for most users, unfortunately. It's related to how directx is hooked and it causes conflicts. If you're able to make it inject after the fact, that might work.

The same mostly goes for RiveTuner, but we're better acquainted with how it behaves and have details on the FAQ regarding how to make sure it doesn't conflict. https://goatcorp.github.io/faq/xl_troubleshooting#q-how-to-set-an-injection-delay-in-rivatunerrtss

**Comment by reiichi001** [comment]
Hello! Any further issues?

**Comment by kennedyoliveira** [comment]
Nope, no more issues, it was SpecialK indeed. Thanks!
