### ISSUE TITLE
Added option to choose mac platform

### ISSUE THREAD

**Issue by qoyyim** [goatcorp/FFXIVQuickLauncher#527]
**What is your suggestion/feature request?**
since the mac version is buggy and does not fully work, I suggest we add an option to log in using mac account for people who mistakenly choose mac version of ffxiv

**Describe how you'd like this to work**
adding checkbox just like steam

**Additional context**
since the mac version is just wine wrapper of pc version
we just need to change platform and/or agent when we call auth API

Thank You

**Comment by goaaats** [comment]
Making the game itself think that it's running on mac isn't as trivial, and this would mean circumventing SE's platform restrictions. We probably won't add it - you can register a Mac and a PC license on the same account, so it's not like Steam/PC where they're mutually exclusive.
