### ISSUE TITLE
Game will not launch if I close out and try to log back in

### ISSUE THREAD

**Issue by t3hasiangod** [goatcorp/FFXIVQuickLauncher#532]
I get the error below if I log out of the game and try to log back in. If I restart my computer, it'll allow me to log into the game again, but if I log out at any point and try to get back into the game, it keeps throwing this error. I tried to find the file noted in the error log, but there is path that leads to that in the D drive either. 

System.Exception: Game exited prematurely
   at XIVLauncher.Game.Launcher.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Launcher.cs:line 270
Version: 6.0.6.0
Git Hash: 6.0.6-0-gac7dd80
Context: XG LaunchGame
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: I:\Final Fantasy XIV\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

**Comment by reiichi001** [comment]
Hello!

Is this still happening?

The path provided in the error message is based on the developer's computer, not yours. This sounds like a plugin is not properly handling logout and is crashing the game. It may help to clear out your plugin files in `%appdata%\xivlauncher\installedPlugins`. Their settings are stored separately and will be retained.

**Comment by t3hasiangod** [comment]
Yes, this is still happening. Should I go through my plugins individually until I find the culprit?

**Comment by reiichi001** [comment]
Yes. I'd start with removing all plugins and see if the issue still happens. Then add half back and try to reproduce the issue. If no crashes, add a few more. Repeat until all plugins are installed again.

Sometimes, this is a case where an old plugin version was getting loaded when it shouldn't have (which also shouldn't happen, but weirder's happened).

**Comment by t3hasiangod** [comment]
I think I've found the culprit. I think it was the old config files for Kamera that I did not delete. The game is a bit slow to load in, but it won't crash any longer.
