### ISSUE TITLE
Linux Lutris - Could not secure SSL/TLS secure channel

### ISSUE THREAD

**Issue by ellitedev** [goatcorp/FFXIVQuickLauncher#538]
I saw a few errors during install, but i didn't explicitly see anything out of the ordinary. Running Fedora 34, with the latest Lutris version.

> System.AggregateException: One or more errors occurred. ---> System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
>    at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
>    at System.Net.WebClient.UploadString(Uri address, String method, String data)
>    at XIVLauncher.Game.Launcher.RegisterSession(OauthLoginResult loginResult, DirectoryInfo gamePath) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Launcher.cs:line 403
>    at System.Threading.Tasks.Task`1.InnerInvoke()
>    at System.Threading.Tasks.Task.Execute()
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
>    at XIVLauncher.Game.Launcher.Login(String userName, String password, String otp, Boolean isSteamServiceAccount, Boolean useCache, DirectoryInfo gamePath) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Launcher.cs:line 125
>    at XIVLauncher.Windows.MainWindow.<StartLogin>d__19.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\MainWindow.xaml.cs:line 586
> ---> (Inner Exception #0) System.Net.WebException: The request was aborted: Could not create SSL/TLS secure channel.
>    at System.Net.WebClient.UploadDataInternal(Uri address, String method, Byte[] data, WebRequest& request)
>    at System.Net.WebClient.UploadString(Uri address, String method, String data)
>    at XIVLauncher.Game.Launcher.RegisterSession(OauthLoginResult loginResult, DirectoryInfo gamePath) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Launcher.cs:line 403
>    at System.Threading.Tasks.Task`1.InnerInvoke()
>    at System.Threading.Tasks.Task.Execute()<---
> 
> Version: 6.0.6.0
> Git Hash: 6.0.6-0-gac7dd80
> Context: Login
> OS: Microsoft Windows NT 6.1.7601 Service Pack 1
> 64bit? True
> DX11? True
> Addons Enabled? True
> Auto Login Enabled? True
> Language: English
> LauncherLanguage: English
> Game path: C:\Program Files (x86)\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

**Comment by reiichi001** [comment]
Please see the Fedora-specific section of https://goatcorp.github.io/faq/xl_troubleshooting#q-im-on-linux-and-i-keep-getting-xivlauncher-failed-to-update-errors

**Comment by ellitedev** [comment]
> Please see the Fedora-specific section of https://goatcorp.github.io/faq/xl_troubleshooting#q-im-on-linux-and-i-keep-getting-xivlauncher-failed-to-update-errors
I also noticed that in this issue, the user was able to fix it with that command. But thanks for directing me! I will now close this issue.
https://github.com/goatcorp/FFXIVQuickLauncher/issues/360#issuecomment-763229908
