### ISSUE TITLE
QuickLauncher Crashing with no errors?

### ISSUE THREAD

**Issue by BoaChan** [goatcorp/FFXIVQuickLauncher#559]
The quick launcher I have will work fine. Loads up. Gets to character menu. Click login. Gets to "Now Loading" and crashes. With no errors. Any fixes? I open normal launcher and able to log in and move with no issues.

**Steps to reproduce the bug:**
Example:
```
1. Click on Auto-Launcher
2. Click enter game
3. Click on character. Log-in/Sit in wait queue
4. Now Loading page thinks and then just shuts down.
```

**Comment by BoaChan** [comment]
I have reinstalled the launcher and restarted my computer. Still same issues.

**Comment by summunosuke** [comment]
i have same issues but i can login already but when i open dalamut menu some time my coputer got black screen i'm use windows 11.

**Comment by Siren1194** [comment]
I'm having the same issue, once it updated i couldnt use my game at all.
