### ISSUE TITLE
Game crashes on launch

### ISSUE THREAD

**Issue by j3nesis87** [goatcorp/FFXIVQuickLauncher#563]
System.Exception: Game exited prematurely
   at XIVLauncher.Game.Launcher.LaunchGame(String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamIntegrationEnabled, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Game\Launcher.cs:line 270
Version: 6.0.6.0
Git Hash: 6.0.6-0-gac7dd80
Context: XG LaunchGame
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: C:\Users\Jenny\Dropbox\Media\Games\FINAL FANTASY XIV Online

**Comment by reiichi001** [comment]
Hello! Please make sure you're launching with XIVLauncher 6.0.9 (the current version). Older versions of the launcher should autoupdate normally, but you may need to get the current release manually if that doesn't happen.

You may also need to adjust your antivirus whitelists. See this [FAQ Post](https://goatcorp.github.io/faq/xl_troubleshooting#q-how-do-i-whitelist-xivlauncher-and-dalamud-so-my-antivirus-leaves-them-alone) for more details.

After that, please let us know if the issue still occurs.

**Comment by reiichi001** [comment]
Closing due to age. If this is still happening on the latest version of XIVLauncher (6.0.9) and Dalamud (6.0.1.2 at time of writing) please open a new issue or contact us in discord and we can help troubleshoot it.
