### ISSUE TITLE
[Linux] Game crash on startup with "Enable in-game features" active since latest update.

### ISSUE THREAD

**Issue by rjoffr07** [goatcorp/FFXIVQuickLauncher#573]
**Describe the bug here:**
Game crash on startup when "Enable in-game features" is active since Dalamud has been updated from v6.0.0.17 to v6.0.1.0.
Worked fine a few hours ago when using Dalamud 6.0.0.17.

**Steps to reproduce the bug:**
Example:
```
1. Enable in-game features
2. Start Game with latest version of XIVLauncher
3. Game crash
```
**Other information (*please* complete the following information):**
  Operating System: Linux 5.10.70-1 Manjaro
  XIVLauncher version: 6.0.9.0-6.0.9-0-g5113f9e
  Launching as admin?: no
  Using Steam?: no
  Addons/Plugins enabled: none

**Additional information**
Launched from lutris using Wine (lutris-6.10-7-x86_64).
Installed via Lutris using [this](https://lutris.net/games/install/29349/view) installation script.

**Comment by goaaats** [comment]
dupe https://github.com/goatcorp/Dalamud/issues/670
