### ISSUE TITLE
XIVLauncher Dalamund Error

### ISSUE THREAD

**Issue by CielLuxor** [goatcorp/FFXIVQuickLauncher#575]
**Other information (*please* complete the following information):**
  Operating System: Windows 10
  XIVLauncher version: Yes 
  Launching as admin?:  Yes
  Using Steam?: Yes
  Addons/Plugins enabled: Yes

**Additional information**

https://cdn.discordapp.com/attachments/209828789813772290/904979975785025607/b7cc4861f93eaab241e8f372b5aec3bf.png

https://drive.google.com/file/d/1YcFYtzXjpNGBUy17TG5TjlEiY9P-4YQR/view?usp=sharing

heres the dalamund log here

**Comment by goaaats** [comment]
Hey, this shouldn't occur any longer. If this still happens for you, please join our Discord to troubleshoot.
