### ISSUE TITLE
No error crashing

### ISSUE THREAD

**Issue by CodesByMo** [goatcorp/FFXIVQuickLauncher#577]
I'm getting consistent crashes, no errors. I'm able to replicate the crash (4 times in a row)

- Login 
- Hire retainer
- Confirm retainer
- Crash

**Comment by AlfredWongCL** [comment]
I started to have this issue too after I opened my razor synapse for update, can't even log into the game until I close it so I think it has something to do between them.

**Comment by goaaats** [comment]
Hey, please join our Discord to troubleshoot - this is a plugin issue, so we can't track it here. Thank you!
