### ISSUE TITLE
Unable to Launch Game

### ISSUE THREAD

**Issue by Nanu308** [goatcorp/FFXIVQuickLauncher#580]
> System.AggregateException: One or more errors occurred. ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
>    --- End of inner exception stack trace ---
>    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
>    at XIVLauncher.Windows.MainWindow.StartLogin(String otp, Boolean startGame) in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\MainWindow.xaml.cs:line 588
> ---> (Inner Exception #0) System.Threading.Tasks.TaskCanceledException: A task was canceled.<---
> 
> Version: 6.0.12.0
> Git Hash: 6.0.12-0-gd32cbcd
> Context: Login
> OS: Microsoft Windows NT 6.2.9200.0
> 64bit? True
> DX11? True
> Addons Enabled? True
> Auto Login Enabled? False
> Language: English
> LauncherLanguage: English
> Game path: E:\Games\SteamLibrary\steamapps\common\FINAL FANTASY XIV Online
>

**Comment by goaaats** [comment]
Hey, please join our Discord to troubleshoot this. Thank you!
