### ISSUE TITLE
[Keepass] Integrate Keepass as an OTP / Authentication Source

### ISSUE THREAD

**Issue by DrKittens** [goatcorp/FFXIVQuickLauncher#585]
**What is your suggestion/feature request?**

Bundle a kdbx implementation with an OTP plugin in the installer to use a universal authnetication source / credential management system instead of the OS based credential store. The reasoning for this is to allow for backups of the launcher / configuration to also include the account credentials. ex a re-install of windows or a forced password change can blank the OS credential store causing loss of credentials.

kbdx/keepass implementations allow for the storage of OTP challenges which can allow for the complete credential to be safely stored in a single location reducing complexity / code upkeep if the underlying method to store/address credentials changes between OS versions or updates.

**Describe how you'd like this to work**
As a quick example:
1. Bundle the following with the install on all platforms:
 - keepass implementation with kpopt plugin or OS specific equivalent (eg keepassxc for linux)
 - https://keepass.info/plugins.html#kpotp
2. Make use of the natives in keepasslib api to perform the following actions
  - Create a keepass database backed by a keyfile
  - set filesystem permissions on the keyfile to be readable/accessible only the by the current user (effectively the same as windows credential store, ex current user can read everything for current user without challenge)
  - request user provide account details, store in keepass secret
  - request user provide OTP key, store in keepass secret associated with account
  - read in the account credentials / otp answer from keepass using keepasslib api as an alternative credential source

**Additional context**
The intention is to make use of a more universal platform agnostic mechanism for storing secrets as linux/mac/windows implementations of the kbdx format all support storing OTP credentials in addition to the account credential. Investigating something like this could save development / upkeep time in the future for storing credentials securely.

**Comment by reiichi001** [comment]
Personal opinion, but this seems like quite a bit of additional complexity for little reward.

Even on Linux and macOS, the Windows Credential Store exists as part of Wine's registry and as we're unlikely to ever move away from Wine on those platforms, it's effectively platform-agnostic. As it stands, Windows doesn't really have any supported methods of pulling a password out of the credential store (and if a user wants to use hacks for that on their local machine, there are bigger issues for them to solve). 

As somewhat discussed in length on our discord and in https://github.com/goatcorp/FFXIVQuickLauncher/pull/437 , there isn't a lot of code-dev approval in letting XIVLauncher be its own OTP generator. The currently proposed compromise was to modify XL-Auth to include a desktop app as well, so a user could run a separate (and thus, not packaged with XIVLauncher) program to send the OTP to XIVLauncher faster.

**Comment by DrKittens** [comment]
I agree with you, i did a bit more reading and yes, all alt-OS implementations run on wine so there isnt really a need for that agnosticism.

I've read through #437 and was unaware of the discussions there which do already go over this alot but with a different, near identical avenue.

I'm self-resolving this as its just re-treading trodden ground and doesn't add sufficient value.
