### ISSUE TITLE
Korean FFXIV Launcher

### ISSUE THREAD

**Issue by aksum3** [goatcorp/FFXIVQuickLauncher#592]
**Describe the bug here:**
I can't run the FFXIV launcher for the Korean client.

**Steps to reproduce the bug:**
```
1. Run install.command from seathasky/FF14-MAC_ModSupport
2. Install dependencies
3. Run local installer exe inside new bottle
4. After installing the native launcher, it shows a square percentage loading window/box
5. Nothing happens :( box disappears and hangs, no login screen
```

Edit: I think the logs said something about "CEF"

**Other information (*please* complete the following information):**
  Operating System: macOS 12.1 (M1 Macbook Air)
  XIVLauncher version: Latest

**Additional information**

The Korean FFXIV has a separate client and setup.exe.  It is mostly the same as the original, but is locked to the local servers.  Can you please add support for this launcher?

Note: I have the Korean Resident ID, phone number, membership with Actoz, and the Korean setup exe.  Linking this for reference: https://github.com/seathasky/FF14-MAC_ModSupport/issues/32

**Comment by seathasky** [comment]
I doubt the Korean client is even usable with XIVLauncher, I'm under the impression that the game in Korea uses a proprietary client login from the publisher Actoz Soft.

I'm not speaking for Goatcorp here, but I will say the chances are zero to none for Korea.

Your best bet of using XIVLauncher would be on the international client on Japanese servers.

**Comment by aksum3** [comment]
They do not have a Mac client, and from what I have been reading from local players, Actoz does the bare minimum so we may luck out in the sense that the client is just reskinned and region locked :)

**Comment by aksum3** [comment]
They do not have a Mac client -- from what I have been reading from local players, Actoz does the bare minimum so we may luck out in the sense that the client is just reskinned and region locked :)

The Resident ID stuff happens on the website, not the client; if I spin up Parallels, which has a decent DX->Metal driver, but the poor WoW64 x86->ARM emulation done by software instead of Rosetta limits frame rates to 25-30.

If Parallels had their own WoW64 implementation to pass x86 commands up to Rosetta some of which are run directly by the GPU's instead of being translated, but I have no idea when that is coming.

**Comment by goaaats** [comment]
XL won't ever add support for regions other than WW, sorry.
I don't have an easy way to maintain it and it's a lot of work that I can't afford to do right now. CN has a separately distributed Dalamud.
