### ISSUE TITLE
[WINE]  Aria / .NET

### ISSUE THREAD

**Issue by mpalermo73** [goatcorp/FFXIVQuickLauncher#602]
Quick Lanucher version 6.1.0.0
![Screenshot_20211203_072152](https://user-images.githubusercontent.com/847259/144601775-1fb83d2e-4f75-4cdc-9e32-c388006a58e9.png)

I am unable to patch the game with this launcher.  Unfortunately this launcher is literally the ONLY way I have of playing the game.  The SE launch just sits on a whiote (sometimes black) screen,  That's how I found your launcher.  Yours is the only one that actually works, but now can't patch the game with it.

Aria "could not contact patch installer"
![Screenshot_20211203_071903](https://user-images.githubusercontent.com/847259/144601578-bf2a28e5-9d1f-4b2b-a65b-8cf7da3f183a.png)

.NET 
~Just sits and does nothing~
After about 15 minutes it came back with the same error above.

Obviously my computer is on the einterannt and all that... I'm typing this to you. 😉  Are therespecificc .NETpackagess I needinstalledd in this prefix?

**Comment by mpalermo73** [comment]
I doesn't appear to be DNS related.  These are not full communication, just snippets enoguh to show it's all working from a DNS perspective.

```
Dec  3 06:34:17 dnsmasq[457]: reply frontier.ffxiv.com is 124.150.157.190
Dec  3 06:35:49 dnsmasq[457]: reply frontier.ffxiv.com is 124.150.157.190
Dec  3 06:47:23 dnsmasq[457]: reply ffxiv-login.square-enix.com is 124.150.158.117
Dec  3 06:47:24 dnsmasq[457]: reply patch-gamever.ffxiv.com is 124.150.157.126
```

**Comment by mpalermo73** [comment]
and yes, I have installed the two packages you recommend in the FAQ

> Q: How can I fix crashes on startup?
> Please try to install the VC Redist from Microsoft at https://github.com/abbodi1406/vcredist/releases/latest, as well as the .NET 4.8 Runtime https://dotnet.microsoft.com/download/dotnet-framework/thank-you/net48-web-installer. If you are still facing issues, please message us in #xivlauncher_issues

**Comment by reiichi001** [comment]
What version of Wine are you on?

XIVLauncher on Linux should be using the .Net downloader library and not Aria by default. Aria2 will only work on Wine 6.16 and above, but our default is Wine 6.10. This is due to wine's changes in winsock.

**Comment by mpalermo73** [comment]
Good day!

I'm VERY sorry for the delay in responding.  I wanted to test and re-test a couple things before opening my mouth.

The bottom line is that a prefix created with the XIVQuickLauncher script is indeed the correct path towards a fully functional wine prefix.

BUT

https://lutris.net/games/install/29349/view

Using that as-is in Lutirs will fail and be unusable.  `winetricks` is used to install `dotnet48 vcrun2019 win10` however one of the packages it tries to install for dotnet "fails" the checksum, and in turn the entire script fails.

If you manually run through all those steps and build a prefix with `--force` on `winetricks` everything works perfectly.  `--force` skips checking checksums.  I did this three times before replying here.

I looked throug the documentation, and also just tested, the `app:` stanza  with a `name` of `winetricks` does NOT support the `args` variable so `--force` cannot passed to `winetricks`.  Yes I'm aware that is not you, that's Lutris and I'll open a bug with them.

My point is that simply telling people to "just use the Lutris XIVLauncher version" will just fail and they will move on.  It needs to be manually built so `--force` can be passed to ignore checksums allowing `winetricks` to finish.

Outside of that, yes you are 100% correct in that wine 6.10.* with the deps listed, and the use of the special env vars, does indeed leave a person with a fully functional, and fully updatable wine prefix via your Launcher.

Thank you for all your effort!

M.

**Comment by reiichi001** [comment]
@mpalermo73 the vcrun2019 recipe is hit and miss as winetricks can and does go out of date and that installer link changes often. 

It might be broken be you right now, but that doesn't mean it's broken for every other user. **Welcome to Linux being inconsistent and Lutris being our only hope of a seni-consistent environment to work with!**

Pinned in our discord, we have several methods on how to work around winetricks issues installing vcrun2019. 

1. Use system winetricks 
2. Open a bash prompt and update the bundled Lutris winetricks
3. Force install vcrun2019 bypassing the hash check failure 
4. Install vcrun2015 or vcrun2017 if they pass the check as they're secretly all the same package fwiw 

So it really is "just run the Lutris script" in all cases. We cannot account for everything and that is the point of having a troubleshooting discord and github issues being open.

**Comment by mpalermo73** [comment]
Thank you for all your input and time.  I have a functional prefix and your launcher has been working perfectly.  So nothing to see here...  ;-)
