### ISSUE TITLE
[Linux] New Dalamud injection method doesn't work under Wine

### ISSUE THREAD

**Issue by Maia-Everett** [goatcorp/FFXIVQuickLauncher#615]
**Describe the bug here:**
When I try to use the new Dalamud injection method, I get a "couldn't inject, try disabling your antivirus" error. The legacy injection method works correctly.

**Steps to reproduce the bug:**
```
1. Install XIVLauncher under Wine.
2. In Dalamud settings, switch to the new injection method (default).
3. Try to launch the game.
```

**Expected behavior**
The 

**Other information (*please* complete the following information):**
  Operating System: Ubuntu 21.10, Wine 6.10 from FFXIV Lutris
  XIVLauncher version: 6.1.0.0
  Launching as admin?: No
  Using Steam?: Yes
  Addons/Plugins enabled: N/A

**Comment by reiichi001** [comment]
This is known. We've added handling for new installs of XIVLauncher to default to the old method for Wine users. (Coming in XIVLauncher 6.1.2)

When Dalamud gets its official release, the announcement will also inform Linux users to manually swap to the DLL Injection method. This is similar to the .Net downloader/Aria2c situation.
