### ISSUE TITLE
HRESULT: 0x800004005

### ISSUE THREAD

**Issue by EliLightX** [goatcorp/FFXIVQuickLauncher#621]
![](https://cdn.discordapp.com/attachments/584827243617058816/918315205677703199/unknown.png)

I can't log in using the launcher at all. Might have to just give up because the launcher does not work unless I run it as admin and Cali in the Discord says not to do that. I added it to my antivirus whitelist and even tried a fresh install.

I can't make the FFXIV game folder not read-only, that may be the issue.

**Comment by goaaats** [comment]
This should be fixed now.
