### ISSUE TITLE
Launcher uninstalled itself after patch

### ISSUE THREAD

**Issue by Codex100** [goatcorp/FFXIVQuickLauncher#622]
XIVlauncher uninstalled itself after the update. unable to reinstall it again

**Comment by iNotacat** [comment]
I think the same think happened to me while my Bitdefender security decided to absolutely nuke this launcher. A lot of files got marked as infected, while previously it worked fine without an issue.

**Comment by yeezyeezy** [comment]
Exactly the same issue here. After the latest update BitDefender completely wrecked the launcher - can't even install it fresh with a new setup.exe.

**Comment by goaaats** [comment]
There's nothing we can do.

https://goatcorp.github.io/faq/xl_troubleshooting#q-how-do-i-whitelist-xivlauncher-and-dalamud-so-my-antivirus-leaves-them-alone

**Comment by yeezyeezy** [comment]
Did everything in the FAQ that was relevant in an attempt to help the situation (whitelisted all mentioned files/folders in Bitdefender Security and Firewall) and restarted multiple times - Now I just get the XIVLauncher failed to check for updates error - once if I try launching the program normally, twice (one after the other) if I try using the Setup.exe. 
If it's just one of those things where Bitdefender just breaks the program, I understand. Nothing you guys can do about that.
