### ISSUE TITLE
Opening the wrong expansion

### ISSUE THREAD

**Issue by marcuscaum** [goatcorp/FFXIVQuickLauncher#628]
My Launcher is launching with the shadowbringers version instead of the endwalker, yesterday was working just fine...

**Comment by Aireil** [comment]
You did not register your Endwalker code (not the code from early access, there is 2 different codes).
https://support.na.square-enix.com/faqarticle.php?id=5382&la=1&kid=76363&ret=faq

**Comment by RaijiMagiwind** [comment]
I can concur that I am having a similar issue. And mine is a fully registered collectors edition of Endwalker. It is showing the Shadowbringers screen instead of the Endwalker one.

**Comment by stijnhau** [comment]
Have you put in you game registration code for endwalker.
Not the pre registration code only?
The official launcher does the same

**Comment by NekoMiku39** [comment]
Have the same issue. See Issue #623. I also have the Endwalker Collectors Edition

**Comment by RaijiMagiwind** [comment]
Yes, I redeemed the official second code that registers the full expansion on Mog Station after the early access. I 'redeemed'/confirmed the activation code for it as soon as it was available for me to redeem. 
The game shows the Endwalker screen with no issues if I use the normal launcher. Its only the FFXIVLauncher that has the issue.

I run on Windows 11, and I have run the launcher both in normal and in admin mode to see if that could be an issue. Same either way.

**Comment by goaaats** [comment]
I assume this is resolved now, if it's not, please let us know
