### ISSUE TITLE
Limit Download Speed

### ISSUE THREAD

**Issue by Irame** [goatcorp/FFXIVQuickLauncher#633]
It would be nice if the dowload speed of FFXIV updates could be limitet.

**Comment by Caraxi** [comment]
good news
![image](https://user-images.githubusercontent.com/11886749/145729925-2e4bf641-99e4-4cae-b4bd-9508983cdd04.png)

**Comment by Irame** [comment]
Oh, I haven't seen this, sorry.
But if you started the download there is nor way to change the speed. A way to stop or better pause the download to then change the speed in the options and resume it would be enough for me.

**Comment by goaaats** [comment]
We'll definitely have a way to set it while downloading in the upcoming rework.
