### ISSUE TITLE
Screenshots not working after launcher update.

### ISSUE THREAD

**Issue by thecoint** [goatcorp/FFXIVQuickLauncher#655]
updated the launcher yesterday and now I can’t take screenshots as it just says screenshot failed. but if I use the official launcher from square screenshots work fine. 
a friend also updated his launcher and is having the same problem now.

**Comment by Soveia** [comment]
99% of these issues are caused by your antivirus. Add an exception and the issue should go away.

**Comment by reiichi001** [comment]
> 99% of these issues are caused by your antivirus. Add an exception and the issue should go away.

It could be, but there's a more likely cause!

This is likely a case of "@thecoint launched FFXIV as the Administrator user at least once" and it set all folder permissions to be Admin-only. Despite the fact that that shouldn't happen inside a user's own profile folders.

There are two ways to fix it:
1. Fix the ownership and permissions on the screenshots folder. 
2. Set the screenshot folder somewhere else, like a folder you know you have access to / on another drive that won't have to deal with weird windows permissions.
