### ISSUE TITLE
Still showing the japanese Shadowbringers Intro

### ISSUE THREAD

**Issue by NekoMiku39** [goatcorp/FFXIVQuickLauncher#656]
Even after I updated the XIVLauncher to the newest version it shows me the japanese Shadowbringers Intro instead of the Endwalker Intro. I also registered the Endwalker Collectors Edition on my Square Enix Account.

**Comment by reiichi001** [comment]
Do you have TitleEdit installed by any chance?

**Comment by NekoMiku39** [comment]
Found the Problem. Had the TitleEdit Plugin installed. Totally forgot about it xD
