### ISSUE TITLE
disable auto create shortcut on desktop when launching the launcher

### ISSUE THREAD

**Issue by Solid-Metal** [goatcorp/FFXIVQuickLauncher#667]
for some reason....FF14QuickLauncher always create new shortcut on desktop, i already checked the setting but theres no such option to disable it, i'm not sure why it does what it does, but i wish add function to disable it or just disable it all together, i like my desktop clean

**Comment by reiichi001** [comment]
You should stop running the setup.exe and instead use the actual bootrapper.

And start menu/taskbar entries should point to `C:\Users\<your windows username>\AppData\Local\XIVLauncher\XIVLauncher.exe`

**Comment by Solid-Metal** [comment]
> You should stop running the setup.exe and instead use the actual bootrapper.
> 
> And start menu/taskbar entries should point to `C:\Users\<your windows username>\AppData\Local\XIVLauncher\XIVLauncher.exe`

yep, you're absolutely right lol, never expect the real launcher is there, cheers !
