### ISSUE TITLE
XIV Randomly Exiting when Idle.

### ISSUE THREAD

**Issue by Rekuja** [goatcorp/FFXIVQuickLauncher#679]
The game completely exits when I'm idle for 4-5 minutes (away from PC)
Definitely not hitting the AFK timer.

Latest XIV Launcher
Only 1 Plugin: NoClippy

Log doesn't show anything abnormal, can attach if needed but didn't see the point.

Doesn't happen using official launcher.

**Comment by reiichi001** [comment]
NoClippy is not a supported plugin. We cannot verify if it is causing your issue or not. You'll need to remove it and try to reproduce the issue without it.
