### ISSUE TITLE
Game crashes immediately afte the "SQUARE ENIX" logo

### ISSUE THREAD

**Issue by PSLink1** [goatcorp/FFXIVQuickLauncher#680]
Hello,
I'm having a problem with booting the game throught the XIVLauncher for a while now (2 weeks).
The game crashes right afte the "Square Enix" logo appears.
It doesn't saw me any error messages, it just close the game's window. 
I have done some of the troubleshootings methods but there were all in vain.... (making exclusion's etc. Even reinstalling the game)
In my second device (laptop) the Launcher is booting normaly like it should do.

Is there a way to fix this issue?

Thank you in advance.

PC's Info having the crashe:

  Operating System: W10
  XIVLauncher version: v6.1.10.0
  Launching as admin?: Yes
  Using Steam?: No
  Addons/Plugins enabled: Yes

**Comment by nubgamerz** [comment]
While I don't have crashes, since the last update, I've noticed that after the Square Enix logo, the game freezes for a good second or two on the main menu while it injects the mods. This didn't happen prior to the latest update. Perhaps my issue is similar to that of yours.

**Comment by thealtsalt** [comment]
This is also happening to me, but it's happening as of today. Jan. 9th 2022 2:30am EST. It has worked fine nearly every day since about 3 months ago when I initially downloaded it. The game launches, gets to the SquareEnix Logo screen and stops responding. However, the game works fine without the launcher. I also noticed, if I launch the game normally then start the game through the launch it works. This is very strange behavior.

OS: Win10
XIVlauncher ver: 6.1.15.0
Launching as admin: no
Steam: no
Plugins enable: yes.

**Comment by reiichi001** [comment]
It would be immensely useful for you two to upload your `dalamud.log` files from `%appdata%\XIVLauncher\` here for review. ...or to ask in the #xivlauncher-help channel on our discord, as freezes on the logo screens usually comes down to maybe 2 things:
1. A plugin is failing to load and taking everything down with it
2. Another program is causing Dalamud to fail to load (antivirus, rivatuner, fraps, etc)

**Comment by thealtsalt** [comment]
I am unsure how to upload files. Also is the strange behavior of it working after i launch it without XIV launcher then with that running launch it with leads me to believe that the things you listing arent applicable. However, i will disable my plugins and turn off rivatuner to see. when i get the opportunity.

**Comment by goaaats** [comment]
Rivatuner crashes are common, there's no real solution yet other than to disable it or tweak injection delays.
