### ISSUE TITLE
XIVlauncher crashes instantly after update check passes when launched

### ISSUE THREAD

**Issue by Ammar1313** [goatcorp/FFXIVQuickLauncher#684]
After clicking on then launcher it checks for update then stops responding and crashes asap with no errors what's so ever, started happening after I got disconnected yesterday with a 2002 error in game. 

I tried uninstalling and reinstalling the launcher with no luck so far.

**Comment by reiichi001** [comment]
XIVLauncher had a recent update (and Dalamud did too).

If you normally need to make exceptions for your antivirus, you may need to adjust those to match the current versions.

Your `%appdata%\xivlauncher\output.log` (for launcher issues) file would also be handy as we can see where the launcher is dying.

**Comment by Ammar1313** [comment]
Thank you replying so quick, I'm using windows defender and already whitelisted the launcher in the firewall.

I'll attack the output.log file for you to see and thank you again.

[output.log](https://github.com/goatcorp/FFXIVQuickLauncher/files/7803708/output.log)
.

**Comment by Ammar1313** [comment]
I figured out the issue, I closed/uninstalled RivaTuner and and everything works fine so far.
