### ISSUE TITLE
SquareEnix has shutdown all plugins

### ISSUE THREAD

**Issue by xkhsvcct** [goatcorp/FFXIVQuickLauncher#685]
It would appear that SquareEnix has shutdown all plugins today (01/04/22) in preparation for patch 6.05 tonight (9pm-3am).  The message comes up on the upper left hand corner of the screen during login.  So any issues you are having with this plugin are Square's fault.  Doesn't make any sense why they would shutdown plugins before they even start updating.

**Comment by nubgamerz** [comment]
Square Enix hasn't shut down anything, the update has already been released.

The message comes up, because we need to wait for the plugins to be updated to be compatible with the latest version of the game.

**Comment by sgtdeagle** [comment]
at least on my end they are active again, (enabled)

**Comment by xkhsvcct** [comment]
Everything is working fine now.

Thanks

**Comment by Braste** [comment]
For anyone wondering, SE can't "shutdown" plugins. If they could, there would be any plugin, because they are against SEs TOS. The messages in the upper left corner comes from starting the game with XIVLauncher, not from the game itself. Wanted to say that just in case someone comes across this Issue.

**Comment by SpunkyNoodle** [comment]
> It would appear that SquareEnix has shutdown all plugins today (01/04/22) in preparation for patch 6.05 tonight (9pm-3am). The message comes up on the upper left hand corner of the screen during login. So any issues you are having with this plugin are Square's fault. Doesn't make any sense why they would shutdown plugins before they even start updating.

lmao, this has nothing to do with SE. This launcher does game version check, it will auto disable whatever is not tested for future patches.
