### ISSUE TITLE
[Linux] Transmission in progress dialog window remains after login is completed

### ISSUE THREAD

**Issue by herbertstew** [goatcorp/FFXIVQuickLauncher#698]
This problem has been happening for a few versions of xivlaucher, I'm currently using the latest version 6.1.16 . After I log in it shows that window but the window never disappears even after log in is complete and it starts downloading patches. It can't be minimized and it only goes away when I kill the process.

![Screenshot_2022-01-23_00-35-01](https://user-images.githubusercontent.com/79783324/150657917-89206f33-4fbc-4c10-ab5d-6558cb04ff04.png)

![Screenshot_2022-01-23_00-35-19](https://user-images.githubusercontent.com/79783324/150657910-f902f44f-b8a9-4c03-a47c-db7a7575baf1.png)

OS is Linux Mint 20.1 XFCE

edit: forgot to mention that this is through lutris version 0.5.9.1

**Comment by Codex100** [comment]
I have the same issue on windows 10 but mine won't go away even if I kill the process.

**Comment by goaaats** [comment]
This should be fixed
