### ISSUE TITLE
Dalamud update progress indicator

### ISSUE THREAD

**Issue by Purple4789** [goatcorp/FFXIVQuickLauncher#700]
What is your suggestion/feature request?
Add progress bar showing the amount of time needed to download durning dalamud updating assets.

Describe how you'd like this to work

- [ ] Progress bar showing total completion from 0 to 100% 
- [ ] Download speed estimate for slower internet

**Comment by reiichi001** [comment]
Under normal circumstances, a user would never see the window. DalamudAssets is ~25MB, with the bulk of the data being a 17MB font that will never need to be downloaded by the user. The asset files that would be obtained are a few < 10 kb text files.

Dalamud on the other hand, is ~17MB and is updated fairly regularly as needed. Sometimes multiple times during recent patches. 

XIVLauncher begins downloading the .Net runtime, DalamudAssets, and Dalamud once the launcher window is open, provided Dalamud is enabled.

**Comment by Purple4789** [comment]
Thanks for the insightful info.

Then i am probably on snail internet as i had to wait like 1 hour to update.

**Comment by Purple4789** [comment]
Thanks for the insightful info.

Then i am probably on snail internet as i had to wait like 1 hour to update.

**Comment by Werneq** [comment]
In a early past sometimes my connection with github servers was very slow too, usually is a problem with your ISP.
I change my provider to fiber and did not happened again

**Comment by goaaats** [comment]
Done in v6.2.34
