### ISSUE TITLE
remote play/steam remote play

### ISSUE THREAD

**Issue by gurkburk76** [goatcorp/FFXIVQuickLauncher#724]
**What is your suggestion/feature request?**
Would it (in the future?) be possible to somehow stream the game as you canwith the original client in steam?

**Describe how you'd like this to work**
The same way i can sit with a laptop logged into steam and "remote" my main pc, aka as "streaming" the game.

**Comment by goaaats** [comment]
Does this not work right now if you add XL to Steam as a non-Steam game?

**Comment by gurkburk76** [comment]
Yes it does, i wasen't aware that you can do that.
Closing... :)

**Comment by PSzczepanski1996** [comment]
For me for some reason it's not working while trying to connect to steam deck, not sure why :/
