### ISSUE TITLE
Launcher windows are black, UI elements get shown when hovering over them (Lutris/Wine)

### ISSUE THREAD

**Issue by sgilissen** [goatcorp/FFXIVQuickLauncher#732]
**Describe the bug here:**
``When trying to use the launcher, all of the windows are black, and sometimes transparent (I.E.: Loading window, OTP window). When hovering over the UI elements with the mouse, they become visible sometimes ``

**Steps to reproduce the bug:**
Example:
```
1. Start the launcher
2. Issue is visible immediately
```

**Expected behavior**
Example: ``UI elements should be visible at all times``

**Screenshots**
Example:
![Error window](https://i.imgur.com/RH5Vmm8.png)
![Main window](https://imgur.com/VRQ68ut.png)
![Check for updates window](https://imgur.com/ScH1jXB.png)

**Other information (*please* complete the following information):**
  Operating System: Fedora 35, running through Lutris (Wine 6.16, and also tried 7.1)
  XIVLauncher version: 6.2.0
  Launching as admin?: /
  Using Steam?: No
  Addons/Plugins enabled: -

**Additional information**
I have tried a full reinstall of both the game and XIVLauncher, under different wine bottles, partly for troubleshooting a different issue (https://github.com/goatcorp/FFXIVQuickLauncher/issues/725)
Will try a different desktop environment as well, to be sure.

Edit: Added another screenshot of the "checking for updates" window. Sorry for the cursed image, it just happened to be on that part of my wallpaper.

**Comment by sgilissen** [comment]
Update:
I can confirm that the same issue happens on multiple desktop environments. 
Specifically, I've tried: 
Cinnamon (on X)
Gnome (both on X and Wayland)
KDE Plasma (Wayland)

**Comment by reiichi001** [comment]
That issue happens when WPF hardware accelerated rendering is enabled, which shouldn't happen on wine, where we specifically set software rendering. 

If you've been swapping the wine rubber version in your prefix a lot, something may have gotten messed up. 

I would recommend making a new prefix and migrating over FFXIV, your character config, and only plugin config from xivlauncher/dalamud if applicable.

**Comment by sgilissen** [comment]
Thanks, @reiichi001 

I didn't have to create a new prefix. 
After some Google-fu I managed to find the solution. 

In a Bash terminal for your prefix, run the following command:

```wine reg add "HKCU\\SOFTWARE\\Microsoft\\Avalon.Graphics" /v DisableHWAcceleration /t REG_DWORD /d 1 /f```

That fixed the issue :-)
