### ISSUE TITLE
Error on exit

### ISSUE THREAD

**Issue by GlitchedForDays** [goatcorp/FFXIVQuickLauncher#746]
Everytime I quit ffxiv I receive a fatal error. This has only started happening after the recent maintenance.
<img width="533" alt="Error Code" src="https://user-images.githubusercontent.com/64620528/157596187-17fa1797-e691-4964-963d-17d59f5289cf.png">

**Comment by reiichi001** [comment]
This informational window was added in a recent XIVLauncher release a couple days ago. It's supposed to be off by default, but that hasn't been the case for some users. You can mostly ignore it or use the "don't ask again" button to keep it hidden.
