### ISSUE TITLE
Getting a error 5003

### ISSUE THREAD

**Issue by kingeibon** [goatcorp/FFXIVQuickLauncher#788]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to FFXIV updating and plugins not working correctly.

### What did you do?

I had played on the laucher on my laptop, then i needed a setting transfered from my console. so i logged out, sighned in on console, uploaded the thing to the cloud, then logged out. once i opened the game and chose "start" i got a 5003 "authentication error." The error does not occur when launching the game normally on either my laptop or console, it is the launcher that makes the issue.

### Platform

Windows

**Comment by goaaats** [comment]
Disable the UID cache in the about page of the launcher settings
