### ISSUE TITLE
This Square Enix account cannot play FFXIV

### ISSUE THREAD

**Issue by megasxlr** [goatcorp/FFXIVQuickLauncher#789]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to FFXIV updating and plugins not working correctly.

### What did you do?

I copied and pasted my username and password form the steam launcher and it say I cannot play the game.
What do?

### Platform

Windows

**Comment by reiichi001** [comment]
We'll need more information.

Did you purchase FFXIV off Steam? (Or get the free trial from Steam)

Is this a Free Trial account? Was it made for Windows, Steam, or macOS?

Are you able to login using the official launcher? 

Are you able to login on the Mog Station and see that your subscription is active? (Skip if trial account)

**Comment by megasxlr** [comment]
FFXIV is off steam so I purchased it there, I have bought and subscribed tot he newest version of the game.
I can login and play the game through the official launcher provided by steam.
mog station is fine.

**Comment by reiichi001** [comment]
Did you check the "Use Steam Service Account" button in XIVLauncher's main window? The same applies to the "Use One-Time-Passwords" checkbox if you have a security token/MFA app for your SQEX account.

**Comment by megasxlr** [comment]
> Did you check the "Use Steam Service Account" button in XIVLauncher's main window? The same applies to the "Use One-Time-Passwords" checkbox if you have a security token/MFA app for your SQEX account.

when I launch my FFXIV Launcher, only three boxes exist:
ID:
Pass:
one-time pass:

**Comment by megasxlr** [comment]
I also launch through steam so I think it should be checked by default by that interaction.

**Comment by reiichi001** [comment]
For XIVLauncher, you need to manually tell it that you have a Steam Service Account. It cannot make that guess for you.
![image](https://user-images.githubusercontent.com/10376708/161354266-38a0caa3-9c8e-4b05-893b-953b8bde6869.png)

**Comment by megasxlr** [comment]
Oh you mean the quick launcher

**Comment by megasxlr** [comment]
ok it is playing so I guess that fixed it

**Comment by megasxlr** [comment]
btw where is a site for all the plugins or is it soley in-game

**Comment by reiichi001** [comment]
Plugin management is handled in-game. There's also <https://github.com/goatcorp/DalamudPlugins/blob/api5/plugins.md> if you want to browse them online, but you can't install them that way.

**Please do not manually install any plugins.**

And while Dalamud has support for custom plugin repositories, we generally do not provide support for any of them and if you encounter issues and ask us for help, we will ask you to disable all of them first.
