### ISSUE TITLE
ffxiv Won't launch

### ISSUE THREAD

**Issue by lizleka95** [goatcorp/FFXIVQuickLauncher#793]
Just keeps telling me to check the faq and report the issue not helping need help.

**Comment by ackwell** [comment]
Well; did you check the FAQ, or indeed report the issue?

I, nor likely anybody else, has any interest in playing 20Questions with you to work out your issue.

Please check [the faq](https://goatcorp.github.io/faq/xl_troubleshooting) to see if the issue you are having is covered there.

If it is not, please _report the issues_, which notably would include the errors and details requested as part of the issue template you bypassed to post this message.

**Comment by reiichi001** [comment]
It would help if you gave us anything to work with. Like even if you had filled out the issue template to start. 

What platform? (Windows, Linux, Steam on Windows)

Do you have a steam service account?

What's the actual error? (Take a screenshot or copy the text)

Then in XIVLauncher's main window, click on the settings gear, go to the about tab, and click on the large XIVLauncher picture. It will generate a troubleshooting pack for us. Please upload that file here.
