### ISSUE TITLE
Plugin to make an AUDIO and/or VISUAL QUE when you successfully hit a POSTIONAL would be amazing!

### ISSUE THREAD

**Issue by OzenScythe** [goatcorp/FFXIVQuickLauncher#796]
### Update disclaimer

- [X] Yes, I have checked and my request is not related to FFXIV updating and plugins not working correctly.

### What happened, what did not, what did you want to happen?

As the title implies,

Having a nice Plugin compatible with FFXIV Launcher Plugin to emit a sound / visual que when successfully hitting positional would not only make hitting positionals easier to go for (when you get into a nice rhythm) but can make playing classes that require positionals have added placebo "weight" to their attacks. 

It will make it feel really bad when you miss or don't hit one due to boss positioning or human error but will create rewarding experience to those who do. 

I recommend adding some nice audio presets, but giving the user their own ability to add small custom audio samples as well if possible for more creativity and personalization for the user.

Let me know what you think of this idea! Thank you ! 

### Version

Standard version (Windows, Lutris)

### Platform

Windows

**Comment by reiichi001** [comment]
This is not the correct place to submit a plugin request. 

Please resubmit on https://github.com/goatcorp/suggestions
