### ISSUE TITLE
"Invalid window identifier" bug. Auto closes launcher, can't download the new patch.

### ISSUE THREAD

**Issue by reiazevedo** [goatcorp/FFXIVQuickLauncher#810]
System.ComponentModel.Win32Exception (0x80004005): Invalid window identifier
   em MS.Win32.UnsafeNativeMethods.GetMessageW(MSG& msg, HandleRef hWnd, Int32 uMsgFilterMin, Int32 uMsgFilterMax)
   em System.Windows.Threading.Dispatcher.GetMessage(MSG& msg, IntPtr hwnd, Int32 minMessage, Int32 maxMessage)
   em System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   em System.Windows.Application.RunDispatcher(Object ignore)
   em System.Windows.Application.RunInternal(Window window)
   em XIVLauncher.App.Main()

Version: 6.2.26.0
Git Hash: 6.2.26-0-g6018dd3
Context: Unhandled
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY XIV Online

**Comment by goaaats** [comment]
Does this always happen?

**Comment by reiazevedo** [comment]
> Does this always happen?

I recently tried again with the newest version and the problem seems to have gone away for now. Closing the issue.

**Comment by reiazevedo** [comment]
The error came back, now with a slightly different error message:
`System.ComponentModel.Win32Exception (0x80004005): O identificador da janela é inválido
   em MS.Win32.UnsafeNativeMethods.GetMessageW(MSG& msg, HandleRef hWnd, Int32 uMsgFilterMin, Int32 uMsgFilterMax)
   em System.Windows.Threading.Dispatcher.GetMessage(MSG& msg, IntPtr hwnd, Int32 minMessage, Int32 maxMessage)
   em System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   em XIVLauncher.App.DalamudOverlayThreadStart() na D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\App.xaml.cs:linha 265
   em System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   em System.Threading.ThreadHelper.ThreadStart()

Version: 6.2.29.0
Git Hash: 6.2.29-0-g9a065db
Context: Unhandled
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: English
Game path: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY XIV Online
`

**Comment by Troloxbeta** [comment]
Also with me. After uninstalling and reinstalling the error appeared and the game does not open by quick luncher.

System.ComponentModel.Win32Exception (0x80004005): O identificador da janela é inválido
   em MS.Win32.UnsafeNativeMethods.GetMessageW(MSG& msg, HandleRef hWnd, Int32 uMsgFilterMin, Int32 uMsgFilterMax)
   em System.Windows.Threading.Dispatcher.GetMessage(MSG& msg, IntPtr hwnd, Int32 minMessage, Int32 maxMessage)
   em System.Windows.Threading.Dispatcher.PushFrameImpl(DispatcherFrame frame)
   em XIVLauncher.App.DalamudOverlayThreadStart() na D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\App.xaml.cs:linha 265
   em System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   em System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   em System.Threading.ThreadHelper.ThreadStart()

Version: 6.2.29.0
Git Hash: 6.2.29-0-g9a065db
Context: Unhandled
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: Portuguese
Game path: C:\Program Files (x86)\Steam\steamapps\common\FINAL FANTASY XIV Online

**Comment by reiazevedo** [comment]
Some more info: Rebooting my PC and then starting the launcher before anything else works. I'm guessing it's a conflict with one of my programs. I'll do some further testing to try to pinpoint which one it is.

**Comment by NotNite** [comment]
Tracking in #912.
