### ISSUE TITLE
Unexpected error has occurred.

### ISSUE THREAD

**Issue by himesuga** [goatcorp/FFXIVQuickLauncher#812]
Error occurs when closing the game.

![image](https://user-images.githubusercontent.com/103502465/162944613-8804d642-1e99-4f8c-8e32-9a436ee39e4e.png)
![image](https://user-images.githubusercontent.com/103502465/162944652-51951fd6-c6ea-44c6-ad16-1415dc35521e.png)
![image](https://user-images.githubusercontent.com/103502465/162944679-bd407e58-e0f4-4556-b96d-f7b66fb0ccbe.png)

**Comment by goaaats** [comment]
#815
