### ISSUE TITLE
System.InvalidOperationException

### ISSUE THREAD

**Issue by Luobiniya** [goatcorp/FFXIVQuickLauncher#819]
System.InvalidOperationException: 這個物件並未啟動處理序，所以無法判斷其所要求的資訊。
   於 System.Diagnostics.Process.EnsureState(State state)
   於 System.Diagnostics.Process.get_ExitCode()
   於 XIVLauncher.Windows.ViewModel.MainWindowViewModel.<TryProcessLoginResult>d__25.MoveNext() 於 D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs: 行 602

Version: 6.2.28.0
Git Hash: 6.2.28-0-gd8cb058
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: Japanese
LauncherLanguage: TraditionalChinese
Game path: D:\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

**Comment by goaaats** [comment]
#815
