### ISSUE TITLE
Lavish Software Crash

### ISSUE THREAD

**Issue by nlagee** [goatcorp/FFXIVQuickLauncher#822]
Currently using Lavish software (update). Both crash upon attempting to open the game

System.ComponentModel.Win32Exception (0x80004005): Access is denied
   at XIVLauncher.Common.Game.NativeAclFix.LaunchGame(String workingDir, String exePath, String arguments, IDictionary`2 envVars, DpiAwareness dpiAwareness, Action`1 beforeResume) in C:\goatsoft\xl\XIVLauncher.Common.Windows\NativeAclFix.cs:line 468
   at XIVLauncher.Common.Windows.WindowsGameRunner.Start(String path, String workingDirectory, String arguments, IDictionary`2 environment, DpiAwareness dpiAwareness) in C:\goatsoft\xl\XIVLauncher.Common.Windows\WindowsGameRunner.cs:line 24
   at XIVLauncher.Common.Game.Launcher.LaunchGame(IGameRunner runner, String sessionId, Int32 region, Int32 expansionLevel, Boolean isSteamServiceAccount, String additionalArguments, DirectoryInfo gamePath, Boolean isDx11, ClientLanguage language, Boolean encryptArguments, DpiAwareness dpiAwareness) in C:\goatsoft\xl\XIVLauncher.Common\Game\Launcher.cs:line 264
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<StartGameAndAddon>d__30.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at XIVLauncher.Windows.ViewModel.MainWindowViewModel.<TryProcessLoginResult>d__25.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:line 600

Version: 6.2.28.0
Git Hash: 6.2.28-0-gd8cb058
Context: Login
OS: Microsoft Windows NT 10.0.19043.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? False
Language: English
LauncherLanguage: English
Game path: D:\FINAL FANTASY XIV - A Realm Reborn

**Comment by nlagee** [comment]
Here is the Innderspace Error


Software: Inner Space Session 1.19 (Wed Mar 30 13:12:43 2022)
Crash: 0x32C2AD18: Exception 0xc0000005 writing to address 0x32C2AD18

Registers:
-----------------------------------
rax=     20E5D4FBCA0 rbx=               0 rcx=      AE0C9FB280 rdx=    7FFAB01FBF20
rdi=               1 rsi=    7FFAB02010D8 rbp=      AE0C9FB320 rsp=      AE0C9FB238

Stack:
-----------------------------------
    7FFAB003CEA4       AE0C9FB280     7FFAB01FBF20                8                6         8007000E     7FFAAFFCE706      20E5D9E47A8
               0      20E00000000     7FFAB003B670       1400000000     7FFAAFF70000                0                0                2
               0     7FFAB02010D8                2       AE0C9FB3C0     7FFAAFFCAE47                0       AE0C9FB320       AE0C9FB3C0
            824C      20E5D9E3C90     7FFAB00149F0      20E5D9E3C90     7FFAB02714E0     7FFAB01FBEA0      20E5D9E3C90       AE0C9FB3E9
    7FFAAFFCB7C8                2      20E5D9E3C90      20E5D9E47A8      20E5D9A6AB0      20E5AF90000     7FFAB0202710               28
               0     7FFAAF729101                0      20E5AF90000     7FFAB0BAA7DD                0     7FFAB01C36F8       AE0C9FB400
               2      20E5D9E3C90     7FFA00000002                0                2       AE0C9FB450         41DE0E2B       AE0C9FB400
               0           140014      20E5AF9AEB0         41DE0E2B     4AD6F304AB91                1         41DE0E2B           33105C
     20E5D92FC10      20E5B93DC30     7FFAAFFCB5B8     7FFAAF729101                0                2                0      20E5D497CB0
               0       AE0C9FB541          33311E4                0     7FFAAF729000             1000                8       AE0C9FB4C0
         3443C30      20E00000004      20E5B266370      20E5B265370                0     7FFAAFF70000                8     7FFAAFFCB560
616974696E496F43     7845657A696C                E                F       AE0C9FB618     7FFAAF700000          332366D                0
    A0D3EF67B0C4          3443C30                0     7FFAAE70EF30           33105C      20E5D92FC10     7FFAAF700000     7FFAAF7291C8
               0     7FFAAF721D84          3336EE0                0     7FFAAF721D84                1     7FFAAF700000     7FFAAF721D84
     20100000001        20F000000     7FFAAF7291C8 FFFFFFFFFF671E9D  401670100000BE4                1         41DE0E2B      20E5D92FC10
               1      20E5B93DC30     7FFAAF705692     7FFAAFFCB560      20E5B2652D0                0 FFFFFFFF000000CE     7FFAAF7291C8
     20E00000000                1     7FFAAF705EDC      20E5B2D0000      20E5D92FC10                1       AE0C9FB790                0
               0                0                0                0                0     4AD6F304AC81                0      20E5D92FC10
    7FFAAF703E5E                0                2      20E5B93DC30                1      20E5D92FC10     7FFAAF703E04                0
               1       AE0C9FB780        300000004                0     7FFAAF703B3E                6                1                0
               1       1C00000000        D00000000                0                0                0                0       AE0C9FB788
    7FFAAFD76FD3     7BE700000001      20E5D942700      50000000000     7007698CFDF0         FFFFFFFF     7FFAAF7024DF      20E5D92FC10
     20E5CE85390             824C     7FFAAACF71F4         C000000F             41DE           1A1886      20E5B208828              287
               0           33105C     7FFAAFD5A0D6         41DE0E2B       AE0C9FB940                1              E2B         41DE0E2B
    7FFAAFD5A2B1                0           33105C     7FFAAFD5C260                1      15000000000      BE400000BE4 5021108400000BE4
               0                0          500C018                0     7FFAB0BA9877                6     7FFAAFD5F8E5            10000
               0       1100000060     7FFAB0BA9993           33105C        300000086                1 FFFFFFFFFFFFFFFF      4B000000004
    7FFAAFD5C260                0                1       1C00000000        D00000011                D          3318504       AE0C9FBE30
    7FFAAFD5FC2D                0               17      20E5B90E800                0                0           33105C     C2D625701539
    7FFAAFD62AAE                1                6           33105C           33105C       AE0C9FBB08     7FFAAFD629F0                1
               1                0                1               86           33105C       AE0C9FBB08     7FFAAACFB271                0
8000601000000000                0                0          33182F0           33105C               48     7FFA00000001                0
               0               70 FFFFFFFFFFFFFFFF FFFFFFFFFFFFFFFF     7FFAAFA5BA6F     7FFAAFD629E2                1                1
    7FFAB0BA9877      20E5B90E800     7FFAAFD6218D                0       AE0C9FBB08      20E5B90E800           1A1886      20E5B946CE0
             287     5D166ED9F582     7FFAAF704A44      20E5B946CE0      20E5B208828               17              287           33105C
    7FFAAFD5B0FF              287           33105C               17                6                0                1                0
               0                0     7FFAAFD5AF6F           33105C       AE0C9FC048              287               17     C2D600000000
               0         80006010     7FFAAFD5E858                1                0                1                0                0
               0 8000601000000000                0                0                0 8000601000000000                0                0
               0                0                0                0                0             B9A0             B997                1
     20E5B1D0000              B9A     7FFAB0BBB44D      20E5B1D0000     7FFAAE7086FE     7FFAB0C2CB00                0               48
      AE00000001     7FFAB0C2CBA0                0               48 FFFFFFFF00000001                0                0               30
FFFFFFFFFFFFFFFF FFFFFFFFFFFFFFFF     7FFAAFD5E703                0                0                0                0                0
               0         40000000         80000000         C0000008     7FFAAFD5E3DC                0     7FFAB0C2CBA0           1A1886
    5D1600000287               17           33105C                1     7FFA00000001                0                0                0
    7FFAAFD70BC3                0                0               17                0     7FFAB0C2CBA0     7FFAAFDE1070       AE0C9FBE38
               0                0     7FFAAFDE1070      20E5D8F3060     7FFAB0C30BA4       AE0C9FBE18       1100000050     7FFAAE6714C4
         33030EA       AE0C9FBE38        200000030     7FFAAE6714C4      20E5B90E800               47       AE0C9FBE68           33105C
     20E5B946CE0              287               17           33105C     7FFAB0C2CBA0     7FFAB0C2CC60          3318474                1
    7FFAAFD70BDB                0       AE0C9FC048                0   74006100000000     7FFA00000041   6F007900200065      20E5D8F2920
     20E5D9D80E0                0             5CB7             5CB7     A0D3EF67BA24                1     7FFAAFD6297F                1
               1                0                1       AE0C9FBF40       AE0C9FBF48   74006300610078     7FFAAFD5B480        100000000
8000601000000000                0                0          33182F0     7FFAB0C2CB80               48     7FFA00000001                0
               0               30 FFFFFFFFFFFFFFFF FFFFFFFFFFFFFFFF     7FFAAFD62892                0              1E5                1
               0            7161A     7FFAAFD620C2                0          33182F0              110      20E5B90E800            7161A
               0                1       AE0C9FC020                0                0                0                0     5D166ED9F212
    7FFAAFD5B30F     C2D6257012E9                0                0              110                0            7161A              110
               0       AE0C9FC2C0     7FFAAFD61FD6                0         80006010   74006100740053           630069     C2D600000000
               0         80006010     7FFAAFD5E858                1                0                1                0      20E5DAA0DC0
    7FFAAE3C73EE FFFFFFFF84012439                D                0                0 8000601000000000                0                0
             BE4                0     7FFAAF2C0000     C2D625701659     7FFAB0BA05B3                0     7FFAAF2C0000     7FFAB0C2CB80
    7FFAAF2D3810               48     7FFA00000001                0                0               70 FFFFFFFFFFFFFFFF FFFFFFFFFFFFFFFF
    7FFAAFD5E703     7FFAB0C2CB00     7FFAAFD63EAB               48      20E00000001                0                0               30
FFFFFFFFFFFFFFFF FFFFFFFFFFFFFFFF     7FFAAFD5E703                0     7FFAB0C2CB80                0      20E5B90E800     7FFA00000000

Module addresses in stack:
-----------------------------------
combase.dll+CCEA4
combase.dll+28BF20
combase.dll+5E706
combase.dll+CB670
combase.dll+2910D8
combase.dll+5AE47
combase.dll+A49F0
combase.dll+3014E0
combase.dll+28BEA0
combase.dll+5B7C8
combase.dll+292710
IMM32.DLL+29101
ntdll.dll+1A7DD
combase.dll+2536F8
combase.dll+5B5B8
IMM32.DLL+29101
InnerSpace.dll+311E4
IMM32.DLL+29000
InnerSpace.dll+143C30
combase.dll+5B560
InnerSpace.dll+2366D
InnerSpace.dll+143C30
KERNELBASE.dll+6EF30
IMM32.DLL+291C8
IMM32.DLL+21D84
InnerSpace.dll+36EE0
IMM32.DLL+21D84
IMM32.DLL+21D84
IMM32.DLL+291C8
IMM32.DLL+5692
combase.dll+5B560
IMM32.DLL+291C8
IMM32.DLL+5EDC
IMM32.DLL+3E5E
IMM32.DLL+3E04
IMM32.DLL+3B3E
USER32.dll+26FD3
IMM32.DLL+24DF
uxtheme.dll+71F4
USER32.dll+A0D6
USER32.dll+A2B1
USER32.dll+C260
ntdll.dll+19877
USER32.dll+F8E5
ntdll.dll+19993
USER32.dll+C260
InnerSpace.dll+18504
USER32.dll+FC2D
USER32.dll+12AAE
USER32.dll+129F0
uxtheme.dll+B271
InnerSpace.dll+182F0
MSCTF.dll+BA6F
USER32.dll+129E2
ntdll.dll+19877
USER32.dll+1218D
IMM32.DLL+4A44
USER32.dll+B0FF
USER32.dll+AF6F
USER32.dll+E858
ntdll.dll+2B44D
KERNELBASE.dll+686FE
ntdll.dll+9CB00
ntdll.dll+9CBA0
USER32.dll+E703
USER32.dll+E3DC
ntdll.dll+9CBA0
USER32.dll+20BC3
ntdll.dll+9CBA0
USER32.dll+91070
USER32.dll+91070
ntdll.dll+A0BA4
win32u.dll+14C4
InnerSpace.dll+30EA
win32u.dll+14C4
ntdll.dll+9CBA0
ntdll.dll+9CC60
InnerSpace.dll+18474
USER32.dll+20BDB
USER32.dll+1297F
USER32.dll+B480
InnerSpace.dll+182F0
ntdll.dll+9CB80
USER32.dll+12892
USER32.dll+120C2
InnerSpace.dll+182F0
USER32.dll+B30F
USER32.dll+11FD6
USER32.dll+E858
gdi32full.dll+173EE
ntdll.dll+105B3
ntdll.dll+9CB80
GDI32.dll+13810
USER32.dll+E703
ntdll.dll+9CB00
USER32.dll+13EAB
USER32.dll+E703
ntdll.dll+9CB80

System:
-----------------------------------
Windows Version: Windows 10 Enterprise//19041.vb_release.191206-1406
System Physical RAM: 50831/65409MB
Page File: 41605/75137MB
Virtual Memory: 134213396/134217727MB (Extended: 0MB)
CPU 1: AMD Ryzen Threadripper 3970X 32-Core Processor  @ 3700MHz
CPU 2: AMD Ryzen Threadripper 3970X 32-Core Processor  @ 3700MHz
CPU 3: AMD Ryzen Threadripper 3970X 32-Core Processor  @ 3700MHz
CPU 4: AMD Ryzen Threadripper 3970X 32-Core Processor  @ 3700MHz
CPU 5: AMD Ryzen Threadripper 3970X 32-Core Processor  @ 3700MHz
CPU 6: AMD Ryzen Threadripper 3970X 32-Core Processor  @ 3700MHz
CPU 7: AMD Ryzen Threadripper 3970X 32-Core Processor  @ 3700MHz
CPU 8: AMD Ryzen Threadripper 3970X 32-Core Processor  @ 3700MHz
CPU 9: AMD Ryzen Threadripper 3970X 32-Core Processor  @ 3700MHz
CPU 10: AMD Ryzen Threadripper 3970X 32-Core Processor  @ 3700MHz
CPU 11: AMD Ryzen Threadripper 3970X 32-Core Processor  @ 3700MHz
CPU 12: AMD Ryzen Threadripper 3970X 32-Core Processor  @ 3700MHz
CPU 13: AMD Ryzen Threadripper 3970X 32-Core Processor  @ 3700MHz
CPU 14: AMD Ryzen Threadripper 3970X 32-Core Processor  @ 3700MHz
CPU 15: AMD Ryzen Threadripper 3970X 32-Core Processor  @ 3700MHz
CPU 16: AMD Ryzen Threadripper 3970X 32-Core Processor  @ 3700MHz
CPU 17: AMD Ryzen Threadripper 3970X 32-Core Processor  @ 3700MHz
CPU 18: AMD Ryzen Threadripper 3970X 32-Core Processor  @ 3700MHz
CPU 19: AMD Ryzen Threadripper 3970X 32-Core Processor  @ 3700MHz
CPU 20: AMD Ryzen Threadripper 3970X 32-Core Processor  @ 3700MHz
CPU 21: AMD Ryzen Threadripper 3970X 32-Core Processor  @ 3700MHz
CPU 22: AMD Ryzen Threadripper 3970X 32-Core Processor  @ 3700MHz
CPU 23: AMD Ryzen Threadripper 3970X 32-Core Processor  @ 3700MHz
CPU 24: AMD Ryzen Threadripper 3970X 32-Core Processor  @ 3700MHz
CPU 25: AMD Ryzen Threadripper 3970X 32-Core Processor  @ 3700MHz
CPU 26: AMD Ryzen Threadripper 3970X 32-Core Processor  @ 3700MHz
CPU 27: AMD Ryzen Threadripper 3970X 32-Core Processor  @ 3700MHz
CPU 28: AMD Ryzen Threadripper 3970X 32-Core Processor  @ 3700MHz
CPU 29: AMD Ryzen Threadripper 3970X 32-Core Processor  @ 3700MHz
CPU 30: AMD Ryzen Threadripper 3970X 32-Core Processor  @ 3700MHz
CPU 31: AMD Ryzen Threadripper 3970X 32-Core Processor  @ 3700MHz
CPU 32: AMD Ryzen Threadripper 3970X 32-Core Processor  @ 3700MHz
CPU Affinity Mask: 0xFFFFFFFFFFFFFFFF
Video 1: //./DISPLAY1/AMD Radeon RX 6900 XT
Video 2: //./DISPLAY2/AMD Radeon RX 6900 XT
Video 3: //./DISPLAY3/AMD Radeon RX 6900 XT
Video 4: //./DISPLAY4/AMD Radeon RX 6900 XT
Video 5: //./DISPLAY5/AMD Radeon RX 6900 XT
Video 6: //./DISPLAY6/AMD Radeon RX 6900 XT
Video 7: //./DISPLAY7/AMD Radeon RX 6900 XT
Video 8: //./DISPLAY8/Citrix Indirect Display Adapter
Video 9: //./DISPLAY9/Citrix Indirect Display Adapter
Video 10: //./DISPLAY10/Citrix Indirect Display Adapter
Sound: 
DirectX: 4.09.00.0904
Internet Explorer: 9.11.19041.0

Loaded Modules:
-----------------------------------
Module 0x03300000-0x03458000: C:/Program Files (x86)/InnerSpace/x64/InnerSpace.dll (Wed Mar 30 13:12:43 2022)
Module 0x7FFA16D40000-0x7FFA17199000: D:/FINAL FANTASY XIV - A Realm Reborn/game/dxgi.dll (Mon Sep 20 14:58:39 2021)
Module 0x7FF61A360000-0x7FF61CF3B000: D:/FINAL FANTASY XIV - A Realm Reborn/game/ffxiv_dx11.exe (Wed Apr  6 18:47:02 2022)
Module 0x7FFA36090000-0x7FFA362F3000: C:/Program Files (x86)/Razer/Razer Cortex/x64/d3dx9_43.dll (Fri May 21 22:37:58 2010)
Module 0x7FFA36300000-0x7FFA3656F000: C:/Program Files (x86)/Razer/Razer Cortex/x64/D3DCOMPILER_43.dll (Fri May 21 22:40:43 2010)
Module 0x7FFA4CF30000-0x7FFA4CFAF000: C:/Program Files (x86)/Razer/Razer Cortex/x64/d3dx10_43.dll (Fri May 21 22:28:54 2010)
Module 0x7FFA4CFB0000-0x7FFA4D007000: C:/Program Files (x86)/Razer/Razer Cortex/x64/EasyHook64.dll (Fri Jun  7 06:40:00 2019)
Module 0x7FFA4D010000-0x7FFA4D11E000: C:/Program Files (x86)/Razer/Razer Cortex/x64/k_fps64.dll (Mon Nov 22 07:57:45 2021)
Module 0x20E5E9E0000-0x20E5EE50000: C:/WINDOWS/System32/SETUPAPI.dll (Wed Feb 19 20:37:35 2053)
Module 0x7FFA73970000-0x7FFA7399C000: C:/WINDOWS/SYSTEM32/GLU32.dll (Tue Apr 23 01:13:12 2041)
Module 0x7FFA74520000-0x7FFA74646000: C:/WINDOWS/SYSTEM32/OPENGL32.dll (Wed Jul 14 22:34:24 2083)
Module 0x7FFA97F70000-0x7FFA980C2000: C:/WINDOWS/SYSTEM32/inputhost.dll (Tue Jun  2 08:45:29 2009)
Module 0x7FFA995C0000-0x7FFA99A96000: C:/WINDOWS/SYSTEM32/WININET.dll (Wed Apr 29 05:06:56 2076)
Module 0x7FFA9D360000-0x7FFA9D5FA000: C:/WINDOWS/WinSxS/amd64_microsoft.windows.common-controls_6595b64144ccf1df_6.0.19041.1110_none_60b5254171f9507e/comctl32.DLL (Tue Jul  9 05:23:59 2086)
Module 0x7FFA9DC00000-0x7FFA9DC45000: C:/WINDOWS/SYSTEM32/DINPUT8.dll (Tue Feb 19 16:37:00 2036)
Module 0x7FFA9DD80000-0x7FFA9DDAC000: C:/WINDOWS/SYSTEM32/dbgcore.DLL (Thu Apr  7 23:14:05 1988)
Module 0x7FFA9E030000-0x7FFA9E03C000: C:/WINDOWS/SYSTEM32/secur32.dll (Wed May  9 02:28:20 2035)
Module 0x7FFA9F820000-0x7FFA9F8D0000: C:/WINDOWS/WinSxS/amd64_microsoft.windows.common-controls_6595b64144ccf1df_5.82.19041.1110_none_792d1c772443f647/COMCTL32.dll (Fri Jan  3 16:27:34 2003)
Module 0x7FFAA4490000-0x7FFAA44B7000: C:/WINDOWS/SYSTEM32/WINMM.dll (Thu Mar 29 14:40:55 2068)
Module 0x7FFAA44C0000-0x7FFAA44CA000: C:/WINDOWS/SYSTEM32/VERSION.dll (Tue Oct 21 14:56:02 1980)
Module 0x7FFAA4EC0000-0x7FFAA4F3F000: C:/WINDOWS/System32/fwpuclnt.dll (Sun Apr  5 23:51:30 2043)
Module 0x7FFAA5B20000-0x7FFAA5C29000: C:/WINDOWS/SYSTEM32/WINHTTP.dll (Sat Aug 26 03:20:46 2090)
Module 0x7FFAA6040000-0x7FFAA616D000: C:/WINDOWS/SYSTEM32/mfperfhelper.dll (Sat Nov  3 14:10:16 2035)
Module 0x7FFAA6950000-0x7FFAA69A5000: C:/WINDOWS/SYSTEM32/WMASF.DLL (Mon Apr 26 13:31:57 2094)
Module 0x7FFAA6A80000-0x7FFAA6CD9000: C:/WINDOWS/SYSTEM32/WMVCore.DLL (Tue Jan 18 03:12:45 1983)
Module 0x7FFAA7360000-0x7FFAA736A000: C:/Windows/System32/rasadhlp.dll (Tue May 19 03:40:08 2009)
Module 0x7FFAA9660000-0x7FFAA9756000: C:/WINDOWS/SYSTEM32/PROPSYS.dll (Wed Aug 19 03:21:50 2020)
Module 0x7FFAA9AE0000-0x7FFAA9C34000: C:/WINDOWS/SYSTEM32/wintypes.dll (Wed Aug  3 12:00:49 2095)
Module 0x7FFAAA610000-0x7FFAAA96E000: C:/WINDOWS/SYSTEM32/CoreUIComponents.dll (Fri Aug 18 20:30:27 2079)
Module 0x7FFAAA970000-0x7FFAAAA62000: C:/WINDOWS/SYSTEM32/CoreMessaging.dll (Sat Aug 22 20:13:26 2082)
Module 0x7FFAAACF0000-0x7FFAAAD8E000: C:/WINDOWS/system32/uxtheme.dll (Sat Jul 13 07:14:29 2080)
Module 0x7FFAAB6B0000-0x7FFAAB914000: C:/WINDOWS/SYSTEM32/d3d11.dll (Sat Feb 28 19:03:20 2043)
Module 0x7FFAABA10000-0x7FFAABBF4000: C:/WINDOWS/SYSTEM32/dbghelp.dll (Sun Dec 23 17:14:57 2035)
Module 0x7FFAABEF0000-0x7FFAABF1F000: C:/WINDOWS/SYSTEM32/dwmapi.dll (Sat May 30 12:58:57 2037)
Module 0x7FFAAC1E0000-0x7FFAAC1F2000: C:/WINDOWS/SYSTEM32/kernel.appcore.dll (Wed Oct 30 06:42:21 2097)
Module 0x7FFAAC3E0000-0x7FFAACB74000: C:/WINDOWS/SYSTEM32/windows.storage.dll (Fri Jul 18 16:37:18 2092)
Module 0x7FFAACB80000-0x7FFAACB8D000: C:/WINDOWS/SYSTEM32/HID.DLL (Fri Mar  4 09:20:50 2050)
Module 0x7FFAACFB0000-0x7FFAACFE3000: C:/WINDOWS/SYSTEM32/ntmarta.dll (Mon Aug 19 08:32:04 2002)
Module 0x7FFAAD2A0000-0x7FFAAD331000: C:/WINDOWS/system32/schannel.DLL (Tue Feb 22 04:40:50 2005)
Module 0x7FFAAD710000-0x7FFAAD74B000: C:/WINDOWS/SYSTEM32/IPHLPAPI.DLL (Wed May 15 06:41:30 2080)
Module 0x7FFAAD750000-0x7FFAAD81A000: C:/WINDOWS/SYSTEM32/DNSAPI.dll (Thu Jan  1 02:10:29 2071)
Module 0x7FFAADA70000-0x7FFAADADA000: C:/WINDOWS/system32/mswsock.dll (Sat Oct 24 22:30:57 2099)
Module 0x7FFAADC60000-0x7FFAADC78000: C:/WINDOWS/SYSTEM32/CRYPTSP.DLL (Sun Jul 30 16:27:18 1972)
Module 0x7FFAADC80000-0x7FFAADC8C000: C:/WINDOWS/SYSTEM32/CRYPTBASE.DLL (Tue Oct  1 15:54:43 1991)
Module 0x7FFAADD10000-0x7FFAADD3C000: C:/WINDOWS/SYSTEM32/Wldp.dll (Wed May 25 20:36:01 1977)
Module 0x7FFAADE90000-0x7FFAADEA2000: C:/WINDOWS/SYSTEM32/MSASN1.dll (Sat Nov 22 19:28:47 2053)
Module 0x7FFAAE170000-0x7FFAAE1A2000: C:/WINDOWS/SYSTEM32/SSPICLI.DLL (Mon Oct  4 18:23:02 2083)
Module 0x7FFAAE1F0000-0x7FFAAE20F000: C:/WINDOWS/SYSTEM32/profapi.dll (Wed Jun 14 15:18:12 2034)
Module 0x7FFAAE2B0000-0x7FFAAE3B0000: C:/WINDOWS/System32/ucrtbase.dll (Fri Apr 23 01:39:11 1993)
Module 0x7FFAAE3B0000-0x7FFAAE4BB000: C:/WINDOWS/System32/gdi32full.dll (Wed Feb  9 20:42:41 2022)
Module 0x7FFAAE4C0000-0x7FFAAE616000: C:/WINDOWS/System32/CRYPT32.dll (Thu Mar 23 14:05:51 2028)
Module 0x7FFAAE620000-0x7FFAAE66E000: C:/WINDOWS/System32/cfgmgr32.dll (Mon Aug 14 18:05:09 1972)
Module 0x7FFAAE670000-0x7FFAAE692000: C:/WINDOWS/System32/win32u.dll (Tue May  3 20:26:59 1977)
Module 0x7FFAAE6A0000-0x7FFAAE968000: C:/WINDOWS/System32/KERNELBASE.dll (Sun May 12 20:23:48 1974)
Module 0x7FFAAEA20000-0x7FFAAEABD000: C:/WINDOWS/System32/msvcp_win.dll (Fri May 19 15:25:03 2000)
Module 0x7FFAAEAC0000-0x7FFAAEB42000: C:/WINDOWS/System32/bcryptPrimitives.dll (Sat Apr 24 18:55:19 2094)
Module 0x7FFAAEB50000-0x7FFAAEBB8000: C:/WINDOWS/System32/WINTRUST.dll (Thu Apr 11 17:11:02 2002)
Module 0x7FFAAEBC0000-0x7FFAAEBE7000: C:/WINDOWS/System32/bcrypt.dll (Tue May 26 09:18:52 2020)
Module 0x7FFAAF1A0000-0x7FFAAF24E000: C:/WINDOWS/System32/ADVAPI32.dll (Fri Aug  3 09:33:21 1979)
Module 0x7FFAAF250000-0x7FFAAF2BB000: C:/WINDOWS/System32/WS2_32.dll (Wed Jul 18 02:18:03 2063)
Module 0x7FFAAF2C0000-0x7FFAAF2EB000: C:/WINDOWS/System32/GDI32.dll (Sat Mar 27 12:16:23 2055)
Module 0x7FFAAF2F0000-0x7FFAAF415000: C:/WINDOWS/System32/RPCRT4.dll (Wed Jan 25 01:08:05 2090)
Module 0x7FFAAF480000-0x7FFAAF53E000: C:/WINDOWS/System32/KERNEL32.DLL (Sun Apr  5 07:12:25 2099)
Module 0x7FFAAF700000-0x7FFAAF730000: C:/WINDOWS/System32/IMM32.DLL (Sun Nov 12 13:21:08 2000)
Module 0x7FFAAF730000-0x7FFAAF786000: C:/WINDOWS/System32/WLDAP32.dll (Fri Dec 29 15:10:51 1972)
Module 0x7FFAAF7F0000-0x7FFAAF7F8000: C:/WINDOWS/System32/NSI.dll (Tue Sep 14 10:48:33 2060)
Module 0x7FFAAF8E0000-0x7FFAAF97E000: C:/WINDOWS/System32/msvcrt.dll (Fri Nov 20 22:31:21 2015)
Module 0x7FFAAF980000-0x7FFAAFA4D000: C:/WINDOWS/System32/OLEAUT32.dll (Fri Oct  1 03:07:23 2021)
Module 0x7FFAAFA50000-0x7FFAAFB66000: C:/WINDOWS/System32/MSCTF.dll (Fri Jul  4 07:03:14 2081)
Module 0x7FFAAFB70000-0x7FFAAFB8D000: C:/WINDOWS/System32/imagehlp.dll (Wed Sep 18 13:08:08 2002)
Module 0x7FFAAFB90000-0x7FFAAFC2C000: C:/WINDOWS/System32/sechost.dll (Sun Jul 27 21:50:25 2014)
Module 0x7FFAAFC30000-0x7FFAAFCDD000: C:/WINDOWS/System32/shcore.DLL (Tue Jul 10 03:29:18 2085)
Module 0x7FFAAFCE0000-0x7FFAAFD35000: C:/WINDOWS/System32/SHLWAPI.dll (Tue Oct  7 06:37:27 2092)
Module 0x7FFAAFD40000-0x7FFAAFD48000: C:/WINDOWS/System32/PSAPI.dll (Fri Mar 31 17:36:50 1978)
Module 0x7FFAAFD50000-0x7FFAAFEF0000: C:/WINDOWS/System32/USER32.dll (Sat Jan 14 19:08:17 2090)
Module 0x7FFAAFF70000-0x7FFAB02C4000: C:/WINDOWS/System32/combase.dll (Sun Jan 22 17:19:10 2102)
Module 0x7FFAB02D0000-0x7FFAB03FA000: C:/WINDOWS/System32/ole32.dll (Sat Apr 12 01:16:33 2070)
Module 0x7FFAB0400000-0x7FFAB0B44000: C:/WINDOWS/System32/SHELL32.dll (Wed Mar  7 22:06:18 2057)
Module 0x7FFAB0B90000-0x7FFAB0D85000: C:/WINDOWS/SYSTEM32/ntdll.dll (Thu Nov  1 06:31:04 1984)

advapi32.dll: 1 0 0 0
bcrypt.dll: 0 0 0 0
bcryptprimitives.dll: 0 0 0 0
cfgmgr32.dll: 0 0 0 0
combase.dll: 1 1 0 0
comctl32.dll: 0 0 1 1
coremessaging.dll: 0 1 1 1
coreuicomponents.dll: 0 1 1 1
crypt32.dll: 0 0 0 0
cryptbase.dll: 0 0 0 0
cryptsp.dll: 0 0 0 0
d3d11.dll: 1 0 0 0
d3dcompiler_43.dll: 0 0 1 1
d3dx10_43.dll: 0 0 1 0
d3dx9_43.dll: 0 0 1 0
dbgcore.dll: 0 0 0 0
dbghelp.dll: 0 0 0 0
dinput8.dll: 1 0 0 0
dnsapi.dll: 0 0 0 0
dwmapi.dll: 0 0 0 0
dxgi.dll: 1 1 0 0
easyhook64.dll: 0 0 1 0
fwpuclnt.dll: 0 0 0 0
gdi32.dll: 0 0 0 0
gdi32full.dll: 0 1 1 1
glu32.dll: 1 0 0 0
hid.dll: 0 0 0 0
imagehlp.dll: 0 0 0 0
imm32.dll: 0 1 1 1
innerspace.dll: 0 1 1 1
inputhost.dll: 1 0 0 0
iphlpapi.dll: 0 0 1 0
k_fps64.dll: 0 0 1 0
kernel.appcore.dll: 0 0 0 0
kernel32.dll: 0 0 1 0
kernelbase.dll: 1 0 1 0
mfperfhelper.dll: 0 0 0 0
msasn1.dll: 0 0 0 0
msctf.dll: 0 1 1 1
msvcp_win.dll: 0 0 0 0
msvcrt.dll: 0 0 0 0
mswsock.dll: 0 0 0 0
nsi.dll: 0 0 0 0
ntdll.dll: 0 0 1 0
ntmarta.dll: 0 0 0 0
ole32.dll: 1 1 0 0
oleaut32.dll: 1 1 0 0
opengl32.dll: 1 0 0 0
profapi.dll: 0 0 0 0
propsys.dll: 0 0 0 0
psapi.dll: 0 0 0 0
rasadhlp.dll: 0 0 0 0
rpcrt4.dll: 0 0 0 0
schannel.dll: 0 0 1 1
sechost.dll: 0 0 0 0
secur32.dll: 0 0 0 0
setupapi.dll: 0 0 0 0
shcore.dll: 0 1 0 0
shell32.dll: 1 0 0 0
shlwapi.dll: 0 0 0 0
shunimpl.dll: 1 1 0 0
sspicli.dll: 0 0 0 0
ucrtbase.dll: 0 1 0 0
user32.dll: 1 0 0 0
uxtheme.dll: 0 0 0 0
version.dll: 0 1 0 0
win32u.dll: 0 0 0 0
windows.storage.dll: 0 1 0 0
winhttp.dll: 0 0 1 0
wininet.dll: 0 0 0 0
winmm.dll: 1 0 0 0
wintrust.dll: 0 0 0 0
wintypes.dll: 0 0 0 0
wldap32.dll: 0 0 0 0
wldp.dll: 0 0 0 0
wmasf.dll: 0 0 0 0
wmvcore.dll: 0 0 0 0
ws2_32.dll: 0 0 0 0

**Comment by goaaats** [comment]
I don't have the resources to support anything at all related to inner space, sorry.
