### ISSUE TITLE
 Die angeforderten Informationen können nicht ermittelt werden, da der Prozess nicht vom Objekt gestartet wurde

### ISSUE THREAD

**Issue by K1inge** [goatcorp/FFXIVQuickLauncher#843]
System.InvalidOperationException: Die angeforderten Informationen können nicht ermittelt werden, da der Prozess nicht vom Objekt gestartet wurde.
   bei System.Diagnostics.Process.EnsureState(State state)
   bei System.Diagnostics.Process.get_ExitCode()
   bei XIVLauncher.Windows.ViewModel.MainWindowViewModel.<TryProcessLoginResult>d__25.MoveNext() in D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:Zeile 602.

Version: 6.2.28.0
Git Hash: 6.2.28-0-gd8cb058
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: German
LauncherLanguage: German
Game path: C:\FFXIV\SquareEnix\FINAL FANTASY XIV - A Realm Reborn

**Comment by goaaats** [comment]
Should be fixed now, please restart XIVLauncher and update.
