### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by zeautumn** [goatcorp/FFXIVQuickLauncher#853]
Unexpected error when I close the game.

![Capture d’écran 2022-04-12 111504](https://user-images.githubusercontent.com/94714182/162995755-47254ef7-61de-45ce-9f22-704fd9d53f1a.png)
![Capture d’écran 2022-04-12 111522](https://user-images.githubusercontent.com/94714182/162995759-e80874e6-afc5-4011-9aa0-b4af8051eddf.png)
![Capture d’écran 2022-04-12 111540](https://user-images.githubusercontent.com/94714182/162995760-b1507a3f-b6fa-472e-8ca6-518929dcd228.png)

**Comment by goaaats** [comment]
Should be fixed now, please restart XIVLauncher and update.
