### ISSUE TITLE
Dalamud has not been updated for FFXIV Patch 6.1

### ISSUE THREAD

**Issue by reiichi001** [goatcorp/FFXIVQuickLauncher#862]
Things will be ready when people have time to work on fixing Dalamud and their plugins. There are a number of breaking changes in 6.1 that will require time to fix and adjust for. Please do not expect to have Dalamud or <plugin> in time for your raids.

Please remember that devs also have work, school, and other priorities that aren't related to community development for FFXIV. Your patience and understanding is appreciated.

**Comment by elizeuW** [comment]
i'm a brazilian and i want to know how many days it will release already??

**Comment by goaaats** [comment]
There's no time estimate. You'll have to wait and see, a lot of things don't work.
