### ISSUE TITLE
Error during 6.1 after closing the game

### ISSUE THREAD

**Issue by wagnerprestrelo** [goatcorp/FFXIVQuickLauncher#866]
System.InvalidOperationException: Processo não foi iniciado por este objeto. Portanto, as informações solicitadas não podem ser determinadas.
   em System.Diagnostics.Process.EnsureState(State state)
   em System.Diagnostics.Process.get_ExitCode()
   em XIVLauncher.Windows.ViewModel.MainWindowViewModel.<TryProcessLoginResult>d__25.MoveNext() na D:\a\FFXIVQuickLauncher\FFXIVQuickLauncher\src\XIVLauncher\Windows\ViewModel\MainWindowViewModel.cs:linha 602

Version: 6.2.28.0
Git Hash: 6.2.28-0-gd8cb058
Context: Login
OS: Microsoft Windows NT 6.2.9200.0
64bit? True
DX11? True
Addons Enabled? True
Auto Login Enabled? True
Language: English
LauncherLanguage: Portuguese
Game path: E:\SteamLibrary\steamapps\common\FINAL FANTASY XIV Online

**Comment by goaaats** [comment]
Should be fixed now, please restart XIVLauncher and update.
