### ISSUE TITLE
Blurred font in plugin window after opening the game

### ISSUE THREAD

**Issue by pearcehao** [goatcorp/FFXIVQuickLauncher#893]
![213](https://user-images.githubusercontent.com/103523684/163704060-d3fca711-398d-4375-88ed-1c1c7ec7bd36.png)
![231](https://user-images.githubusercontent.com/103523684/163704064-de2e744f-cf1e-4441-b5d5-1faf0d4b9f01.png)

**Comment by RunninS** [comment]
same problem 
![image](https://user-images.githubusercontent.com/31590185/164353458-3a911105-6e5d-4129-9435-347122886346.png)
everything is blurry

**Comment by NotNite** [comment]
Sorry for the delay! This is the wrong repository to report this on - if it's still happening, make an issue on [goatcorp/Dalamud](https://github.com/goatcorp/Dalamud).
