### ISSUE TITLE
AUR deployment

### ISSUE THREAD

**Issue by goaaats** [goatcorp/FFXIVQuickLauncher#905]
Binary release, from source?

**Comment by Centzilius** [comment]
For now I have created 
* https://aur.archlinux.org/packages/xivlauncher (Builds from tags of this repo)
* https://aur.archlinux.org/packages/xivlauncher-git (Builds from HEAD of this repo).
@cali666 is going to publish a -bin package for prebuilt releases of XIVLauncher.Core

**Comment by TiffanyNeat** [comment]
Hey I tried running the XLCore aur repository on my desktop Linux computer, and it just does not start. Tried with the launch options recommended in the steam deck guide too, same thing happened. I put in the newest version of Proton GE, was I not supposed to do that and it just didn't say there? Or if I am, what am I doing wrong?

**Comment by reiichi001** [comment]
> Hey I tried running the (non-git) XLCore aur repository on my desktop Linux computer, and it just does not start. Tried with the launch options recommended in the steam deck guide too, same thing happened. I put in the newest version of Proton GE, was I not supposed to do that and it just didn't say there? Or if I am, what am I doing wrong?

The not-git version is extremely outdated and shouldn't be used. You'll want to target the xivlauncher-git package or use the flatpak.

XLCore will not work in proton, as it uses its own custom build of Wine. The Proton-GE/protonfix setups should also still work, but I'd recommend sticking to xlcore. If using the flatpak, you'll want to grab flatseal to grant the xivlauncher flatpak access to all storage. See our FAQ for more information on setup steps.

**Comment by TiffanyNeat** [comment]
alrightsie! very good to know thank you for answering. so i just pop it open and it runs its own version of wine off the bat?

**Comment by NotNite** [comment]
*Not* closing this issue (summer cleaning o/) because the binaries are frequently out of date. We need a solution for this.

**Comment by Centzilius** [comment]
Since Centzilius/aur-xivlauncher/pull/3 has now been merged do you think anything else is left to do about this @NotNite ?

**Comment by NotNite** [comment]
LGTM
