### ISSUE TITLE
Plugins commands not working

### ISSUE THREAD

**Issue by Niniisan** [goatcorp/FFXIVQuickLauncher#928]
Since the last update, all of my plugins' command show and "does not exist". I've tried deactivating every one of them, then reactivating - same error message in game.
I've tried reinstalling as well, but it's still here as an issue. I'm wondering if I deinstalled correctly maybe, but I'm not so sure. They're here, my game detects that Dalamud Plugins are activated, but the commands simply show as "do not exist", therefore, I can't use my plugins. How can I reslove this?

**Comment by reiichi001** [comment]
Hello! Have you used any language mods or do you have any plugins that modify how chat works?

What language are you launching with?

Can you please post a screenshot of the error?

**Comment by Niniisan** [comment]
Hello! Well, I have the chats bubbles and also tweaks - tweaks used to change some usernames' colors, it's also up to date. I'm launching with French language, since my game's in French as well - the error is basically just the chat telling me the command doesn't exist, but here it is (in french): (also, when I tried reinstalling the launcher, it basically just did a quick opening without a download and immediately launched FF) [https://imgur.com/a/isNA8DE](url)

**Comment by reiichi001** [comment]
I'm going to need the core devs to look into this further. All of the plugin command work by looking for that error text and then intercept it, but this is the second time I've seen it fail with a not-English language, even though we check for all global client languages.

Does it start working again if you disable all of your plugins?

**Comment by Niniisan** [comment]
Nope, I've tried that. It doesn't change anything :c

**Comment by Athavar** [comment]
I have the same problem.
After switching the client language from german to english commands work again.

I have noticed that in both cases in StartInfo the Language Property is set to 1 (Have used the Dalamud Data window).

**Comment by Niniisan** [comment]
So... basically I should have my game in English, even though I've never played in English? Don't get me wrong - I have a fluent English, but I'm mostly used to my game being in French. Is there really no solution that doesn't involve going for English?

**Comment by reiichi001** [comment]
> So... basically I should have my game in English, even though I've never played in English? Don't get me wrong - I have a fluent English, but I'm mostly used to my game being in French. Is there really no solution that doesn't involve going for English?

No, this is a bug. It should work with any of the supported languages. The temporary solution is launching the game in English. That's not the permanent fix.

**Comment by Niniisan** [comment]
Oh, alright, I didn't understand it that way. I just need to remember where to change the language and be on the lookout for any update basically

**Comment by reiichi001** [comment]
Do you happen to be on Dalamud stable or Dalamud Testing?

Could you please upload your `dalamud.log` from `%appdata%\xivlauncher` please? (When launched in a not-English language). 

I launched the game in Japanese and could use commands fine, and startinfo appropriately updated. That was on Dalamud 6.4.0.8 Stable.

**Comment by Athavar** [comment]
In my case i use the version 6.4.0.8. For this run I have also renamed dalamudConfig.json and the folder installedPlugins to have a clean state.
[dalamud.log](https://github.com/goatcorp/FFXIVQuickLauncher/files/8589890/dalamud.log)
![grafik](https://user-images.githubusercontent.com/9285323/165920671-c94b968f-7a8e-4dfd-b681-daba948499e8.png)
![grafik](https://user-images.githubusercontent.com/9285323/165922127-454cd045-d5ae-4671-98aa-6e34313251ef.png)

**Comment by Niniisan** [comment]
(sorry, I just failed :x)

**Comment by Niniisan** [comment]
Also, I would try to launch the game in English but I choose auto launch on the XIVLauncher and I'm not sure how to reverse that

**Comment by tommadness** [comment]
Hold shift when starting the launcher.

**Comment by Niniisan** [comment]
I did just that, yeah. I've opened the game in English but can't seem to access any dalamug log in French because of the log's file type

**Comment by Niniisan** [comment]
> Do you happen to be on Dalamud stable or Dalamud Testing?
> 
> Could you please upload your `dalamud.log` from `%appdata%\xivlauncher` please? (When launched in a not-English language).
> 
> I launched the game in Japanese and could use commands fine, and startinfo appropriately updated. That was on Dalamud 6.4.0.8 Stable.

I cannot find dalamud log in French.  Or, I can find one, but it has a file name type that cannot be sent here. It is set as an ".OLD" file. (image attached : ) [https://imgur.com/a/QrAOtVP](url)

**Comment by reiichi001** [comment]
We've identified the cause and it'll be fixed in the next Dalamud update.

**Comment by Niniisan** [comment]
Alright! Thanks for your time!

**Comment by reiichi001** [comment]
Dalamud 6.4.0.9 should fix this. We're waiting for the deployment to finish up, so you should see it within the next couple of hours if/when you relaunch.
