### ISSUE TITLE
Burning down the House does not show up

### ISSUE THREAD

**Issue by Shorski** [goatcorp/FFXIVQuickLauncher#930]
Don't know if it was removed or a bug, but when I search for Burning Down the House it doesn't appear in the search bar. Doesn't show up at all. Any help is appreciated.

**Comment by reiichi001** [comment]
We do not provide support for plugins installed from custom plugin repositories (aka third party plugins). It's likely out of date and needs to be updated.

Please consult the developer[s] of the plugin through their support channels.

**Comment by Shorski** [comment]
Sounds good, sorry I just installed to use it so I'm still new to the software. Thanks for the quick response
