### ISSUE TITLE
Core - Prevent running as root user

### ISSUE THREAD

**Issue by rekyuu** [goatcorp/FFXIVQuickLauncher#936]
Implement a check to validate that XL.Core is not being run as the root user.

### Version

Native/Core version (Linux)

### Platform

Linux (native)

**Comment by Zi-SH** [comment]
Should XLCore ever be running as Admin on Windows? Could knock out both at the same time if not.

**Comment by rekyuu** [comment]
Looks like this was merged by #958 so it can be closed.
