### ISSUE TITLE
[flatpak, Steam Deck] Steam text input window for OTP does not close automatically when using OTP macro

### ISSUE THREAD

**Issue by tommadness** [goatcorp/FFXIVQuickLauncher#940]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to FFXIV updating and plugins not working correctly.

### What did you do?

Run XIV Launcher through Flatpak in Gamemode. Progress through login until the Steam text input for OTP appears. Use XLAuthenticator to send OTP to the webserver.

OTP input needs to be manually closed, instead of closing automatically.

### Platform

Linux (native)

### Wine/Proton runner version

Flatpak on Steam Deck game mode

**Comment by goaaats** [comment]
Sadly, I don't think this is possible, or I can't spot a way to :/ Might be best to just turn that feature off if people are using the app.
https://partner.steamgames.com/doc/api/ISteamUtils#ShowGamepadTextInput

**Comment by tommadness** [comment]
I think that's a decent workaround; not pulling up the text input if OTP macro is enabled.

**Comment by goaaats** [comment]
Implemented the workaround
