### ISSUE TITLE
[flatpak] Steam IPC doesn't clean up when exiting game

### ISSUE THREAD

**Issue by tommadness** [goatcorp/FFXIVQuickLauncher#941]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to FFXIV updating and plugins not working correctly.

### What did you do?

After closing FFXIV and XIVLauncher, Steam never receives the signal that FFXIV has closed.

### Platform

Linux (native)

### Wine/Proton runner version

XIVLauncher Flatpak

**Comment by goaaats** [comment]
I believe that this was an issue specific to the flatpak?

**Comment by tommadness** [comment]
Correct

**Comment by HLennart** [comment]
i can confirm this only happens on the flatpak version (reported version 1.0.0.1)

**Comment by tommadness** [comment]
Resolved in v1.0.0.3

**Comment by goaaats** [comment]
Please follow the step to set up a non-steam shortcut in the steam deck guide: https://goatcorp.github.io/faq/steamdeck

**Comment by HLennart** [comment]
does the flatpak version only exit the game properly if it's added as a non-steam game to steam?

**Comment by goaaats** [comment]
No, it just needs the extra launch args that we have in the guide, you can probably just edit your .desktop file too

**Comment by HLennart** [comment]
oh thank you very much! is that documented anywhere for just the flatpak?

**Comment by goaaats** [comment]
Not yet, what's a good place/where did you check before commenting here

**Comment by HLennart** [comment]
I checked https://flathub.org/apps/details/dev.goats.xivlauncher and pinned messages in the discord.
Since flathub is where people will get the flatpak from it seems most sensible to document it on there
