### ISSUE TITLE
[flatpak, Steam] SteamAPI_init() failed

### ISSUE THREAD

**Issue by Rioluuu** [goatcorp/FFXIVQuickLauncher#946]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to FFXIV updating and plugins not working correctly.

### What did you do?

When trying to sign in using a Steam account in flatpaked XIVLauncher, the error message "SteamAPI_init() failed" shows up. Steam is also running as a flatpak.

Distribution: Fedora Silverblue 36

### Platform

Linux (native)

**Comment by NotNite** [comment]
The reason is Steam is running as a Flatpak. Running with system Steam should work. There might also be some Flatseal trickery you can do? - maybe ask in our `#linux-and-deck` channel in [our Discord server](https://goat.place/).
