### ISSUE TITLE
Removing Chat Message on Login

### ISSUE THREAD

**Issue by Rynn21** [goatcorp/FFXIVQuickLauncher#947]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to FFXIV updating and plugins not working correctly.

### What did you do?

[LogKind未設定]Dalamud vD6.4.0.9 loaded. 11 plugin(s) loaded. 

How do you remove it from showing up upon login? I already had gone to Dalamud Settings and unchecked "Display loaded plugins in the welcome message", but every login still shows it in chat. Been like it for a week since installing.

### Platform

Windows

**Comment by NotNite** [comment]
This is the wrong repo to report this on. If you want to suggest hiding this message, leave it on [the right repository](https://github.com/goatcorp/Dalamud).
