### ISSUE TITLE
Cannot shift click to open launcher to get into settings

### ISSUE THREAD

**Issue by Garreezy** [goatcorp/FFXIVQuickLauncher#951]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to FFXIV updating and plugins not working correctly.

### What did you do?

I messed up and did not apply a certain setting that will let me launch /xlplugins in the game and it wont let me shift click the launcher to load it up again. (I have the auto load up setting on) I tried re-installing the launcher and it keeps the auto login settings and does not pop up. I have also tried restarting the pc and still nothing. any suggestions?   

### Platform

Windows

### Relevant log output

```shell
n/a
```

**Comment by Garreezy** [comment]
> Keep holding shift until the launcher appears, not just while clicking on the icon.

Still not working :|

**Comment by Garreezy** [comment]
Is there an older version that I can install that will work and let me get into the settings? I am not sure why its not popping up at all. and it used to.

**Comment by reiichi001** [comment]
> Is there an older version that I can install that will work and let me get into the settings? I am not sure why its not popping up at all. and it used to.

If keeping the shift key held down when you open XIVLauncher isn't working, you can also directly modify its configuration file to disable autologin.

To do so, head to `%appdata%\XIVLauncher` and look for a file named `launcherConfigV3.json` and open it in your text editor of choice. (Notepad is fine, don't use Wordpad or Word or other rich-text editors).

Find:
`"AutologinEnabled": "true",`
Replace with:
`"AutologinEnabled": "false",`

If in doubt, you can delete the file entirely, but then you'll need to set up XIVLauncher again.

**Comment by Garreezy** [comment]
> > Is there an older version that I can install that will work and let me get into the settings? I am not sure why its not popping up at all. and it used to.
> 
> If keeping the shift key held down when you open XIVLauncher isn't working, you can also directly modify its configuration file to disable autologin.
> 
> To do so, head to `%appdata%\XIVLauncher` and look for a file named `launcherConfigV3.json` and open it in your text editor of choice. (Notepad is fine, don't use Wordpad or Word or other rich-text editors).
> 
> Find: `"AutologinEnabled": "true",` Replace with: `"AutologinEnabled": "false",`
> 
> If in doubt, you can delete the file entirely, but then you'll need to set up XIVLauncher again.

You are a legend! thank you very much for helping you guys.
