### ISSUE TITLE
[Core][Linux/Flatpak] Add feedback to the OTP step

### ISSUE THREAD

**Issue by ChristopherJTrent** [goatcorp/FFXIVQuickLauncher#952]
### Update disclaimer

- [X] Yes, I have checked and my request is not related to FFXIV updating and plugins not working correctly.

### What happened, what did not, what did you want to happen?

When I input my OTP, it'd be nice for there to be some feedback when the OTP has been accepted, and the launcher is waiting on other blocking steps, e.g steam integration or file verification. Even something as simple as just a spinning wheel would be better than no feedback.

### Version

Native/Core version (Linux)

### Platform

Linux (native)

**Comment by goaaats** [comment]
It's supposed to, it not being there is a bug

**Comment by ChristopherJTrent** [comment]
I see. The below image is what I'm seeing in my XL window
![image](https://user-images.githubusercontent.com/50601711/168177611-131b0354-19a8-4f81-a08e-82ec020b4f07.png)

**Comment by ChristopherJTrent** [comment]
Could it be related that the launcher hangs for about 2 minutes on DalamudLauncher::HoldForUpdate(gp:/home/<my_name>/.xlcore/ffxiv)?

**Comment by ChristopherJTrent** [comment]
Did some more testing.
This only happens when all of the authentication steps succeed. If SteamAPI fails, or my OTP is wrong, or my SE password is wrong, the feedback shows up as normal.

**Comment by ChristopherJTrent** [comment]
Actually, this was fixed in the most recent update. All feedback is now showing as expected.

Closing as fixed.
