### ISSUE TITLE
Flatpak: Gamemode not found

### ISSUE THREAD

**Issue by ChristopherJTrent** [goatcorp/FFXIVQuickLauncher#954]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to FFXIV updating and plugins not working correctly.

### What did you do?

In the launcher's settings/wine tab, whenever I click "Enable Gamemode", I get an error saying that gamemode wasn't found.
I checked the source code, and grepped for the /usr/lib/libgamemodeauto.so.0 file that that module is looking for, and it's very much present. Not sure what to do from here.

Thought: Is it possible that File.Exists isn't playing nice with Symbolic Links at https://github.com/goatcorp/FFXIVQuickLauncher/blob/0971dfd5533ba53413916d38a86f629120ff3bd9/src/XIVLauncher.Core/Components/SettingsPage/Tabs/SettingsTabWine.cs#L26-L35

### Platform

Linux (native)

### Wine/Proton runner version

Uncertain, bug is in native code.

### Relevant log output

```shell
"GameMode not detected".
```

**Comment by Zi-SH** [comment]
This is a known issue that is being looked into. For the time being, you should be able to get similar performance gains by setting your CPU governor to Performance.

**Comment by ChristopherJTrent** [comment]
Ah, Okiedoke. I'll go ahead and close this then, since it's a known issue.

**Comment by schippie** [comment]
I was wondering given that this issue was closed if there had been any further progress regarding resolving the issue? I did read gamemode has support for flatpak but requires some changes on how to detect it.  But not sure if any such changes where ever made.
