### ISSUE TITLE
Add option to use Free Trial App ID for XLCore

### ISSUE THREAD

**Issue by JDGBOLT** [goatcorp/FFXIVQuickLauncher#959]
### Update disclaimer

- [X] Yes, I have checked and my request is not related to FFXIV updating and plugins not working correctly.

### What happened, what did not, what did you want to happen?

The Steam Deck has a "feature" where it will close a window in gaming mode if the game in question is not installed and it does a periodic check for installed games. Most noticeable if you put the deck to sleep and wake it up while ffxiv is running, as the window will disappear as the Source 2013 SDK is not installed, but have had it happen on other occasions. The Source SDK is about 3.5 gigs of space, so not ideal to have installed on the steam deck. Would be nice to have an option to use the ffxiv free trial app id rather than the source sdk for those of us who have added it to their account, as it will provide both a more seamless experience in switching to the window in gaming mode, access to the free trial controller configurations, and also even installed it's only 50 megs of space if you don't run the launcher. Would involve either the code block at
https://github.com/goatcorp/FFXIVQuickLauncher/blob/master/src/XIVLauncher.Core/Program.cs#L151 and having another option for the free trial check but not doing the other logic from the free trial toggle in the settings. Or could modify https://github.com/goatcorp/FFXIVQuickLauncher/blob/master/src/XIVLauncher.Core/Program.cs#L159 and have it use the free trial app id, or could be any number of other implementations. Just would be nice to have it as an option for those of us with a deck and the free trial but are playing with a standard non-steam account.

### Version

Native/Core version (Linux)

### Platform

Linux (native)

**Comment by NotNite** [comment]
This was fixed a while ago - not sure why this issue is still open.
