### ISSUE TITLE
XiV Launcher disappeared from pc completely

### ISSUE THREAD

**Issue by Sinhshulva** [goatcorp/FFXIVQuickLauncher#973]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to FFXIV updating and plugins not working correctly.

### What did you do?

I booted up my PC today and the launcher is completely gone for no apparent reason. Used it yesterday with no issues. Where did it go? Game is still installed and boots up fine from normal steam launcher.

### Platform

Windows

**Comment by goaaats** [comment]
Your antivirus deleted it, please check out this help article: https://goatcorp.github.io/faq/xl_troubleshooting#q-how-do-i-whitelist-xivlauncher-and-dalamud-so-my-antivirus-leaves-them-alone

We can't really help you any further than that, since we know nothing about the antivirus or your system.
