### ISSUE TITLE
Quarantined by my antivirus 

### ISSUE THREAD

**Issue by gaaralock** [goatcorp/FFXIVQuickLauncher#977]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to FFXIV updating and plugins not working correctly.

### What did you do?

After the update, the launcher was flagged and quarantined by my antivirus software

### Platform

Windows

**Comment by goaaats** [comment]
There's nothing we can do about this, you need to whitelist it: https://goatcorp.github.io/faq/xl_troubleshooting#q-how-do-i-whitelist-xivlauncher-and-dalamud-so-my-antivirus-leaves-them-alone
