### ISSUE TITLE
Game won't start up

### ISSUE THREAD

**Issue by hinacchis** [goatcorp/FFXIVQuickLauncher#979]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to FFXIV updating and plugins not working correctly.

### What did you do?

I just close it in Task Manager but I figured I should report it?

### Platform

Windows

**Comment by zevadrows** [comment]
The same is happening with my wife. Steam says the game is running, it is running on Task Manager, but the game wont load on the screen. If running the game directly from Steam, it works fine.

**Comment by hinacchis** [comment]
I found out it was because of Razer Cortex! Thank you for telling me!

**Comment by zevadrows** [comment]
We don't have this Razer Cortex :(

**Comment by NotNite** [comment]
> The same is happening with my wife. Steam says the game is running, it is running on Task Manager, but the game wont load on the screen. If running the game directly from Steam, it works fine.

Is this still happening? Can you join our [Discord server](https://goat.place/) so I can see your logs? My username is `NotNite#0001`.

**Comment by zevadrows** [comment]
Nope! It solved by itself. I think it was some problem with Steam, and not the Launcher or FF
