### ISSUE TITLE
国服使用使用启动器登录不了

### ISSUE THREAD

**Issue by yuanjie408** [goatcorp/FFXIVQuickLauncher#998]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to FFXIV updating and plugins not working correctly.

### What did you do?

![K %GW$Y(TOQW RW}LVZ8XUN](https://user-images.githubusercontent.com/88411181/170827431-7d0b59ab-6924-4ded-8975-216d9d9d6092.png)

一直是这样子，无法使用这个启动器登录，叨鱼也没有反应

### Platform

Windows

**Comment by goaaats** [comment]
I don't speak Chinese and can't support Chinese-patched clients
