### ISSUE TITLE
How to enable auto advanced combat tracker to startup with XIVLauncher?

### ISSUE THREAD

**Issue by nammerduong** [goatcorp/FFXIVQuickLauncher#999]
### Update disclaimer

- [X] Yes, I have checked and my issue is not related to FFXIV updating and plugins not working correctly.

### What did you do?

I remember when I first installed XIVLauncher there was an option to auto start Advanced Combat Tracker when launching with XIVLauncher. However, I didn't check it off and now I have no idea how to turn it on? I even tried to uninstall the launcher and install again but that did nothing. 

### Platform

Windows

**Comment by NadyaNayme** [comment]
Hold shift when opening the launcher if you have it auto-login/start. Go to the launcher settings. I think there's a Startup tab - might be named something else or under one of the other settings in the launcher. Put the shortcut or path to the .exe in the big text area and it'll run on startup.

I'm in-game or I'd be able to give better directions with more precise verbiage but you should be able to find what I'm talking about.

**Comment by NotNite** [comment]
Let us know if you're having any issues setting auto launch up following the above instructions - if you are, feel free to leave a response or join our [Discord server](https://goat.place/). If not, you can close the issue or I'll do it in a day or so.
